import test from 'node:test';
import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
const root=path.resolve(import.meta.dirname,'../..');
const temporary=await mkdtemp(path.join(tmpdir(),'kit-mseg-'));
const bundle=async (name,source)=>{const outfile=path.join(temporary,name+'.mjs');await build({entryPoints:[path.join(root,source)],outfile,bundle:true,format:'esm',platform:'node',logLevel:'silent'});return import(pathToFileURL(outfile));};
const kit=await bundle('kit','kit/ui/mseg.ts');
test.after(()=>rm(temporary,{recursive:true,force:true}));
const {msegCurveCodec}=await bundle('codec','kit/ui/mseg-state.ts');
test('curve codec rejects poisoned coordinates, owns its points, and reports ordering failure',()=>{
 const input=kit.addMsegPoint(kit.createDefaultMsegShape(),.4,.7),result=msegCurveCodec.parse(input);
 assert.equal(result.kind,'ok');assert.ok(Object.isFrozen(result.value));assert.ok(Object.isFrozen(result.value.points[1]));
 input.points[1].y=.1;assert.equal(result.value.points[1].y,.7);
 assert.equal(msegCurveCodec.parse({...input,points:[input.points[0],{x:.4,y:Infinity,curvePower:0},input.points[2]]}).kind,'error');
 const reversed={...input,points:[input.points[0],{x:.8,y:.3,curvePower:0},{x:.2,y:.5,curvePower:0},input.points[2]]};
 assert.deepEqual(msegCurveCodec.parse(reversed),{kind:'error',message:'MSEG shape points must stay in non-decreasing x order'});
});
