// Generated from ui/shared/lane-state.ts by node ui/build.mjs. Do not edit this file directly.
import { LEGACY_LANE_DEVICE_PARAM_ENDPOINTS, LANE_SLOT_ORDINAL_COUNT, LANE_SLOT_TYPE_COUNT, buildLaneSlotParamValues, getLaneSlotId, getLaneSlotParamIndex, } from "./lane-slot-params.js";
import { getRackEffectDescriptor } from "./rack-parameter-descriptors.js";
/**
 * Canonical stored-state key for the Effects Lane document. lane.v1 owns the
 * complete effect surface: chain order, per-device enables, and EVERY device
 * parameter value — since the B3 parameter cut there are no per-effect host
 * endpoints, so this document is the single durable owner of those values.
 *
 * v1 carries exactly one device of each type (the shipping editor's surface);
 * the device-instance tree arrives with the add/remove UX.
 */
export const LANE_STATE_KEY = "lane.v1";
/** DSP endpoint receiving the complete lane structure: chain + enable mask. */
export const LANE_TOPOLOGY_ENDPOINT_ID = "laneTopology";
/** DSP endpoint receiving one device's complete positional parameter record. */
export const LANE_SLOT_PARAMS_ENDPOINT_ID = "laneSlotParams";
/** DSP endpoint receiving one live-edited parameter field. */
export const LANE_SLOT_PARAM_VALUE_ENDPOINT_ID = "laneSlotParamValue";
/** DSP endpoint reporting the committed structure after its transition. */
export const EFFECTIVE_RACK_STATE_ENDPOINT_ID = "effectiveRackState";
/** Wire capacity of one lane chain (engine maxLaneChainLength). */
export const LANE_MAX_CHAIN_LENGTH = 16;
/**
 * Branch-tag wire encoding (groups, M3 slices T1+T2). The topology upload's
 * slotIds carry the slot id in the low byte and a BRANCH TAG in the three
 * bits above it: tag 0 is the trunk. A group is opened by a MARKER SLOT —
 * a utility unit placed in the chain like a device — whose tag field carries
 * the branch/band count N; the members that follow carry tags 1..N, monotone
 * non-decreasing with skips allowed (an empty branch is representable). A
 * trunk device, the next marker, or the chain's end closes the group. The
 * engine validates and never coerces. Mirrors EffectsRack.cmajor's
 * laneEncodeSlotWithBranchTag exactly; the bit layout is pinned by test on
 * both sides of the wire.
 */
export const LANE_BRANCH_TAG_SHIFT = 8;
export const LANE_BRANCH_TAG_BITS = 3;
export const LANE_MAX_BRANCHES_PER_GROUP = 4;
export const LANE_MAX_BANDS_PER_SPLIT = 3;
/**
 * Marker slot ids sit above the device pool: four parallel units, then four
 * split units (engine laneParallelSlotBase / laneSplitSlotBase). The CHAIN
 * slot domain — what a topology may reference and what param records may
 * address — is therefore wider than the device pool. A split marker owns a
 * param record: values[0]/values[1] are its Linkwitz-Riley crossover
 * frequencies (LR4, 24 dB/oct, minimum phase, zero latency), band tag 1 = low.
 */
export const LANE_DEVICE_SLOT_COUNT = LANE_SLOT_ORDINAL_COUNT * LANE_SLOT_TYPE_COUNT;
export const LANE_PARALLEL_UNIT_COUNT = 4;
export const LANE_SPLIT_UNIT_COUNT = 4;
export const LANE_PARALLEL_SLOT_BASE = LANE_DEVICE_SLOT_COUNT;
export const LANE_SPLIT_SLOT_BASE = LANE_DEVICE_SLOT_COUNT + LANE_PARALLEL_UNIT_COUNT;
export const LANE_CHAIN_SLOT_COUNT = LANE_DEVICE_SLOT_COUNT + LANE_PARALLEL_UNIT_COUNT + LANE_SPLIT_UNIT_COUNT;
export const LANE_SPLIT_PARAM_XOVER_LOW_HZ = 0;
export const LANE_SPLIT_PARAM_XOVER_HIGH_HZ = 1;
export const LANE_SPLIT_PARAM_XOVER_LOW_KEY_TRACK_ENABLED = 2;
export const LANE_SPLIT_PARAM_XOVER_LOW_KEY_TRACK_OFFSET_SEMITONES = 3;
export const LANE_SPLIT_PARAM_XOVER_HIGH_KEY_TRACK_ENABLED = 4;
export const LANE_SPLIT_PARAM_XOVER_HIGH_KEY_TRACK_OFFSET_SEMITONES = 5;
/** True for any group-marker slot id (parallel or split), bounds included. */
export function isLaneGroupMarkerSlot(slotId) {
    return slotId >= LANE_DEVICE_SLOT_COUNT && slotId < LANE_CHAIN_SLOT_COUNT;
}
/** True for a split-marker slot id, bounds included. */
export function isLaneSplitMarkerSlot(slotId) {
    return slotId >= LANE_SPLIT_SLOT_BASE && slotId < LANE_CHAIN_SLOT_COUNT;
}
/** Encode one placed device's wire entry. Tag 0 = a trunk (serial) device. */
export function encodeLaneSlotWithBranchTag(slotId, branchTag) {
    if (!Number.isInteger(branchTag) || branchTag < 0 || branchTag > LANE_MAX_BRANCHES_PER_GROUP) {
        throw new Error(`Invalid lane branch tag: ${String(branchTag)}`);
    }
    return slotId | (branchTag << LANE_BRANCH_TAG_SHIFT);
}
export function decodeLaneSlotId(encoded) {
    return encoded & ((1 << LANE_BRANCH_TAG_SHIFT) - 1);
}
export function decodeLaneBranchTag(encoded) {
    return (encoded >> LANE_BRANCH_TAG_SHIFT) & ((1 << LANE_BRANCH_TAG_BITS) - 1);
}
/** Stable effect identity order and wire-id vocabulary. */
export const RACK_EFFECT_ORDER = Object.freeze([
    "filter",
    "drive",
    "ott",
    "chorus",
    "flanger",
    "phaser",
    "delay",
    "reverb",
]);
/** UI effect ids to wire device types (one type per id, by construction). */
export const EFFECT_ID_TO_LANE_TYPE = Object.freeze({
    filter: "globalFilter",
    drive: "distortion",
    ott: "ott",
    chorus: "chorus",
    flanger: "flanger",
    phaser: "phaser",
    delay: "delay",
    reverb: "reverb",
});
/** The inverse map, for surfaces that speak device types (the subway map,
    the bridge adapter's host lists). */
export const LANE_TYPE_TO_EFFECT_ID = new Map(Object.entries(EFFECT_ID_TO_LANE_TYPE)
    .map(([effectId, deviceType]) => [deviceType, effectId]));
const EFFECT_ID_TO_WIRE_ID = Object.freeze({
    filter: 0,
    drive: 1,
    ott: 2,
    chorus: 3,
    flanger: 4,
    phaser: 5,
    delay: 6,
    reverb: 7,
});
const WIRE_ID_TO_EFFECT_ID = new Map(RACK_EFFECT_ORDER.map((effectId) => [EFFECT_ID_TO_WIRE_ID[effectId], effectId]));
function defaultEnabled() {
    return {
        filter: false,
        drive: false,
        ott: false,
        chorus: false,
        flanger: false,
        phaser: false,
        delay: false,
        reverb: false,
    };
}
function defaultParams(effectId) {
    return Object.fromEntries(getRackEffectDescriptor(effectId).parameters
        .map((descriptor) => [descriptor.endpointID, descriptor.initial]));
}
/**
 * The patch's live lane devices in STABLE IDENTITY ORDER — the order the
 * dynamic target domain (pickers, table categories) lists devices in, which
 * deliberately never follows the chain order: reordering the chain must not
 * reshuffle pickers. A v1 document pins exactly one instance-#1 device per
 * type; the device-instance tree arrives with the add/remove UX, and only
 * this function changes when it does.
 */
export function listLaneDeviceInstances(state) {
    void state;
    return RACK_EFFECT_ORDER.map((effectId) => {
        const deviceType = EFFECT_ID_TO_LANE_TYPE[effectId];
        return { instanceId: `${deviceType}#1`, deviceType };
    });
}
/** Create the lane state matching the deployed pre-lane sound. */
export function createDefaultLaneState() {
    return {
        format: "cosimo.lane",
        version: 1,
        order: [...RACK_EFFECT_ORDER],
        enabled: defaultEnabled(),
        params: Object.fromEntries(RACK_EFFECT_ORDER.map((effectId) => [effectId, defaultParams(effectId)])),
    };
}
function parseJsonDocument(input) {
    if (typeof input !== "string") {
        return { _tag: "json", value: input };
    }
    if (input.trim().length === 0) {
        return { _tag: "err", message: `${LANE_STATE_KEY} must not be empty` };
    }
    try {
        const value = JSON.parse(input);
        return { _tag: "json", value };
    }
    catch (cause) {
        const detail = cause instanceof Error ? cause.message : String(cause);
        return { _tag: "err", message: `${LANE_STATE_KEY} is not valid JSON: ${detail}` };
    }
}
function isRecord(value) {
    return typeof value === "object" && value !== null && !Array.isArray(value);
}
function parseEffectId(input) {
    if (typeof input !== "string") {
        return null;
    }
    return RACK_EFFECT_ORDER.find((candidate) => candidate === input) ?? null;
}
/** Parse unknown persisted data into the complete clean lane schema. */
export function parseLaneState(input) {
    const document = parseJsonDocument(input);
    if (document._tag === "err") {
        return document;
    }
    if (!isRecord(document.value)) {
        return { _tag: "err", message: `${LANE_STATE_KEY} must be an object` };
    }
    const allowedKeys = new Set(["format", "version", "order", "enabled", "params"]);
    for (const key of Reflect.ownKeys(document.value)) {
        if (typeof key !== "string" || !allowedKeys.has(key)) {
            return { _tag: "err", message: `${LANE_STATE_KEY} has unexpected field ${String(key)}` };
        }
    }
    if (document.value.format !== "cosimo.lane" || document.value.version !== 1) {
        return { _tag: "err", message: `${LANE_STATE_KEY} must be cosimo.lane version 1` };
    }
    if (!Array.isArray(document.value.order) || document.value.order.length !== RACK_EFFECT_ORDER.length) {
        return { _tag: "err", message: `${LANE_STATE_KEY}.order must contain every effect once` };
    }
    const order = [];
    const seen = new Set();
    for (const rawEffectId of document.value.order) {
        const effectId = parseEffectId(rawEffectId);
        if (effectId === null || seen.has(effectId)) {
            return { _tag: "err", message: `${LANE_STATE_KEY}.order is not a complete permutation` };
        }
        seen.add(effectId);
        order.push(effectId);
    }
    if (!isRecord(document.value.enabled)) {
        return { _tag: "err", message: `${LANE_STATE_KEY}.enabled must be an object` };
    }
    if (Reflect.ownKeys(document.value.enabled).length !== RACK_EFFECT_ORDER.length) {
        return { _tag: "err", message: `${LANE_STATE_KEY}.enabled must contain every effect once` };
    }
    const enabled = defaultEnabled();
    for (const effectId of RACK_EFFECT_ORDER) {
        const rawEnabled = document.value.enabled[effectId];
        if (typeof rawEnabled !== "boolean") {
            return { _tag: "err", message: `${LANE_STATE_KEY}.enabled.${effectId} must be boolean` };
        }
        enabled[effectId] = rawEnabled;
    }
    if (!isRecord(document.value.params)) {
        return { _tag: "err", message: `${LANE_STATE_KEY}.params must be an object` };
    }
    if (Reflect.ownKeys(document.value.params).length !== RACK_EFFECT_ORDER.length) {
        return { _tag: "err", message: `${LANE_STATE_KEY}.params must contain every effect once` };
    }
    const params = {};
    for (const effectId of RACK_EFFECT_ORDER) {
        const rawDeviceParams = document.value.params[effectId];
        if (!isRecord(rawDeviceParams)) {
            return { _tag: "err", message: `${LANE_STATE_KEY}.params.${effectId} must be an object` };
        }
        const descriptors = getRackEffectDescriptor(effectId).parameters;
        const currentEndpoints = descriptors.map((descriptor) => descriptor.endpointID);
        const legacyEndpoints = LEGACY_LANE_DEVICE_PARAM_ENDPOINTS[EFFECT_ID_TO_LANE_TYPE[effectId]];
        const rawKeys = Reflect.ownKeys(rawDeviceParams);
        const hasExactShape = (expected) => rawKeys.length === expected.length
            && rawKeys.every((key) => typeof key === "string" && expected.includes(key));
        if (!hasExactShape(currentEndpoints) && !hasExactShape(legacyEndpoints)) {
            return { _tag: "err", message: `${LANE_STATE_KEY}.params.${effectId} must contain every parameter once` };
        }
        const deviceParams = {};
        for (const endpointID of rawKeys) {
            if (typeof endpointID !== "string") {
                return { _tag: "err", message: `${LANE_STATE_KEY}.params.${effectId} has an invalid parameter key` };
            }
            const rawValue = rawDeviceParams[endpointID];
            if (typeof rawValue !== "number" || !Number.isFinite(rawValue)) {
                return { _tag: "err", message: `${LANE_STATE_KEY}.params.${effectId}.${endpointID} must be a finite number` };
            }
            deviceParams[endpointID] = rawValue;
        }
        params[effectId] = deviceParams;
    }
    return {
        _tag: "ok",
        value: { format: "cosimo.lane", version: 1, order, enabled, params },
    };
}
/** Deserialize persisted state, using the clean default for missing/corrupt local data. */
export function deserializeLaneState(input) {
    if (input === undefined) {
        return createDefaultLaneState();
    }
    const parsed = parseLaneState(input);
    return parsed._tag === "ok" ? parsed.value : createDefaultLaneState();
}
/** Serialize the complete canonical lane document. */
export function serializeLaneState(state) {
    return JSON.stringify({
        format: "cosimo.lane",
        version: 1,
        order: state.order,
        enabled: state.enabled,
        params: state.params,
    });
}
/**
 * Build the complete runtime replay for one lane document: every device's
 * positional parameter record, then the one structure event. Records go
 * FIRST so a device entering the committed chain snaps onto its record
 * rather than a zeroed default.
 */
export function buildLaneRuntimeEvents(state) {
    const events = [];
    let deliverySerial = 0;
    for (const effectId of RACK_EFFECT_ORDER) {
        deliverySerial += 1;
        const deviceType = EFFECT_ID_TO_LANE_TYPE[effectId];
        events.push({
            endpointID: LANE_SLOT_PARAMS_ENDPOINT_ID,
            value: {
                slotId: getLaneSlotId(deviceType, 0),
                deliverySerial,
                values: buildLaneSlotParamValues(deviceType, state.params[effectId]),
            },
        });
    }
    const slotIds = new Array(LANE_MAX_CHAIN_LENGTH).fill(0);
    let enabledMask = 0;
    state.order.forEach((effectId, position) => {
        slotIds[position] = EFFECT_ID_TO_WIRE_ID[effectId];
        if (state.enabled[effectId]) {
            enabledMask |= 1 << position;
        }
    });
    events.push({
        endpointID: LANE_TOPOLOGY_ENDPOINT_ID,
        value: { chainLength: state.order.length, slotIds, enabledMask },
    });
    return events;
}
/** Send a complete lane document as one logical commit before the next audio frame. */
export function commitLaneState(connection, state) {
    for (const event of buildLaneRuntimeEvents(state)) {
        connection.sendEventOrValue?.(event.endpointID, event.value);
    }
}
/**
 * Send one live-edited parameter field. The document write is the caller's
 * job (typically on gesture end); this is the low-latency audible path.
 */
export function sendLaneParamValue(connection, effectId, endpointID, value, deliverySerial) {
    const deviceType = EFFECT_ID_TO_LANE_TYPE[effectId];
    const paramIndex = getLaneSlotParamIndex(deviceType, endpointID);
    if (paramIndex === null) {
        throw new Error(`Unknown lane parameter: ${effectId}.${endpointID}`);
    }
    connection.sendEventOrValue?.(LANE_SLOT_PARAM_VALUE_ENDPOINT_ID, {
        slotId: getLaneSlotId(deviceType, 0),
        paramIndex,
        deliverySerial,
        value,
    });
}
function decodeOrder(code) {
    const order = [];
    const seen = new Set();
    for (let position = 0; position < RACK_EFFECT_ORDER.length; position += 1) {
        const wireId = (code >>> (position * 3)) & 0b111;
        const effectId = WIRE_ID_TO_EFFECT_ID.get(wireId);
        if (effectId === undefined || seen.has(effectId)) {
            return null;
        }
        seen.add(effectId);
        order.push(effectId);
    }
    return order;
}
/**
 * Parse DSP effective-state readback into stable effect identities.
 *
 * Null when the committed chain is not a lane.v1 structure: before the
 * adapter's first commit the engine runs the default EMPTY chain (the
 * deployed pre-lane sound), which this eight-device document cannot
 * represent.
 */
export function parseEffectiveLaneState(input) {
    if (!isRecord(input)) {
        return null;
    }
    const chainLength = Number(input.laneCommittedChainLength);
    const chainCode = Number(input.laneCommittedChainCode);
    const positionMask = Number(input.laneCommittedPositionMask);
    const generation = Number(input.laneCommittedGeneration);
    const rejectedUploadCount = Number(input.laneRejectedUploadCount);
    const paramsAcknowledgedSerial = Number(input.laneParamsAcknowledgedSerial);
    if (![chainLength, chainCode, positionMask, generation, rejectedUploadCount, paramsAcknowledgedSerial]
        .every(Number.isFinite)) {
        return null;
    }
    if (Math.trunc(chainLength) !== RACK_EFFECT_ORDER.length) {
        return null;
    }
    const order = decodeOrder(Math.trunc(chainCode));
    if (order === null) {
        return null;
    }
    const enabled = defaultEnabled();
    order.forEach((effectId, position) => {
        enabled[effectId] = ((Math.trunc(positionMask) >>> position) & 1) === 1;
    });
    return {
        generation: Math.trunc(generation),
        order,
        enabled,
        rejectedUploadCount: Math.trunc(rejectedUploadCount),
        paramsAcknowledgedSerial: Math.trunc(paramsAcknowledgedSerial),
    };
}
