// Generated from ui/shared/lane-state.ts by node ui/build.mjs. Do not edit this file directly.
import { LANE_SLOT_ORDINAL_COUNT, LANE_SLOT_TYPE_COUNT } from "./lane-slot-params.js";
/**
 * Stored-state key of the Effects Lane document (lane-state-v2.ts). The document
 * is the one durable owner of the chain, the device enables and every device
 * parameter value, because effect parameters have no host endpoints.
 */
export const LANE_STATE_KEY = "lane.v1";
/** DSP endpoint receiving the complete lane structure: chain + enable mask. */
export const LANE_TOPOLOGY_ENDPOINT_ID = "laneTopology";
/** DSP endpoint receiving the transient per-group branch Solo overlay. */
export const LANE_SOLO_ENDPOINT_ID = "laneSolo";
/** DSP endpoint receiving one device's complete positional parameter record. */
export const LANE_SLOT_PARAMS_ENDPOINT_ID = "laneSlotParams";
/** DSP endpoint receiving one live-edited parameter field. */
export const LANE_SLOT_PARAM_VALUE_ENDPOINT_ID = "laneSlotParamValue";
/** DSP endpoint receiving the whole-lane Mix and Bypass state. */
export const LANE_OUTPUT_CONTROL_ENDPOINT_ID = "laneOutputControl";
/** Wire capacity of one lane chain (engine maxLaneChainLength). */
export const LANE_MAX_CHAIN_LENGTH = 16;
/**
 * Branch-tag wire encoding for groups. The topology upload's
 * slotIds carry the slot id in the low byte and a BRANCH TAG in the three
 * bits above it: tag 0 is the trunk. A group is opened by a MARKER SLOT —
 * a utility unit placed in the chain like a device — whose tag field carries
 * the branch/band count N; the members that follow carry tags 1..N, monotone
 * non-decreasing with skips allowed (an empty branch is representable). A
 * trunk device, the next marker, or the chain's end closes the group. The
 * engine validates and never coerces. Mirrors EffectsRack.cmajor's
 * laneEncodeSlotWithBranchTag exactly; the bit layout is pinned by test on
 * both sides of the wire.
 */
export const LANE_BRANCH_TAG_SHIFT = 8;
export const LANE_BRANCH_TAG_BITS = 3;
export const LANE_MAX_BRANCHES_PER_GROUP = 4;
export const LANE_MAX_BANDS_PER_SPLIT = 3;
/**
 * Marker slot ids sit above the device pool: four parallel units, then four
 * split units (engine laneParallelSlotBase / laneSplitSlotBase). The CHAIN
 * slot domain — what a topology may reference and what param records may
 * address — is therefore wider than the device pool. A split marker owns a
 * param record: values[0]/values[1] are its Linkwitz-Riley crossover
 * frequencies (LR4, 24 dB/oct, minimum phase, zero latency), band tag 1 = low.
 */
export const LANE_DEVICE_SLOT_COUNT = LANE_SLOT_ORDINAL_COUNT * LANE_SLOT_TYPE_COUNT;
export const LANE_PARALLEL_UNIT_COUNT = 4;
export const LANE_SPLIT_UNIT_COUNT = 4;
export const LANE_PARALLEL_SLOT_BASE = LANE_DEVICE_SLOT_COUNT;
export const LANE_SPLIT_SLOT_BASE = LANE_DEVICE_SLOT_COUNT + LANE_PARALLEL_UNIT_COUNT;
export const LANE_CHAIN_SLOT_COUNT = LANE_DEVICE_SLOT_COUNT + LANE_PARALLEL_UNIT_COUNT + LANE_SPLIT_UNIT_COUNT;
export const LANE_SPLIT_PARAM_XOVER_LOW_HZ = 0;
export const LANE_SPLIT_PARAM_XOVER_HIGH_HZ = 1;
export const LANE_SPLIT_PARAM_XOVER_LOW_KEY_TRACK_ENABLED = 2;
export const LANE_SPLIT_PARAM_XOVER_LOW_KEY_TRACK_OFFSET_SEMITONES = 3;
export const LANE_SPLIT_PARAM_XOVER_HIGH_KEY_TRACK_ENABLED = 4;
export const LANE_SPLIT_PARAM_XOVER_HIGH_KEY_TRACK_OFFSET_SEMITONES = 5;
/** True for any group-marker slot id (parallel or split), bounds included. */
export function isLaneGroupMarkerSlot(slotId) {
    return slotId >= LANE_DEVICE_SLOT_COUNT && slotId < LANE_CHAIN_SLOT_COUNT;
}
/** True for a split-marker slot id, bounds included. */
export function isLaneSplitMarkerSlot(slotId) {
    return slotId >= LANE_SPLIT_SLOT_BASE && slotId < LANE_CHAIN_SLOT_COUNT;
}
/** Encode one placed device's wire entry. Tag 0 = a trunk (serial) device. */
export function encodeLaneSlotWithBranchTag(slotId, branchTag) {
    if (!Number.isInteger(branchTag) || branchTag < 0 || branchTag > LANE_MAX_BRANCHES_PER_GROUP) {
        throw new Error(`Invalid lane branch tag: ${String(branchTag)}`);
    }
    return slotId | (branchTag << LANE_BRANCH_TAG_SHIFT);
}
export function decodeLaneSlotId(encoded) {
    return encoded & ((1 << LANE_BRANCH_TAG_SHIFT) - 1);
}
export function decodeLaneBranchTag(encoded) {
    return (encoded >> LANE_BRANCH_TAG_SHIFT) & ((1 << LANE_BRANCH_TAG_BITS) - 1);
}
/** Stable effect identity order. */
export const RACK_EFFECT_ORDER = Object.freeze([
    "filter",
    "drive",
    "ott",
    "chorus",
    "flanger",
    "phaser",
    "delay",
    "reverb",
]);
/** UI effect ids to wire device types (one type per id, by construction). */
export const EFFECT_ID_TO_LANE_TYPE = Object.freeze({
    filter: "globalFilter",
    drive: "distortion",
    ott: "ott",
    chorus: "chorus",
    flanger: "flanger",
    phaser: "phaser",
    delay: "delay",
    reverb: "reverb",
});
/** The inverse map, for surfaces that speak device types (the subway map,
    the bridge adapter's host lists). */
export const LANE_TYPE_TO_EFFECT_ID = new Map(Object.entries(EFFECT_ID_TO_LANE_TYPE)
    .map(([effectId, deviceType]) => [deviceType, effectId]));
