// Generated from ui/shared/modulation.ts by node ui/build.mjs. Do not edit this file directly.
// ui/shared/modulation.ts
import {
  getLaneDeviceModulationTargetKinds,
  laneMirrorRackKind,
  parseLaneModulationTargetKind
} from "./lane-modulation-targets.js";
import {
  allRackParameterDescriptors
} from "./rack-parameter-descriptors.js";
import {
  MSEG_RATE_MAX_SECONDS,
  createDefaultMsegPlayback,
  createDefaultMsegShape as createDefaultMsegShape2,
  msegShapesEqual,
  normalizeMsegPlayback,
  normalizeMsegShape as normalizeMsegShape2
} from "./mseg.js";

// kit/ui/mseg.ts
var MSEG_BODY_SAMPLES = 2048;
var MSEG_PADDED_SAMPLES = MSEG_BODY_SAMPLES + 3;
var MSEG_CURVE_POWER_LIMIT = 20;
var MSEG_DEFAULT_NAME = "MSEG 1";
function objectFields(value) {
  return value !== null && typeof value === "object" ? value : {};
}
function clamp(value, min, max) {
  return Math.min(Math.max(value, min), max);
}
function almostEqual(left, right, epsilon = 1e-12) {
  return Math.abs(left - right) <= epsilon;
}
function clampCurvePower(value) {
  return clamp(Number.isFinite(value) ? value : 0, -MSEG_CURVE_POWER_LIMIT, MSEG_CURVE_POWER_LIMIT);
}
function clamp01(value) {
  return clamp(Number.isFinite(value) ? value : 0, 0, 1);
}
function createDefaultMsegShape(name = MSEG_DEFAULT_NAME) {
  return {
    format: "mseg.shape",
    version: 1,
    name,
    globalSmooth: false,
    points: [
      { x: 0, y: 0, curvePower: 0 },
      { x: 1, y: 1, curvePower: 0 }
    ]
  };
}
function normalizePoint(point, pointIndex, pointCount) {
  const nextPoint = objectFields(point);
  let x = Number(nextPoint.x);
  if (!Number.isFinite(x)) {
    x = pointIndex === 0 ? 0 : pointIndex === pointCount - 1 ? 1 : 0;
  }
  if (pointIndex !== 0 && pointIndex !== pointCount - 1) {
    x = clamp01(x);
  }
  return {
    x,
    y: clamp01(Number(nextPoint.y)),
    curvePower: clampCurvePower(Number(nextPoint.curvePower))
  };
}
function normalizeMsegShape(shape = createDefaultMsegShape()) {
  const next = objectFields(shape);
  const inputPoints = Array.isArray(next.points) ? next.points : [];
  if (inputPoints.length < 2) {
    throw new Error("MSEG shapes require at least two points");
  }
  const points = inputPoints.map((point, index) => normalizePoint(point, index, inputPoints.length));
  if (!almostEqual(points[0].x, 0) || !almostEqual(points[points.length - 1].x, 1)) {
    throw new Error("MSEG shapes must start at x = 0 and end at x = 1");
  }
  for (let index = 1; index < points.length; index += 1) {
    if (points[index].x < points[index - 1].x) {
      throw new Error("MSEG shape points must stay in non-decreasing x order");
    }
  }
  return {
    format: "mseg.shape",
    version: 1,
    name: typeof next.name === "string" && next.name.trim() ? next.name : MSEG_DEFAULT_NAME,
    globalSmooth: Boolean(next.globalSmooth),
    points
  };
}
function powerScale(value, power) {
  if (Math.abs(power) < 0.01) {
    return value;
  }
  const numerator = Math.exp(power * value) - 1;
  const denominator = Math.exp(power) - 1;
  return numerator / denominator;
}
function findEvaluationSegment(points, x) {
  if (x <= points[0].x) {
    return { from: points[0], to: points[0], laterPointWins: false };
  }
  for (let index = 0; index < points.length - 1; index += 1) {
    const from = points[index];
    const to = points[index + 1];
    if (x < to.x) {
      return { from, to, laterPointWins: false };
    }
    if (almostEqual(x, to.x)) {
      let latestIndex = index + 1;
      while (latestIndex + 1 < points.length && almostEqual(points[latestIndex + 1].x, x)) {
        latestIndex += 1;
      }
      return {
        from: points[latestIndex],
        to: points[latestIndex],
        laterPointWins: true
      };
    }
  }
  return {
    from: points[points.length - 1],
    to: points[points.length - 1],
    laterPointWins: false
  };
}
function evaluateNormalizedMsegShape(points, x) {
  const clampedX = clamp01(Number(x));
  const segment = findEvaluationSegment(points, clampedX);
  if (segment.laterPointWins || almostEqual(segment.from.x, segment.to.x)) {
    return segment.to.y;
  }
  const width = segment.to.x - segment.from.x;
  const t = width <= 0 ? 1 : (clampedX - segment.from.x) / width;
  const curvedT = clamp01(powerScale(t, segment.from.curvePower));
  return segment.from.y + (segment.to.y - segment.from.y) * curvedT;
}
function evaluateMsegShape(shape, x) {
  return evaluateNormalizedMsegShape(normalizeMsegShape(shape).points, x);
}
function renderMsegShape(shape) {
  const padded = new Float32Array(MSEG_PADDED_SAMPLES);
  renderMsegShapeInto(shape, padded);
  return padded;
}
function renderMsegShapeInto(shape, padded) {
  if (padded.length !== MSEG_PADDED_SAMPLES) throw new Error("Invalid MSEG destination length.");
  const normalizedShape = normalizeMsegShape(shape);
  for (let sampleIndex = 0; sampleIndex < MSEG_BODY_SAMPLES; sampleIndex += 1) {
    const x = sampleIndex / (MSEG_BODY_SAMPLES - 1);
    padded[sampleIndex + 1] = evaluateMsegShape(normalizedShape, x);
  }
  padded[0] = padded[1];
  padded[MSEG_BODY_SAMPLES + 1] = padded[MSEG_BODY_SAMPLES];
  padded[MSEG_BODY_SAMPLES + 2] = padded[MSEG_BODY_SAMPLES];
}

// ui/shared/modulation.ts
import {
  MODULATION_SOURCE_IDENTITIES,
  MODULATION_TARGET_IDENTITIES,
  getVoiceModulationParameterKind,
  parseModulationTargetKind as parseCanonicalModulationTargetKind,
  parseRackModulationTargetKind,
  laneBaseKindForRackEndpoint
} from "./modulation-targets.js";
import { buildModulationRuntimeProgramEvents } from "./modulation-runtime-program.js";
import { err, ok } from "./result.js";
import { getModulationTargetDisplayLabel } from "./target-descriptor.js";
import {
  GLOBAL_TUNE_MODULATION_MAX_SEMITONES,
  GLOBAL_TUNE_MODULATION_MIN_SEMITONES,
  formatSemitonesAndCents
} from "./global-tune.js";
var MODULATION_STATE_KEY = "modulation.v6";
var MODULATION_STATE_VERSION = 6;
var MODULATION_MSEG_SLOT_COUNT = 3;
var MODULATION_ENV_SLOT_COUNT = 3;
var AMP_ENVELOPE_SOURCE_SLOT = 4;
var MODULATION_MSEG_BUFFER_ENDPOINT_ID = "modulationMsegBuffer";
var MODULATION_MSEG_PLAYBACK_ENDPOINT_ID = "modulationMsegPlayback";
var MODULATION_MACRO_SLOT_COUNT = 4;
var MSEG_SLOT_NAMES = ["MSEG 1", "MSEG 2", "MSEG 3"];
var MACRO_SLOT_NAMES = ["Macro 1", "Macro 2", "Macro 3", "Macro 4"];
var ENV_SLOT_NAMES = ["Env 1", "Env 2", "Env 3"];
var ENV_MIN_SECONDS = 1e-3;
var ENV_MAX_SECONDS = 10;
var FILTER_Q_MIN = 0.1;
var FILTER_Q_MAX = 20;
var VOICE_ENHANCER_Q_SPAN = 10 - 0.1;
var ROUTE_AMOUNT_LIMITS = {
  wavetablePosition: { min: -1, max: 1 },
  warpAmount: { min: -1, max: 1 },
  filterCutoffOctaves: { min: -6, max: 6 },
  filterQ: { min: -(FILTER_Q_MAX - FILTER_Q_MIN), max: FILTER_Q_MAX - FILTER_Q_MIN },
  filterMix: { min: -1, max: 1 },
  pitchSemitones: { min: -48, max: 48 },
  globalTuneSemitones: {
    min: GLOBAL_TUNE_MODULATION_MIN_SEMITONES,
    max: GLOBAL_TUNE_MODULATION_MAX_SEMITONES
  },
  // Additive dB offset over the full parameter span; the engine clamps base + offset.
  ampGainDb: { min: -54, max: 54 },
  pan: { min: -1, max: 1 },
  unisonDetune: { min: -1, max: 1 },
  unisonBlend: { min: -1, max: 1 },
  unisonWidth: { min: -1, max: 1 },
  unisonWavetablePositionSpread: { min: -1, max: 1 },
  unisonWarpSpread: { min: -1, max: 1 },
  mseg1Morph: { min: -1, max: 1 },
  mseg2Morph: { min: -1, max: 1 },
  mseg3Morph: { min: -1, max: 1 },
  mseg1Rate: { min: -MSEG_RATE_MAX_SECONDS, max: MSEG_RATE_MAX_SECONDS },
  mseg2Rate: { min: -MSEG_RATE_MAX_SECONDS, max: MSEG_RATE_MAX_SECONDS },
  mseg3Rate: { min: -MSEG_RATE_MAX_SECONDS, max: MSEG_RATE_MAX_SECONDS },
  env1Attack: { min: -ENV_MAX_SECONDS, max: ENV_MAX_SECONDS },
  env1Decay: { min: -ENV_MAX_SECONDS, max: ENV_MAX_SECONDS },
  env1Sustain: { min: -1, max: 1 },
  env1Release: { min: -ENV_MAX_SECONDS, max: ENV_MAX_SECONDS },
  env2Attack: { min: -ENV_MAX_SECONDS, max: ENV_MAX_SECONDS },
  env2Decay: { min: -ENV_MAX_SECONDS, max: ENV_MAX_SECONDS },
  env2Sustain: { min: -1, max: 1 },
  env2Release: { min: -ENV_MAX_SECONDS, max: ENV_MAX_SECONDS },
  env3Attack: { min: -ENV_MAX_SECONDS, max: ENV_MAX_SECONDS },
  env3Decay: { min: -ENV_MAX_SECONDS, max: ENV_MAX_SECONDS },
  env3Sustain: { min: -1, max: 1 },
  env3Release: { min: -ENV_MAX_SECONDS, max: ENV_MAX_SECONDS },
  ampAttack: { min: -ENV_MAX_SECONDS, max: ENV_MAX_SECONDS },
  ampDecay: { min: -ENV_MAX_SECONDS, max: ENV_MAX_SECONDS },
  ampSustain: { min: -1, max: 1 },
  ampRelease: { min: -ENV_MAX_SECONDS, max: ENV_MAX_SECONDS },
  voiceEnhancerFrequencyOctaves: { min: -6, max: 6 },
  voiceEnhancerQ: { min: -VOICE_ENHANCER_Q_SPAN, max: VOICE_ENHANCER_Q_SPAN },
  voiceEnhancerAmount: { min: -1, max: 1 }
};
var ROUTE_AMOUNT_STEPS = {
  wavetablePosition: 1e-3,
  warpAmount: 1e-3,
  filterCutoffOctaves: 1e-3,
  filterQ: 1e-3,
  filterMix: 1e-3,
  pitchSemitones: 0.01,
  globalTuneSemitones: 0.01,
  ampGainDb: 0.1,
  pan: 1e-3,
  unisonDetune: 1e-3,
  unisonBlend: 1e-3,
  unisonWidth: 1e-3,
  unisonWavetablePositionSpread: 1e-3,
  unisonWarpSpread: 1e-3,
  mseg1Morph: 1e-3,
  mseg2Morph: 1e-3,
  mseg3Morph: 1e-3,
  mseg1Rate: 1e-3,
  mseg2Rate: 1e-3,
  mseg3Rate: 1e-3,
  env1Attack: 1e-3,
  env1Decay: 1e-3,
  env1Sustain: 1e-3,
  env1Release: 1e-3,
  env2Attack: 1e-3,
  env2Decay: 1e-3,
  env2Sustain: 1e-3,
  env2Release: 1e-3,
  env3Attack: 1e-3,
  env3Decay: 1e-3,
  env3Sustain: 1e-3,
  env3Release: 1e-3,
  ampAttack: 1e-3,
  ampDecay: 1e-3,
  ampSustain: 1e-3,
  ampRelease: 1e-3,
  voiceEnhancerFrequencyOctaves: 1e-3,
  voiceEnhancerQ: 1e-3,
  voiceEnhancerAmount: 1e-3
};
var RACK_MODULATION_PARAMETERS = allRackParameterDescriptors().filter((parameter) => parameter.modulationTargetIndex !== null);
var RACK_MODULATION_PARAMETER_BY_KIND = new Map(
  RACK_MODULATION_PARAMETERS.map((parameter) => [
    laneBaseKindForRackEndpoint(parameter.endpointID),
    parameter
  ])
);
var ModulationStateParseError = class extends Error {
  name = "ModulationStateParseError";
};
var MODULATION_SOURCE_LABELS = {
  "mseg-1": "MSEG 1",
  "mseg-2": "MSEG 2",
  "mseg-3": "MSEG 3",
  "env-1": "ENV 1",
  "env-2": "ENV 2",
  "env-3": "ENV 3",
  "amp-envelope": "AMP ENV",
  velocity: "VEL",
  pressure: "AT",
  slide: "SLIDE",
  "macro-1": "MACRO 1",
  "macro-2": "MACRO 2",
  "macro-3": "MACRO 3",
  "macro-4": "MACRO 4"
};
var MODULATION_SOURCE_OPTIONS = MODULATION_SOURCE_IDENTITIES.map((identity) => ({
  value: identity.id,
  label: MODULATION_SOURCE_LABELS[identity.id],
  sourceKind: identity.sourceKind,
  sourceSlot: identity.sourceSlot
}));
var MODULATION_TARGET_OPTIONS = MODULATION_TARGET_IDENTITIES.map((identity) => ({
  value: identity.kind,
  label: getModulationTargetDisplayLabel(identity.kind)
}));
var VOICE_TARGET_OPTIONS = MODULATION_TARGET_OPTIONS.filter((option) => !isRackModulationTarget(option.value));
function buildPatchModulationTargetOptions(devices) {
  const laneKinds = devices.flatMap((device) => getLaneDeviceModulationTargetKinds(device));
  const liveKindSet = new Set(laneKinds);
  const liveCanonicalRackOptions = MODULATION_TARGET_OPTIONS.filter((option) => isRackModulationTarget(option.value) && liveKindSet.has(option.value));
  const poolOptions = laneKinds.filter((kind) => parseCanonicalModulationTargetKind(kind) === null).map((kind) => ({
    value: kind,
    label: getModulationTargetDisplayLabel(kind)
  }));
  return [
    ...VOICE_TARGET_OPTIONS,
    ...liveCanonicalRackOptions,
    ...poolOptions
  ];
}
var generatedRouteIdCounter = 1;
function hasOwnValue(record, key) {
  return Object.prototype.hasOwnProperty.call(record, key);
}
function clamp2(value, min, max) {
  return Math.min(Math.max(value, min), max);
}
function clampEnvSeconds(value, fallback) {
  const numeric = Number(value);
  return clamp2(Number.isFinite(numeric) ? numeric : fallback, ENV_MIN_SECONDS, ENV_MAX_SECONDS);
}
function formatMagnitude(value, digits) {
  const numeric = Number.isFinite(value) ? value : 0;
  return Math.abs(numeric).toFixed(digits);
}
function isRackModulationTarget(targetKind) {
  return parseRackModulationTargetKind(targetKind) !== null;
}
function isRackBusModulationTarget(targetKind) {
  return parseLaneModulationTargetKind(targetKind) !== null;
}
function isVoiceModulationSource(sourceKind) {
  return sourceKind !== "macro";
}
function getRackRouteAmountLimit(descriptor) {
  if (descriptor.modulationApplication === "octaves") {
    return { min: -6, max: 6 };
  }
  if (descriptor.modulationApplication === "semitones") {
    return { min: -60, max: 60 };
  }
  const span = descriptor.max - descriptor.min;
  return { min: -span, max: span };
}
function amountAuthorityKind(targetKind) {
  const parsedLane = parseLaneModulationTargetKind(targetKind);
  return parsedLane !== null ? laneMirrorRackKind(parsedLane) : targetKind;
}
function getRouteAmountLimit(rawTargetKind) {
  const targetKind = amountAuthorityKind(rawTargetKind);
  if (parseLaneModulationTargetKind(targetKind)?.deviceType === "frequencySplit") {
    return { min: -4, max: 4 };
  }
  const rackParameter = RACK_MODULATION_PARAMETER_BY_KIND.get(targetKind);
  if (rackParameter !== void 0) {
    return getRackRouteAmountLimit(rackParameter);
  }
  return ROUTE_AMOUNT_LIMITS[getVoiceModulationParameterKind(targetKind)];
}
function getRouteAmountStep(rawTargetKind) {
  const targetKind = amountAuthorityKind(rawTargetKind);
  if (parseLaneModulationTargetKind(targetKind)?.deviceType === "frequencySplit") {
    return 0.01;
  }
  const rackParameter = RACK_MODULATION_PARAMETER_BY_KIND.get(targetKind);
  if (rackParameter !== void 0) {
    return rackParameter.modulationApplication === "octaves" || rackParameter.modulationApplication === "semitones" ? 0.01 : (rackParameter.max - rackParameter.min) / 1e3;
  }
  return ROUTE_AMOUNT_STEPS[getVoiceModulationParameterKind(targetKind)];
}
function getRouteAmountMagnitudeLimit(targetKind) {
  const limits = getRouteAmountLimit(targetKind);
  return Math.max(Math.abs(limits.min), Math.abs(limits.max));
}
function getRouteAmountSideLimit(targetKind, amount) {
  const limits = getRouteAmountLimit(targetKind);
  if (amount < 0) {
    return Math.abs(limits.min);
  }
  if (amount > 0) {
    return Math.abs(limits.max);
  }
  return getRouteAmountMagnitudeLimit(targetKind);
}
function createGeneratedRouteId() {
  const routeId = `mod-route-auto-${generatedRouteIdCounter}`;
  generatedRouteIdCounter += 1;
  return routeId;
}
function createAvailableGeneratedRouteId(routes) {
  const usedRouteIds = new Set(routes.map((route) => route.id));
  let routeId = createGeneratedRouteId();
  while (usedRouteIds.has(routeId)) {
    routeId = createGeneratedRouteId();
  }
  return routeId;
}
function normalizeRouteId(value, routeIndex) {
  if (typeof value === "string" && value.trim()) {
    return value;
  }
  return `mod-route-${routeIndex + 1}`;
}
function normalizePolarity(value) {
  return value === "bipolar" ? "bipolar" : "unipolar";
}
function getModulationAmountBounds(targetKind) {
  const limits = getRouteAmountLimit(targetKind);
  return {
    min: limits.min,
    max: limits.max,
    step: getRouteAmountStep(targetKind)
  };
}
function clampModulationRouteAmount(targetKind, value) {
  const limits = getRouteAmountLimit(targetKind);
  const numeric = Number(value);
  return clamp2(Number.isFinite(numeric) ? numeric : 0, limits.min, limits.max);
}
function getModulationAmountDepth(targetKind, amount) {
  const clampedAmount = clampModulationRouteAmount(targetKind, amount);
  const limit = getRouteAmountSideLimit(targetKind, clampedAmount);
  if (limit <= 0) {
    return 0;
  }
  return clamp2(Math.abs(clampedAmount) / limit, 0, 1);
}
function composeModulationAmount(targetKind, depth) {
  const limits = getRouteAmountLimit(targetKind);
  const clampedDepth = clamp2(Number.isFinite(depth) ? depth : 0, 0, 1);
  if (Math.abs(clampedDepth - 0.5) <= 1e-9) {
    return 0;
  }
  if (clampedDepth <= 0.5) {
    if (Math.abs(limits.min) <= 1e-9) {
      return 0;
    }
    const negativeRatio = 1 - clampedDepth / 0.5;
    return clampModulationRouteAmount(targetKind, limits.min * negativeRatio);
  }
  if (Math.abs(limits.max) <= 1e-9) {
    return 0;
  }
  const positiveRatio = (clampedDepth - 0.5) / 0.5;
  return clampModulationRouteAmount(targetKind, limits.max * positiveRatio);
}
function getModulationAmountSliderPosition(targetKind, amount) {
  const limits = getRouteAmountLimit(targetKind);
  const clampedAmount = clampModulationRouteAmount(targetKind, amount);
  if (Math.abs(clampedAmount) <= 1e-9) {
    return 0.5;
  }
  if (clampedAmount < 0) {
    if (Math.abs(limits.min) <= 1e-9) {
      return 0.5;
    }
    return clamp2(0.5 * (1 - Math.abs(clampedAmount) / Math.abs(limits.min)), 0, 0.5);
  }
  if (Math.abs(limits.max) <= 1e-9) {
    return 0.5;
  }
  return clamp2(0.5 + 0.5 * (clampedAmount / limits.max), 0.5, 1);
}
function formatModulationAmountReadout(rawTargetKind, amount, polarity = "unipolar") {
  const targetKind = amountAuthorityKind(rawTargetKind);
  const clampedAmount = clampModulationRouteAmount(targetKind, amount);
  const prefix = polarity === "bipolar" ? Math.abs(clampedAmount) <= 1e-9 ? "" : "\xB1" : clampedAmount > 0 ? "+" : clampedAmount < 0 ? "-" : "";
  const rackParameter = RACK_MODULATION_PARAMETER_BY_KIND.get(targetKind);
  if (rackParameter !== void 0) {
    if (rackParameter.modulationApplication === "octaves") {
      return `${prefix}${formatMagnitude(clampedAmount, 2)} oct`;
    }
    if (rackParameter.modulationApplication === "semitones") {
      return `${prefix}${formatMagnitude(clampedAmount, 2)} st`;
    }
    if (rackParameter.unit === "" && rackParameter.max - rackParameter.min <= 2) {
      return `${prefix}${formatMagnitude(clampedAmount * 100, 0)}%`;
    }
    const unit = rackParameter.unit === "deg" ? "\xB0" : rackParameter.unit;
    return `${prefix}${formatMagnitude(clampedAmount, Math.abs(clampedAmount) < 10 ? 2 : 1)}${unit ? ` ${unit}` : ""}`;
  }
  if (parseLaneModulationTargetKind(targetKind)?.deviceType === "frequencySplit") {
    return `${prefix}${formatMagnitude(clampedAmount, 2)} oct`;
  }
  switch (getVoiceModulationParameterKind(targetKind)) {
    case "wavetablePosition":
      return `${prefix}${formatMagnitude(clampedAmount * 100, 0)}%`;
    case "warpAmount":
      return `${prefix}${formatMagnitude(clampedAmount * 100, 0)}%`;
    case "unisonDetune":
    case "unisonBlend":
    case "unisonWidth":
    case "unisonWavetablePositionSpread":
    case "unisonWarpSpread":
    case "mseg1Morph":
    case "mseg2Morph":
    case "mseg3Morph":
    case "filterMix":
    case "voiceEnhancerAmount":
    case "env1Sustain":
    case "env2Sustain":
    case "env3Sustain":
    case "ampSustain":
      return `${prefix}${formatMagnitude(clampedAmount * 100, 0)}%`;
    case "mseg1Rate":
    case "mseg2Rate":
    case "mseg3Rate":
    case "env1Attack":
    case "env1Decay":
    case "env1Release":
    case "env2Attack":
    case "env2Decay":
    case "env2Release":
    case "env3Attack":
    case "env3Decay":
    case "env3Release":
    case "ampAttack":
    case "ampDecay":
    case "ampRelease":
      return `${prefix}${formatMagnitude(clampedAmount, 3)} s`;
    case "filterCutoffOctaves":
    case "voiceEnhancerFrequencyOctaves":
      return `${prefix}${formatMagnitude(clampedAmount, 2)} oct`;
    case "filterQ":
    case "voiceEnhancerQ":
      return `${prefix}${formatMagnitude(clampedAmount, 2)} Q`;
    case "pitchSemitones":
      return `${prefix}${formatMagnitude(clampedAmount, 1)} st`;
    case "globalTuneSemitones":
      return `${polarity === "bipolar" && Math.abs(clampedAmount) > 1e-9 ? "\xB1" : prefix}${formatSemitonesAndCents(clampedAmount, false)}`;
    case "ampGainDb":
      return `${prefix}${formatMagnitude(clampedAmount, 1)} dB`;
    case "pan": {
      const panPercent = Math.round(Math.abs(clampedAmount) * 100);
      if (panPercent === 0) {
        return "0%";
      }
      if (polarity === "bipolar") {
        return `\xB1${panPercent}%`;
      }
      return `${panPercent}% ${clampedAmount < 0 ? "L" : "R"}`;
    }
    default:
      return `${prefix}${formatMagnitude(clampedAmount, 3)}`;
  }
}
function getModulationAmountPercentLabel(targetKind, amount) {
  return `${Math.round(getModulationAmountDepth(targetKind, amount) * 100)}%`;
}
function getModulationTargetClampHint(targetKind) {
  if (isRackModulationTarget(amountAuthorityKind(targetKind))) {
    return "Rack modulation adds to the base control and clamps to the effect's authored range.";
  }
  switch (getVoiceModulationParameterKind(targetKind)) {
    case "wavetablePosition":
      return "Wavetable scan still clamps to the table range.";
    case "warpAmount":
      return "Warp amount still clamps to the oscillator's warp range.";
    case "filterCutoffOctaves":
      return "Requested cutoff movement is converted to Hz and still clamps to the filter range.";
    case "voiceEnhancerFrequencyOctaves":
      return "Enhancer frequency movement remains octave-backed and clamps to its safe bell range.";
    case "filterQ":
      return "Resonance still clamps to the synth's Q range.";
    case "voiceEnhancerQ":
      return "Enhancer Q still clamps to its 0.1-10 range.";
    case "filterMix":
      return "Mix clamps to 0-100%.";
    case "voiceEnhancerAmount":
      return "Enhancer Amount clamps to 0-100%.";
    case "pitchSemitones":
      return "Pitch depth adds on top of note, glide, and bend.";
    case "globalTuneSemitones":
      return "Global Tune depth joins note, glide, bend, and the Global Tune knob before oscillator tuning.";
    case "ampGainDb":
      return "Amplitude still clamps to the synth's gain range.";
    case "pan":
      return "Pan still clamps between full left and full right.";
    case "unisonDetune":
      return "Unison detune still clamps to the oscillator's detune range.";
    case "unisonBlend":
      return "Unison blend still clamps between center-heavy and even spread.";
    case "unisonWidth":
      return "Unison width still clamps between mono and full stereo spread.";
    case "unisonWavetablePositionSpread":
      return "Unison wavetable spread still clamps to the table range.";
    case "unisonWarpSpread":
      return "Unison warp spread still clamps to the oscillator's warp range.";
    case "mseg1Morph":
    case "mseg2Morph":
    case "mseg3Morph":
      return "MSEG morph still clamps between Shape A and Shape B.";
    case "mseg1Rate":
    case "mseg2Rate":
    case "mseg3Rate":
      return "MSEG time still clamps to the source's authored duration range.";
    case "env1Attack":
    case "env1Decay":
    case "env1Release":
    case "env2Attack":
    case "env2Decay":
    case "env2Release":
    case "env3Attack":
    case "env3Decay":
    case "env3Release":
    case "ampAttack":
    case "ampDecay":
    case "ampRelease":
      return "Envelope time still clamps to the envelope stage range.";
    case "env1Sustain":
    case "env2Sustain":
    case "env3Sustain":
    case "ampSustain":
      return "Envelope sustain still clamps between silence and full level.";
    default:
      return "";
  }
}
function parseSourceKind(value) {
  if (value === "mseg" || value === "env" || value === "velocity" || value === "pressure" || value === "slide" || value === "macro") {
    return value;
  }
  return null;
}
function normalizeSourceKind(value) {
  return parseSourceKind(value) ?? "mseg";
}
function parseAnyModulationTargetKind(value) {
  return parseTargetKind(value);
}
function parseTargetKind(value) {
  const canonical = parseCanonicalModulationTargetKind(value);
  if (canonical !== null) {
    return canonical;
  }
  return parseLaneModulationTargetKind(value) !== null ? value : null;
}
function normalizeTargetKind(value) {
  return parseTargetKind(value) ?? "oscA.wavetablePosition";
}
function normalizeMacroName(value, slotIndex) {
  const fallback = MACRO_SLOT_NAMES[slotIndex] ?? `Macro ${slotIndex + 1}`;
  return typeof value === "string" && value.trim() ? value.trim() : fallback;
}
function normalizeSourceSlot(sourceKind, rawSlot) {
  const numericSlot = Math.round(Number(rawSlot));
  if (sourceKind === "velocity" || sourceKind === "pressure" || sourceKind === "slide") {
    return null;
  }
  const maxSlot = sourceKind === "mseg" ? MODULATION_MSEG_SLOT_COUNT : sourceKind === "macro" ? MODULATION_MACRO_SLOT_COUNT : AMP_ENVELOPE_SOURCE_SLOT;
  return clamp2(Number.isFinite(numericSlot) ? numericSlot : 1, 1, maxSlot);
}
function createDefaultEnvelope(slotIndex) {
  return {
    name: ENV_SLOT_NAMES[slotIndex] ?? `Env ${slotIndex + 1}`,
    attackSeconds: 0.01,
    decaySeconds: 0.25,
    sustain: 0.5,
    releaseSeconds: 0.2
  };
}
function normalizeEnvelope(value, slotIndex = 0) {
  const nextValue = value && typeof value === "object" ? value : {};
  const fallback = createDefaultEnvelope(slotIndex);
  return {
    name: typeof nextValue.name === "string" && nextValue.name.trim() ? nextValue.name : fallback.name,
    attackSeconds: clampEnvSeconds(nextValue.attackSeconds ?? fallback.attackSeconds, fallback.attackSeconds),
    decaySeconds: clampEnvSeconds(nextValue.decaySeconds ?? fallback.decaySeconds, fallback.decaySeconds),
    sustain: clamp01(nextValue.sustain ?? fallback.sustain),
    releaseSeconds: clampEnvSeconds(nextValue.releaseSeconds ?? fallback.releaseSeconds, fallback.releaseSeconds)
  };
}
function normalizeEnvelopeSlot(value, slotIndex = 0) {
  const normalized = normalizeEnvelope(value, slotIndex);
  return { name: normalized.name };
}
function createDefaultRoute(overrides = {}) {
  return {
    id: overrides.id ?? createGeneratedRouteId(),
    enabled: true,
    sourceKind: "mseg",
    sourceSlot: 1,
    polarity: "unipolar",
    targetKind: "oscA.wavetablePosition",
    amount: 0,
    reducer: "max",
    ...overrides
  };
}
function normalizeRouteRecord(nextValue, routeIndex, sourceKind, targetKind) {
  const numericAmount = Number(nextValue.amount);
  return {
    id: normalizeRouteId(nextValue.id, routeIndex),
    enabled: nextValue.enabled !== false,
    sourceKind,
    sourceSlot: normalizeSourceSlot(sourceKind, nextValue.sourceSlot),
    polarity: normalizePolarity(nextValue.polarity),
    targetKind,
    amount: clampModulationRouteAmount(targetKind, numericAmount),
    reducer: nextValue.reducer === "mean" ? "mean" : "max"
  };
}
function normalizeRoute(value, routeIndex = 0) {
  const isObject = value !== null && typeof value === "object";
  const nextValue = isObject ? value : {};
  const sourceKind = normalizeSourceKind(nextValue.sourceKind);
  const targetKind = normalizeTargetKind(nextValue.targetKind);
  return normalizeRouteRecord(nextValue, routeIndex, sourceKind, targetKind);
}
function modulationRoutePairKey(route) {
  return `${route.sourceKind}:${route.sourceSlot ?? 0}->${route.targetKind}`;
}
function normalizeRoutes(value) {
  const inputRoutes = Array.isArray(value) ? value : [];
  return inputRoutes.map((route, routeIndex) => normalizeRoute(route, routeIndex));
}
function routesHaveUniqueIdentity(routes) {
  const routeIds = /* @__PURE__ */ new Set();
  const routePairs = /* @__PURE__ */ new Set();
  for (const route of routes) {
    const pairKey = modulationRoutePairKey(route);
    if (routeIds.has(route.id) || routePairs.has(pairKey)) {
      return false;
    }
    routeIds.add(route.id);
    routePairs.add(pairKey);
  }
  return true;
}
function canonicalJsonValuesEqual(left, right) {
  if (left === null || right === null || typeof left !== "object" || typeof right !== "object") {
    return Object.is(left, right);
  }
  if (Array.isArray(left) || Array.isArray(right)) {
    if (!Array.isArray(left) || !Array.isArray(right) || left.length !== right.length) {
      return false;
    }
    return left.every((value, index) => canonicalJsonValuesEqual(value, right[index]));
  }
  const leftRecord = left;
  const rightRecord = right;
  const leftKeys = Object.keys(leftRecord);
  const rightKeys = Object.keys(rightRecord);
  return leftKeys.length === rightKeys.length && leftKeys.every((key) => hasOwnValue(rightRecord, key) && canonicalJsonValuesEqual(leftRecord[key], rightRecord[key]));
}
function createFirstAvailableModulationRoute(routes, targetOptions = MODULATION_TARGET_OPTIONS) {
  const usedPairs = new Set(routes.map(modulationRoutePairKey));
  for (const source of MODULATION_SOURCE_OPTIONS) {
    for (const target of targetOptions) {
      const candidateShape = {
        sourceKind: source.sourceKind,
        sourceSlot: source.sourceSlot,
        targetKind: target.value
      };
      if (usedPairs.has(modulationRoutePairKey(candidateShape))) continue;
      return createDefaultRoute({
        ...candidateShape,
        id: createAvailableGeneratedRouteId(routes)
      });
    }
  }
  return null;
}
function normalizeMsegSlot(value, slotIndex) {
  const nextValue = value && typeof value === "object" ? value : {};
  const defaultShape = createDefaultMsegShape2(MSEG_SLOT_NAMES[slotIndex] ?? `MSEG ${slotIndex + 1}`);
  const shapeA = normalizeMsegShape2(nextValue.shapeA ?? defaultShape);
  const normalizedPlayback = normalizeMsegPlayback({
    ...createDefaultMsegPlayback(),
    ...nextValue.playback ?? {},
    rate: createDefaultMsegPlayback().rate
  });
  const { rate: _parameterOwnedRate, ...playback } = normalizedPlayback;
  return {
    shapeA,
    shapeB: normalizeMsegShape2(nextValue.shapeB ?? shapeA),
    playback
  };
}
function createDefaultModulationState() {
  return {
    format: "cosimo.modulation",
    version: MODULATION_STATE_VERSION,
    msegSlots: Array.from({ length: MODULATION_MSEG_SLOT_COUNT }, (_, slotIndex) => normalizeMsegSlot({}, slotIndex)),
    envelopeSlots: Array.from({ length: MODULATION_ENV_SLOT_COUNT }, (_, slotIndex) => ({
      name: createDefaultEnvelope(slotIndex).name
    })),
    routes: [],
    macroNames: MACRO_SLOT_NAMES.slice()
  };
}
function normalizeModulationState(value = createDefaultModulationState()) {
  const nextValue = value && typeof value === "object" ? value : {};
  const inputMsegSlots = Array.isArray(nextValue.msegSlots) ? nextValue.msegSlots : [];
  const inputEnvelopeSlots = Array.isArray(nextValue.envelopeSlots) ? nextValue.envelopeSlots : [];
  const inputMacroNames = Array.isArray(nextValue.macroNames) ? nextValue.macroNames : [];
  return {
    format: "cosimo.modulation",
    version: MODULATION_STATE_VERSION,
    msegSlots: Array.from({ length: MODULATION_MSEG_SLOT_COUNT }, (_, slotIndex) => normalizeMsegSlot(inputMsegSlots[slotIndex], slotIndex)),
    envelopeSlots: Array.from({ length: MODULATION_ENV_SLOT_COUNT }, (_, slotIndex) => normalizeEnvelopeSlot(inputEnvelopeSlots[slotIndex], slotIndex)),
    routes: normalizeRoutes(nextValue.routes),
    macroNames: Array.from(
      { length: MODULATION_MACRO_SLOT_COUNT },
      (_, slotIndex) => normalizeMacroName(inputMacroNames[slotIndex], slotIndex)
    )
  };
}
function modulationStatesEqual(left, right) {
  return left === right || canonicalJsonValuesEqual(left, right);
}
function serializeModulationState(state) {
  const parsedState = parseModulationState(state);
  if (parsedState._tag === "err") {
    throw parsedState.error;
  }
  return JSON.stringify(parsedState.value);
}
function parseModulationState(value) {
  let parsedValue = value;
  if (typeof value === "string") {
    if (value.trim() === "") {
      return err(new ModulationStateParseError("Expected a modulation document"));
    }
    try {
      parsedValue = JSON.parse(value);
    } catch {
      return err(new ModulationStateParseError("Expected valid modulation JSON"));
    }
  }
  const normalizedState = normalizeModulationState(parsedValue);
  if (!canonicalJsonValuesEqual(parsedValue, normalizedState) || !routesHaveUniqueIdentity(normalizedState.routes)) {
    return err(new ModulationStateParseError("Expected the current modulation schema"));
  }
  return ok(normalizedState);
}
function deserializeModulationState(value) {
  const parsedState = parseModulationState(value);
  if (parsedState._tag === "err") {
    throw parsedState.error;
  }
  return parsedState.value;
}
function toMsegPlaybackUpload(slotIndex, playback) {
  return {
    slot: slotIndex + 1,
    holdFinalValue: playback.holdFinalValue !== false,
    rateKind: 0,
    loopEnabled: Boolean(playback.loop),
    loopStart: playback.loop?.startX ?? 0,
    loopEnd: playback.loop?.endX ?? 1,
    noteOffPolicy: playback.noteOffPolicy === "immediate" ? 1 : playback.noteOffPolicy === "ignore" ? 2 : 0,
    legatoRestarts: Boolean(playback.legatoRestarts)
  };
}
function toMsegBufferUpload(slotIndex, shapeIndex, shape) {
  return {
    slot: slotIndex + 1,
    shapeIndex,
    buffer: Array.from(renderMsegShape(shape))
  };
}
function msegPlaybackPoliciesEqual(left, right) {
  return left.holdFinalValue === right.holdFinalValue && left.noteOffPolicy === right.noteOffPolicy && left.legatoRestarts === right.legatoRestarts && JSON.stringify(left.loop) === JSON.stringify(right.loop);
}
function buildModulationRuntimeEvents(state, previousState = null, curveCommand) {
  const events = [];
  for (let slotIndex = 0; slotIndex < MODULATION_MSEG_SLOT_COUNT; slotIndex += 1) {
    const slot = state.msegSlots[slotIndex];
    const previousSlot = previousState?.msegSlots[slotIndex];
    if (previousSlot === void 0 || !msegShapesEqual(previousSlot.shapeA, slot.shapeA)) {
      events.push(curveCommand ? curveCommand(slotIndex, 0, slot.shapeA) : {
        endpointID: MODULATION_MSEG_BUFFER_ENDPOINT_ID,
        value: toMsegBufferUpload(slotIndex, 0, slot.shapeA)
      });
    }
    if (previousSlot === void 0 || !msegShapesEqual(previousSlot.shapeB, slot.shapeB)) {
      events.push(curveCommand ? curveCommand(slotIndex, 1, slot.shapeB) : {
        endpointID: MODULATION_MSEG_BUFFER_ENDPOINT_ID,
        value: toMsegBufferUpload(slotIndex, 1, slot.shapeB)
      });
    }
    if (previousSlot === void 0 || !msegPlaybackPoliciesEqual(previousSlot.playback, slot.playback)) {
      events.push({
        endpointID: MODULATION_MSEG_PLAYBACK_ENDPOINT_ID,
        value: toMsegPlaybackUpload(slotIndex, slot.playback)
      });
    }
  }
  events.push(...buildModulationRuntimeProgramEvents(previousState?.routes ?? null, state.routes));
  return events;
}
function getModulationSourceOptionValue(route) {
  const match = MODULATION_SOURCE_OPTIONS.find((option) => option.sourceKind === route.sourceKind && option.sourceSlot === route.sourceSlot);
  return match?.value ?? MODULATION_SOURCE_OPTIONS[0].value;
}
function applyModulationSourceOption(route, sourceValue) {
  const option = MODULATION_SOURCE_OPTIONS.find((candidate) => candidate.value === sourceValue) ?? MODULATION_SOURCE_OPTIONS[0];
  return {
    ...route,
    sourceKind: option.sourceKind,
    sourceSlot: option.sourceSlot
  };
}
function buildDisplayedMsegState(bridge, slotIndex) {
  return bridge.getMsegSlotController(slotIndex).getState();
}
export {
  AMP_ENVELOPE_SOURCE_SLOT,
  MODULATION_ENV_SLOT_COUNT,
  MODULATION_MACRO_SLOT_COUNT,
  MODULATION_MSEG_BUFFER_ENDPOINT_ID,
  MODULATION_MSEG_PLAYBACK_ENDPOINT_ID,
  MODULATION_MSEG_SLOT_COUNT,
  MODULATION_SOURCE_OPTIONS,
  MODULATION_STATE_KEY,
  MODULATION_STATE_VERSION,
  MODULATION_TARGET_OPTIONS,
  ModulationStateParseError,
  applyModulationSourceOption,
  buildDisplayedMsegState,
  buildModulationRuntimeEvents,
  buildPatchModulationTargetOptions,
  clampModulationRouteAmount,
  composeModulationAmount,
  createAvailableGeneratedRouteId,
  createDefaultEnvelope,
  createDefaultModulationState,
  createDefaultRoute,
  createFirstAvailableModulationRoute,
  deserializeModulationState,
  formatModulationAmountReadout,
  getModulationAmountBounds,
  getModulationAmountDepth,
  getModulationAmountPercentLabel,
  getModulationAmountSliderPosition,
  getModulationSourceOptionValue,
  getModulationTargetClampHint,
  isRackBusModulationTarget,
  isRackModulationTarget,
  isVoiceModulationSource,
  modulationRoutePairKey,
  modulationStatesEqual,
  normalizeEnvelope,
  normalizeEnvelopeSlot,
  normalizeMacroName,
  normalizeModulationState,
  normalizeRoute,
  normalizeRoutes,
  parseAnyModulationTargetKind,
  parseModulationState,
  serializeModulationState
};
