// Generated from ui/shared/modulation.ts by node ui/build.mjs. Do not edit this file directly.
import { MSEG_DEFAULT_DEPTH, addMsegPoint, clamp01, clampMsegRateSeconds, createDefaultMsegPlayback, createDefaultMsegShape, deleteMsegPoint, msegPlaybacksEqual, msegShapesEqual, moveMsegPoint, normalizeMsegPlayback, normalizeMsegShape, renderMsegShape, setMsegSegmentCurvePower, } from "./mseg.js";
export const MODULATION_STATE_KEY = "modulation.v2";
export const MODULATION_MAX_ROUTES = 12;
export const MODULATION_MSEG_SLOT_COUNT = 3;
export const MODULATION_ENV_SLOT_COUNT = 3;
export const MODULATION_CLEAR_ENDPOINT_ID = "modulationClear";
export const MODULATION_ENABLE_ENDPOINT_ID = "modulationEnable";
export const MODULATION_MSEG_BUFFER_ENDPOINT_ID = "modulationMsegBuffer";
export const MODULATION_MSEG_PLAYBACK_ENDPOINT_ID = "modulationMsegPlayback";
export const MODULATION_ENV_ENDPOINT_ID = "modulationEnvelope";
export const MODULATION_ROUTE_ENDPOINT_ID = "modulationRoute";
export const MOD_SOURCE_MSEG = 1;
export const MOD_SOURCE_ENV = 2;
export const MOD_SOURCE_VELOCITY = 3;
export const MOD_SOURCE_PRESSURE = 4;
export const MOD_SOURCE_SLIDE = 5;
export const MOD_POLARITY_UNIPOLAR = 0;
export const MOD_POLARITY_BIPOLAR = 1;
export const MOD_TARGET_WAVETABLE_POSITION = 1;
export const MOD_TARGET_WARP_AMOUNT = 2;
export const MOD_TARGET_FILTER_CUTOFF_OCTAVES = 3;
export const MOD_TARGET_FILTER_Q = 4;
export const MOD_TARGET_PITCH_SEMITONES = 5;
export const MOD_TARGET_AMP_GAIN_DB = 6;
export const MOD_TARGET_PAN = 7;
const MSEG_SLOT_NAMES = ["MSEG 1", "MSEG 2", "MSEG 3"];
const ENV_SLOT_NAMES = ["Env 1", "Env 2", "Env 3"];
const ENV_MIN_SECONDS = 0.001;
const ENV_MAX_SECONDS = 10.0;
const FILTER_Q_MIN = 0.1;
const FILTER_Q_MAX = 20.0;
const ROUTE_AMOUNT_LIMITS = {
    wavetablePosition: { min: -1.0, max: 1.0 },
    warpAmount: { min: -1.0, max: 1.0 },
    filterCutoffOctaves: { min: -6.0, max: 6.0 },
    filterQ: { min: -(FILTER_Q_MAX - FILTER_Q_MIN), max: FILTER_Q_MAX - FILTER_Q_MIN },
    pitchSemitones: { min: -48.0, max: 48.0 },
    ampGainDb: { min: -48.0, max: 6.0 },
    pan: { min: -1.0, max: 1.0 },
};
const ROUTE_AMOUNT_STEPS = {
    wavetablePosition: 0.001,
    warpAmount: 0.001,
    filterCutoffOctaves: 0.001,
    filterQ: 0.001,
    pitchSemitones: 0.01,
    ampGainDb: 0.1,
    pan: 0.001,
};
export const MODULATION_SOURCE_OPTIONS = [
    { value: "mseg-1", label: "MSEG 1", sourceKind: "mseg", sourceSlot: 1 },
    { value: "mseg-2", label: "MSEG 2", sourceKind: "mseg", sourceSlot: 2 },
    { value: "mseg-3", label: "MSEG 3", sourceKind: "mseg", sourceSlot: 3 },
    { value: "env-1", label: "ENV 1", sourceKind: "env", sourceSlot: 1 },
    { value: "env-2", label: "ENV 2", sourceKind: "env", sourceSlot: 2 },
    { value: "env-3", label: "ENV 3", sourceKind: "env", sourceSlot: 3 },
    { value: "velocity", label: "VEL", sourceKind: "velocity", sourceSlot: null },
    { value: "pressure", label: "AT", sourceKind: "pressure", sourceSlot: null },
    { value: "slide", label: "SLIDE", sourceKind: "slide", sourceSlot: null },
];
export const MODULATION_TARGET_OPTIONS = [
    { value: "wavetablePosition", label: "WT POS" },
    { value: "warpAmount", label: "WARP" },
    { value: "filterCutoffOctaves", label: "CUTOFF" },
    { value: "filterQ", label: "RES" },
    { value: "pitchSemitones", label: "PITCH" },
    { value: "ampGainDb", label: "AMP" },
    { value: "pan", label: "PAN" },
];
let generatedRouteIdCounter = 1;
function clamp(value, min, max) {
    return Math.min(Math.max(value, min), max);
}
function clampEnvSeconds(value, fallback) {
    const numeric = Number(value);
    return clamp(Number.isFinite(numeric) ? numeric : fallback, ENV_MIN_SECONDS, ENV_MAX_SECONDS);
}
function formatMagnitude(value, digits) {
    const numeric = Number.isFinite(value) ? value : 0;
    return Math.abs(numeric).toFixed(digits);
}
function formatSignedNumeric(value, digits) {
    const numeric = Number.isFinite(value) ? Number(value.toFixed(digits)) : 0;
    if (Math.abs(numeric) <= 1e-9) {
        return "0";
    }
    return String(numeric);
}
function getRouteAmountLimit(targetKind) {
    return ROUTE_AMOUNT_LIMITS[targetKind];
}
function getRouteAmountMagnitudeLimit(targetKind) {
    const limits = getRouteAmountLimit(targetKind);
    return Math.max(Math.abs(limits.min), Math.abs(limits.max));
}
function getRouteAmountSideLimit(targetKind, amount) {
    const limits = getRouteAmountLimit(targetKind);
    if (amount < 0) {
        return Math.abs(limits.min);
    }
    if (amount > 0) {
        return Math.abs(limits.max);
    }
    return getRouteAmountMagnitudeLimit(targetKind);
}
function createGeneratedRouteId() {
    const routeId = `mod-route-auto-${generatedRouteIdCounter}`;
    generatedRouteIdCounter += 1;
    return routeId;
}
function normalizeRouteId(value, routeIndex) {
    if (typeof value === "string" && value.trim()) {
        return value;
    }
    return `mod-route-${routeIndex + 1}`;
}
function normalizePolarity(value) {
    return value === "bipolar" ? "bipolar" : "unipolar";
}
function polarityToCode(polarity) {
    return polarity === "bipolar" ? MOD_POLARITY_BIPOLAR : MOD_POLARITY_UNIPOLAR;
}
export function getModulationAmountBounds(targetKind) {
    const limits = getRouteAmountLimit(targetKind);
    return {
        min: limits.min,
        max: limits.max,
        step: ROUTE_AMOUNT_STEPS[targetKind],
    };
}
export function clampModulationRouteAmount(targetKind, value) {
    const limits = ROUTE_AMOUNT_LIMITS[targetKind];
    const numeric = Number(value);
    return clamp(Number.isFinite(numeric) ? numeric : 0.0, limits.min, limits.max);
}
export function getModulationAmountDepth(targetKind, amount) {
    const clampedAmount = clampModulationRouteAmount(targetKind, amount);
    const limit = getRouteAmountSideLimit(targetKind, clampedAmount);
    if (limit <= 0) {
        return 0;
    }
    return clamp(Math.abs(clampedAmount) / limit, 0, 1);
}
export function composeModulationAmount(targetKind, depth) {
    const limits = getRouteAmountLimit(targetKind);
    const clampedDepth = clamp(Number.isFinite(depth) ? depth : 0, 0, 1);
    if (Math.abs(clampedDepth - 0.5) <= 1e-9) {
        return 0;
    }
    if (clampedDepth <= 0.5) {
        if (Math.abs(limits.min) <= 1e-9) {
            return 0;
        }
        const negativeRatio = 1 - (clampedDepth / 0.5);
        return clampModulationRouteAmount(targetKind, limits.min * negativeRatio);
    }
    if (Math.abs(limits.max) <= 1e-9) {
        return 0;
    }
    const positiveRatio = (clampedDepth - 0.5) / 0.5;
    return clampModulationRouteAmount(targetKind, limits.max * positiveRatio);
}
export function getModulationAmountSliderPosition(targetKind, amount) {
    const limits = getRouteAmountLimit(targetKind);
    const clampedAmount = clampModulationRouteAmount(targetKind, amount);
    if (Math.abs(clampedAmount) <= 1e-9) {
        return 0.5;
    }
    if (clampedAmount < 0) {
        if (Math.abs(limits.min) <= 1e-9) {
            return 0.5;
        }
        return clamp(0.5 * (1 - (Math.abs(clampedAmount) / Math.abs(limits.min))), 0, 0.5);
    }
    if (Math.abs(limits.max) <= 1e-9) {
        return 0.5;
    }
    return clamp(0.5 + (0.5 * (clampedAmount / limits.max)), 0.5, 1);
}
export function formatModulationAmountReadout(targetKind, amount, polarity = "unipolar") {
    const clampedAmount = clampModulationRouteAmount(targetKind, amount);
    const prefix = polarity === "bipolar"
        ? (Math.abs(clampedAmount) <= 1e-9 ? "" : "±")
        : (clampedAmount > 0 ? "+" : clampedAmount < 0 ? "-" : "");
    switch (targetKind) {
        case "wavetablePosition":
            return `${prefix}${formatMagnitude(clampedAmount * 100, 0)}%`;
        case "warpAmount":
            return `${prefix}${formatMagnitude(clampedAmount * 100, 0)}%`;
        case "filterCutoffOctaves":
            return `${prefix}${formatMagnitude(clampedAmount, 2)} oct`;
        case "filterQ":
            return `${prefix}${formatMagnitude(clampedAmount, 2)} Q`;
        case "pitchSemitones":
            return `${prefix}${formatMagnitude(clampedAmount, 1)} st`;
        case "ampGainDb":
            return `${prefix}${formatMagnitude(clampedAmount, 1)} dB`;
        case "pan": {
            const panPercent = Math.round(Math.abs(clampedAmount) * 100);
            if (panPercent === 0) {
                return "0%";
            }
            if (polarity === "bipolar") {
                return `±${panPercent}%`;
            }
            return `${panPercent}% ${clampedAmount < 0 ? "L" : "R"}`;
        }
        default:
            return `${prefix}${formatMagnitude(clampedAmount, 3)}`;
    }
}
export function formatModulationAmountEditingValue(targetKind, amount) {
    const clampedAmount = clampModulationRouteAmount(targetKind, amount);
    switch (targetKind) {
        case "wavetablePosition":
        case "warpAmount":
        case "pan":
            return formatSignedNumeric(clampedAmount * 100, 1);
        case "filterCutoffOctaves":
            return formatSignedNumeric(clampedAmount, 2);
        case "filterQ":
            return formatSignedNumeric(clampedAmount, 2);
        case "pitchSemitones":
            return formatSignedNumeric(clampedAmount, 2);
        case "ampGainDb":
            return formatSignedNumeric(clampedAmount, 1);
        default:
            return formatSignedNumeric(clampedAmount, 3);
    }
}
export function parseModulationAmountEditingValue(targetKind, rawText) {
    const normalizedText = String(rawText ?? "")
        .trim()
        .toLowerCase()
        .replace(/,/g, "")
        .replace(/\s+/g, "");
    if (!normalizedText) {
        return null;
    }
    let suffixDirection = 1;
    let numericText = normalizedText;
    if (targetKind === "pan") {
        if (numericText.endsWith("l")) {
            suffixDirection = -1;
            numericText = numericText.slice(0, -1);
        }
        else if (numericText.endsWith("r")) {
            suffixDirection = 1;
            numericText = numericText.slice(0, -1);
        }
    }
    numericText = numericText.replace(/%|oct|st|db|q/g, "");
    const numericValue = Number.parseFloat(numericText);
    if (!Number.isFinite(numericValue)) {
        return null;
    }
    if (targetKind === "wavetablePosition" || targetKind === "warpAmount") {
        return clampModulationRouteAmount(targetKind, numericValue / 100);
    }
    if (targetKind === "pan") {
        const signedValue = /^[+-]/.test(numericText)
            ? numericValue
            : (Math.abs(numericValue) * suffixDirection);
        return clampModulationRouteAmount(targetKind, signedValue / 100);
    }
    return clampModulationRouteAmount(targetKind, numericValue);
}
export function getModulationAmountPercentLabel(targetKind, amount) {
    return `${Math.round(getModulationAmountDepth(targetKind, amount) * 100)}%`;
}
export function getModulationTargetClampHint(targetKind) {
    switch (targetKind) {
        case "wavetablePosition":
            return "Wavetable scan still clamps to the table range.";
        case "warpAmount":
            return "Warp amount still clamps to the oscillator's warp range.";
        case "filterCutoffOctaves":
            return "Requested cutoff movement is converted to Hz and still clamps to the filter range.";
        case "filterQ":
            return "Resonance still clamps to the synth's Q range.";
        case "pitchSemitones":
            return "Pitch depth adds on top of note, glide, and bend.";
        case "ampGainDb":
            return "Amplitude still clamps to the synth's gain range.";
        case "pan":
            return "Pan still clamps between full left and full right.";
        default:
            return "";
    }
}
function normalizeSourceKind(value) {
    if (value === "mseg" || value === "env" || value === "velocity" || value === "pressure" || value === "slide") {
        return value;
    }
    return "mseg";
}
function normalizeTargetKind(value) {
    if (value === "wavetablePosition"
        || value === "warpAmount"
        || value === "filterCutoffOctaves"
        || value === "filterQ"
        || value === "pitchSemitones"
        || value === "ampGainDb"
        || value === "pan") {
        return value;
    }
    return "wavetablePosition";
}
function normalizeSourceSlot(sourceKind, rawSlot) {
    const numericSlot = Math.round(Number(rawSlot));
    if (sourceKind === "velocity" || sourceKind === "pressure" || sourceKind === "slide") {
        return null;
    }
    const maxSlot = sourceKind === "mseg" ? MODULATION_MSEG_SLOT_COUNT : MODULATION_ENV_SLOT_COUNT;
    return clamp(Number.isFinite(numericSlot) ? numericSlot : 1, 1, maxSlot);
}
export function createDefaultEnvelope(slotIndex) {
    return {
        name: ENV_SLOT_NAMES[slotIndex] ?? `Env ${slotIndex + 1}`,
        attackSeconds: 0.01,
        decaySeconds: 0.25,
        sustain: 0.5,
        releaseSeconds: 0.2,
    };
}
export function normalizeEnvelope(value, slotIndex = 0) {
    const nextValue = value && typeof value === "object" ? value : {};
    const fallback = createDefaultEnvelope(slotIndex);
    return {
        name: typeof nextValue.name === "string" && nextValue.name.trim() ? nextValue.name : fallback.name,
        attackSeconds: clampEnvSeconds(nextValue.attackSeconds ?? fallback.attackSeconds, fallback.attackSeconds),
        decaySeconds: clampEnvSeconds(nextValue.decaySeconds ?? fallback.decaySeconds, fallback.decaySeconds),
        sustain: clamp01(nextValue.sustain ?? fallback.sustain),
        releaseSeconds: clampEnvSeconds(nextValue.releaseSeconds ?? fallback.releaseSeconds, fallback.releaseSeconds),
    };
}
export function createDefaultRoute(overrides = {}) {
    return {
        id: overrides.id ?? createGeneratedRouteId(),
        enabled: true,
        sourceKind: "mseg",
        sourceSlot: 1,
        polarity: "unipolar",
        targetKind: "wavetablePosition",
        amount: 0,
        ...overrides,
    };
}
export function normalizeRoute(value, routeIndex = 0) {
    const nextValue = value && typeof value === "object" ? value : {};
    const sourceKind = normalizeSourceKind(nextValue.sourceKind);
    const targetKind = normalizeTargetKind(nextValue.targetKind);
    const numericAmount = Number(nextValue.amount);
    return {
        id: normalizeRouteId(nextValue.id, routeIndex),
        enabled: nextValue.enabled !== false,
        sourceKind,
        sourceSlot: normalizeSourceSlot(sourceKind, nextValue.sourceSlot),
        polarity: normalizePolarity(nextValue.polarity),
        targetKind,
        amount: clampModulationRouteAmount(targetKind, numericAmount),
    };
}
function normalizeMsegSlot(value, slotIndex) {
    const nextValue = value && typeof value === "object" ? value : {};
    const defaultShape = createDefaultMsegShape(MSEG_SLOT_NAMES[slotIndex] ?? `MSEG ${slotIndex + 1}`);
    const shapeA = normalizeMsegShape(nextValue.shapeA ?? defaultShape);
    return {
        shapeA,
        shapeB: normalizeMsegShape(nextValue.shapeB ?? shapeA),
        morph: clamp01(nextValue.morph ?? 0),
        playback: normalizeMsegPlayback(nextValue.playback ?? createDefaultMsegPlayback()),
    };
}
export function createDefaultModulationState() {
    return {
        format: "cosimo.modulation",
        version: 2,
        msegSlots: Array.from({ length: MODULATION_MSEG_SLOT_COUNT }, (_, slotIndex) => normalizeMsegSlot({}, slotIndex)),
        envelopeSlots: Array.from({ length: MODULATION_ENV_SLOT_COUNT }, (_, slotIndex) => createDefaultEnvelope(slotIndex)),
        routes: [createDefaultRoute({ id: "mod-route-1" })],
    };
}
export function normalizeModulationState(value = createDefaultModulationState()) {
    const nextValue = value && typeof value === "object" ? value : {};
    const inputMsegSlots = Array.isArray(nextValue.msegSlots) ? nextValue.msegSlots : [];
    const inputEnvelopeSlots = Array.isArray(nextValue.envelopeSlots) ? nextValue.envelopeSlots : [];
    const inputRoutes = Array.isArray(nextValue.routes) ? nextValue.routes : [];
    return {
        format: "cosimo.modulation",
        version: 2,
        msegSlots: Array.from({ length: MODULATION_MSEG_SLOT_COUNT }, (_, slotIndex) => normalizeMsegSlot(inputMsegSlots[slotIndex], slotIndex)),
        envelopeSlots: Array.from({ length: MODULATION_ENV_SLOT_COUNT }, (_, slotIndex) => normalizeEnvelope(inputEnvelopeSlots[slotIndex], slotIndex)),
        routes: inputRoutes.slice(0, MODULATION_MAX_ROUTES).map((route, routeIndex) => normalizeRoute(route, routeIndex)),
    };
}
export function serializeModulationState(state) {
    return JSON.stringify(normalizeModulationState(state));
}
export function deserializeModulationState(value) {
    if (typeof value !== "string" || value.trim() === "") {
        return createDefaultModulationState();
    }
    try {
        return normalizeModulationState(JSON.parse(value));
    }
    catch {
        return createDefaultModulationState();
    }
}
function modulationStatesEqual(left, right) {
    return serializeModulationState(left) === serializeModulationState(right);
}
function toStoredStateEchoToken(value) {
    try {
        return `${typeof value}:${JSON.stringify(value)}`;
    }
    catch {
        return `${typeof value}:${String(value)}`;
    }
}
function sourceKindToCode(sourceKind) {
    if (sourceKind === "mseg")
        return MOD_SOURCE_MSEG;
    if (sourceKind === "env")
        return MOD_SOURCE_ENV;
    if (sourceKind === "velocity")
        return MOD_SOURCE_VELOCITY;
    if (sourceKind === "pressure")
        return MOD_SOURCE_PRESSURE;
    return MOD_SOURCE_SLIDE;
}
function targetKindToCode(targetKind) {
    if (targetKind === "wavetablePosition")
        return MOD_TARGET_WAVETABLE_POSITION;
    if (targetKind === "warpAmount")
        return MOD_TARGET_WARP_AMOUNT;
    if (targetKind === "filterCutoffOctaves")
        return MOD_TARGET_FILTER_CUTOFF_OCTAVES;
    if (targetKind === "filterQ")
        return MOD_TARGET_FILTER_Q;
    if (targetKind === "pitchSemitones")
        return MOD_TARGET_PITCH_SEMITONES;
    if (targetKind === "ampGainDb")
        return MOD_TARGET_AMP_GAIN_DB;
    return MOD_TARGET_PAN;
}
function toMsegPlaybackUpload(slotIndex, playback) {
    return {
        slot: slotIndex + 1,
        seconds: clampMsegRateSeconds(playback.rate.seconds),
        holdFinalValue: playback.holdFinalValue !== false,
        rateKind: 0,
        loopEnabled: Boolean(playback.loop),
        loopStart: playback.loop?.startX ?? 0,
        loopEnd: playback.loop?.endX ?? 1,
        noteOffPolicy: playback.noteOffPolicy === "immediate"
            ? 1
            : playback.noteOffPolicy === "ignore"
                ? 2
                : 0,
        legatoRestarts: Boolean(playback.legatoRestarts),
    };
}
function toMsegBufferUpload(slotIndex, shapeIndex, shape) {
    return {
        slot: slotIndex + 1,
        shapeIndex,
        buffer: Array.from(renderMsegShape(shape)),
    };
}
function toEnvelopeUpload(slotIndex, envelope) {
    return {
        slot: slotIndex + 1,
        attackSeconds: envelope.attackSeconds,
        decaySeconds: envelope.decaySeconds,
        sustain: envelope.sustain,
        releaseSeconds: envelope.releaseSeconds,
    };
}
function toRouteUpload(routeIndex, route) {
    const normalizedRoute = route ? normalizeRoute(route) : null;
    const isEnabled = normalizedRoute?.enabled ?? false;
    return {
        routeIndex,
        enabled: isEnabled,
        sourceKind: sourceKindToCode(normalizedRoute?.sourceKind ?? "mseg"),
        sourceSlot: isEnabled ? (normalizedRoute?.sourceSlot ?? 0) : 0,
        polarityKind: polarityToCode(normalizedRoute?.polarity ?? "unipolar"),
        targetKind: targetKindToCode(normalizedRoute?.targetKind ?? "wavetablePosition"),
        amount: isEnabled ? (normalizedRoute?.amount ?? 0.0) : 0.0,
    };
}
export function buildModulationRuntimeEvents(stateValue) {
    const state = normalizeModulationState(stateValue);
    const events = [
        { endpointID: MODULATION_ENABLE_ENDPOINT_ID, value: 0 },
        { endpointID: MODULATION_CLEAR_ENDPOINT_ID, value: 1 },
    ];
    for (let slotIndex = 0; slotIndex < MODULATION_MSEG_SLOT_COUNT; slotIndex += 1) {
        const slot = state.msegSlots[slotIndex];
        events.push({
            endpointID: MODULATION_MSEG_BUFFER_ENDPOINT_ID,
            value: toMsegBufferUpload(slotIndex, 0, slot.shapeA),
        });
        events.push({
            endpointID: MODULATION_MSEG_BUFFER_ENDPOINT_ID,
            value: toMsegBufferUpload(slotIndex, 1, slot.shapeB),
        });
        events.push({
            endpointID: MODULATION_MSEG_PLAYBACK_ENDPOINT_ID,
            value: toMsegPlaybackUpload(slotIndex, slot.playback),
        });
    }
    for (let slotIndex = 0; slotIndex < MODULATION_ENV_SLOT_COUNT; slotIndex += 1) {
        events.push({
            endpointID: MODULATION_ENV_ENDPOINT_ID,
            value: toEnvelopeUpload(slotIndex, state.envelopeSlots[slotIndex]),
        });
    }
    for (let routeIndex = 0; routeIndex < MODULATION_MAX_ROUTES; routeIndex += 1) {
        events.push({
            endpointID: MODULATION_ROUTE_ENDPOINT_ID,
            value: toRouteUpload(routeIndex, state.routes[routeIndex] ?? null),
        });
    }
    events.push({ endpointID: MODULATION_ENABLE_ENDPOINT_ID, value: 1 });
    return events;
}
export function getModulationSourceOptionValue(route) {
    const match = MODULATION_SOURCE_OPTIONS.find((option) => (option.sourceKind === route.sourceKind
        && option.sourceSlot === route.sourceSlot));
    return match?.value ?? MODULATION_SOURCE_OPTIONS[0].value;
}
export function applyModulationSourceOption(route, sourceValue) {
    const option = MODULATION_SOURCE_OPTIONS.find((candidate) => candidate.value === sourceValue)
        ?? MODULATION_SOURCE_OPTIONS[0];
    return {
        ...route,
        sourceKind: option.sourceKind,
        sourceSlot: option.sourceSlot,
    };
}
class ModulationMsegSlotController {
    bridge;
    slotIndex;
    constructor(bridge, slotIndex) {
        this.bridge = bridge;
        this.slotIndex = slotIndex;
    }
    getState() {
        const slot = this.bridge.getState().msegSlots[this.slotIndex];
        const editShapeIndex = this.bridge.getMsegSlotEditShapeIndex(this.slotIndex);
        const shape = editShapeIndex === 1 ? slot.shapeB : slot.shapeA;
        const referenceShape = editShapeIndex === 1 ? slot.shapeA : slot.shapeB;
        return {
            shape,
            shapeA: slot.shapeA,
            shapeB: slot.shapeB,
            referenceShape,
            editShapeIndex,
            morph: slot.morph,
            playback: slot.playback,
            depth: MSEG_DEFAULT_DEPTH,
        };
    }
    setShape(nextShape) {
        this.bridge.setMsegSlotShape(this.slotIndex, this.bridge.getMsegSlotEditShapeIndex(this.slotIndex), nextShape);
    }
    setEditShapeIndex(shapeIndex) {
        this.bridge.setMsegSlotEditShapeIndex(this.slotIndex, shapeIndex);
    }
    setPlayback(nextPlayback) {
        this.bridge.setMsegSlotPlayback(this.slotIndex, nextPlayback);
    }
    addPoint(x, y) {
        this.setShape(addMsegPoint(this.getState().shape, x, y));
    }
    movePoint(pointIndex, x, y) {
        this.setShape(moveMsegPoint(this.getState().shape, pointIndex, x, y));
    }
    deletePoint(pointIndex) {
        this.setShape(deleteMsegPoint(this.getState().shape, pointIndex));
    }
    setSegmentCurvePower(segmentIndex, curvePower) {
        this.setShape(setMsegSegmentCurvePower(this.getState().shape, segmentIndex, curvePower));
    }
}
export class ModulationRuntimeBridge {
    patchConnection;
    state = createDefaultModulationState();
    suppressStoredStateEvents = 0;
    pendingStoredStateEchoes = new Map();
    stateListeners = new Set();
    msegSlotEditShapeIndexes = Array.from({ length: MODULATION_MSEG_SLOT_COUNT }, () => 0);
    slotControllers = Array.from({ length: MODULATION_MSEG_SLOT_COUNT }, (_, slotIndex) => new ModulationMsegSlotController(this, slotIndex));
    constructor(patchConnection) {
        this.patchConnection = patchConnection;
        this.handleStoredStateValue = this.handleStoredStateValue.bind(this);
    }
    attach() {
        this.patchConnection.addStoredStateValueListener?.(this.handleStoredStateValue);
    }
    detach() {
        this.patchConnection.removeStoredStateValueListener?.(this.handleStoredStateValue);
    }
    requestBootState() {
        if (typeof this.patchConnection.requestFullStoredState === "function") {
            this.patchConnection.requestFullStoredState((storedState) => {
                const fullState = storedState && typeof storedState === "object"
                    ? storedState
                    : {};
                this.applyStoredState(fullState[MODULATION_STATE_KEY]);
            });
            return;
        }
        if (typeof this.patchConnection.requestStoredStateValue === "function") {
            this.patchConnection.requestStoredStateValue(MODULATION_STATE_KEY);
            return;
        }
        this.emitStateChange();
    }
    getState() {
        return this.state;
    }
    subscribe(listener) {
        this.stateListeners.add(listener);
    }
    unsubscribe(listener) {
        this.stateListeners.delete(listener);
    }
    getMsegSlotController(slotIndex) {
        return this.slotControllers[clamp(Math.round(slotIndex), 0, MODULATION_MSEG_SLOT_COUNT - 1)];
    }
    getMsegSlotEditShapeIndex(slotIndex) {
        return this.msegSlotEditShapeIndexes[clamp(Math.round(slotIndex), 0, MODULATION_MSEG_SLOT_COUNT - 1)];
    }
    setMsegSlotEditShapeIndex(slotIndex, shapeIndex) {
        const normalizedSlotIndex = clamp(Math.round(slotIndex), 0, MODULATION_MSEG_SLOT_COUNT - 1);
        const normalizedShapeIndex = Math.round(Number(shapeIndex)) === 1 ? 1 : 0;
        if (this.msegSlotEditShapeIndexes[normalizedSlotIndex] === normalizedShapeIndex) {
            return;
        }
        this.msegSlotEditShapeIndexes[normalizedSlotIndex] = normalizedShapeIndex;
        this.emitStateChange();
    }
    setState(nextState) {
        const normalizedState = normalizeModulationState(nextState);
        if (modulationStatesEqual(this.state, normalizedState)) {
            return;
        }
        this.state = normalizedState;
        this.persistState();
        this.emitStateChange();
    }
    setMsegSlotShape(slotIndex, shapeIndex, nextShape) {
        const normalizedShape = normalizeMsegShape(nextShape);
        const currentSlot = this.state.msegSlots[slotIndex];
        const currentShape = Math.round(Number(shapeIndex)) === 1 ? currentSlot.shapeB : currentSlot.shapeA;
        if (msegShapesEqual(currentShape, normalizedShape)) {
            return;
        }
        this.updateState((previousState) => {
            const nextMsegSlots = previousState.msegSlots.map((slot, index) => (index === slotIndex
                ? Math.round(Number(shapeIndex)) === 1
                    ? { ...slot, shapeB: normalizedShape }
                    : { ...slot, shapeA: normalizedShape }
                : slot));
            return {
                ...previousState,
                msegSlots: nextMsegSlots,
            };
        });
    }
    setMsegSlotMorph(slotIndex, nextMorph) {
        const normalizedMorph = clamp01(nextMorph);
        const currentSlot = this.state.msegSlots[slotIndex];
        if (currentSlot.morph === normalizedMorph) {
            return;
        }
        this.updateState((previousState) => ({
            ...previousState,
            msegSlots: previousState.msegSlots.map((slot, index) => (index === slotIndex ? { ...slot, morph: normalizedMorph } : slot)),
        }));
    }
    setMsegSlotPlayback(slotIndex, nextPlayback) {
        const normalizedPlayback = normalizeMsegPlayback(nextPlayback);
        const currentSlot = this.state.msegSlots[slotIndex];
        if (msegPlaybacksEqual(currentSlot.playback, normalizedPlayback)) {
            return;
        }
        this.updateState((previousState) => {
            const nextMsegSlots = previousState.msegSlots.map((slot, index) => (index === slotIndex
                ? { ...slot, playback: normalizedPlayback }
                : slot));
            return {
                ...previousState,
                msegSlots: nextMsegSlots,
            };
        });
    }
    setEnvelope(slotIndex, nextEnvelope) {
        const normalizedEnvelope = normalizeEnvelope(nextEnvelope, slotIndex);
        const currentEnvelope = this.state.envelopeSlots[slotIndex];
        if (JSON.stringify(currentEnvelope) === JSON.stringify(normalizedEnvelope)) {
            return;
        }
        this.updateState((previousState) => ({
            ...previousState,
            envelopeSlots: previousState.envelopeSlots.map((envelope, index) => (index === slotIndex ? normalizedEnvelope : envelope)),
        }));
    }
    replaceRoutes(nextRoutes) {
        const normalizedRoutes = Array.isArray(nextRoutes)
            ? nextRoutes.slice(0, MODULATION_MAX_ROUTES).map((route, routeIndex) => normalizeRoute(route, routeIndex))
            : [];
        if (JSON.stringify(this.state.routes) === JSON.stringify(normalizedRoutes)) {
            return;
        }
        this.updateState((previousState) => ({
            ...previousState,
            routes: normalizedRoutes,
        }));
    }
    setRoute(routeIndex, nextRoute) {
        const normalizedRoute = normalizeRoute(nextRoute, routeIndex);
        const currentRoutes = [...this.state.routes];
        while (currentRoutes.length <= routeIndex) {
            currentRoutes.push(createDefaultRoute());
        }
        if (JSON.stringify(currentRoutes[routeIndex]) === JSON.stringify(normalizedRoute)) {
            return;
        }
        currentRoutes[routeIndex] = normalizedRoute;
        this.replaceRoutes(currentRoutes);
    }
    addRoute(nextRoute = createDefaultRoute()) {
        if (this.state.routes.length >= MODULATION_MAX_ROUTES) {
            return;
        }
        this.replaceRoutes([...this.state.routes, normalizeRoute(nextRoute, this.state.routes.length)]);
    }
    removeRoute(routeIndex) {
        if (routeIndex < 0 || routeIndex >= this.state.routes.length) {
            return;
        }
        const nextRoutes = this.state.routes.filter((_, index) => index !== routeIndex);
        this.replaceRoutes(nextRoutes);
    }
    updateState(update) {
        const nextState = normalizeModulationState(update(this.state));
        if (modulationStatesEqual(this.state, nextState)) {
            return;
        }
        this.state = nextState;
        this.persistState();
        this.emitStateChange();
    }
    applyStoredState(rawValue) {
        const nextState = deserializeModulationState(rawValue);
        this.state = nextState;
        this.emitStateChange();
    }
    handleStoredStateValue(message) {
        if (!message || typeof message !== "object") {
            return;
        }
        const nextMessage = message;
        if (this.suppressStoredStateEvents > 0) {
            return;
        }
        if (typeof nextMessage.key === "string" && this.consumePendingStoredStateEcho(nextMessage.key, nextMessage.value)) {
            return;
        }
        if (nextMessage.key === MODULATION_STATE_KEY) {
            this.applyStoredState(nextMessage.value);
        }
    }
    persistState() {
        if (typeof this.patchConnection.sendStoredStateValue !== "function") {
            return;
        }
        const persistedModulationState = serializeModulationState(this.state);
        this.suppressStoredStateEvents += 1;
        try {
            this.rememberPendingStoredStateEcho(MODULATION_STATE_KEY, persistedModulationState);
            this.patchConnection.sendStoredStateValue(MODULATION_STATE_KEY, persistedModulationState);
        }
        finally {
            this.suppressStoredStateEvents -= 1;
        }
    }
    emitStateChange() {
        const stateSnapshot = {
            ...this.state,
            msegSlots: [...this.state.msegSlots],
            envelopeSlots: [...this.state.envelopeSlots],
            routes: [...this.state.routes],
        };
        this.stateListeners.forEach((listener) => listener(stateSnapshot));
    }
    rememberPendingStoredStateEcho(key, value) {
        const token = toStoredStateEchoToken(value);
        const pendingByToken = this.pendingStoredStateEchoes.get(key) ?? new Map();
        pendingByToken.set(token, (pendingByToken.get(token) ?? 0) + 1);
        this.pendingStoredStateEchoes.set(key, pendingByToken);
    }
    consumePendingStoredStateEcho(key, value) {
        const pendingByToken = this.pendingStoredStateEchoes.get(key);
        if (!pendingByToken) {
            return false;
        }
        const token = toStoredStateEchoToken(value);
        const pendingCount = pendingByToken.get(token) ?? 0;
        if (pendingCount <= 0) {
            return false;
        }
        if (pendingCount === 1) {
            pendingByToken.delete(token);
        }
        else {
            pendingByToken.set(token, pendingCount - 1);
        }
        if (pendingByToken.size === 0) {
            this.pendingStoredStateEchoes.delete(key);
        }
        return true;
    }
}
export function buildDisplayedMsegState(bridge, slotIndex) {
    return bridge.getMsegSlotController(slotIndex).getState();
}
const sharedRuntimeBridges = new WeakMap();
export function acquireModulationRuntimeBridge(patchConnection) {
    const existingEntry = sharedRuntimeBridges.get(patchConnection);
    if (existingEntry) {
        existingEntry.refCount += 1;
        return existingEntry.bridge;
    }
    const bridge = new ModulationRuntimeBridge(patchConnection);
    bridge.attach();
    bridge.requestBootState();
    sharedRuntimeBridges.set(patchConnection, {
        bridge,
        refCount: 1,
    });
    return bridge;
}
export function releaseModulationRuntimeBridge(patchConnection) {
    const entry = sharedRuntimeBridges.get(patchConnection);
    if (!entry) {
        return;
    }
    entry.refCount -= 1;
    if (entry.refCount > 0) {
        return;
    }
    entry.bridge.detach();
    sharedRuntimeBridges.delete(patchConnection);
}
