// Generated from ui/shared/modulation-targets.ts by node ui/build.mjs. Do not edit this file directly.
import { allRackParameterDescriptors } from "./rack-parameter-descriptors.js";
/** Stable oscillator identities in runtime order. */
export const OSCILLATOR_IDS = ["A", "B", "C"];
/** Oscillator-local destinations in runtime order within each oscillator. */
export const OSCILLATOR_MODULATION_PARAMETER_KINDS = [
    "wavetablePosition",
    "warpAmount",
    "pitchSemitones",
    "ampGainDb",
    "pan",
    "unisonDetune",
    "unisonBlend",
    "unisonWidth",
    "unisonWavetablePositionSpread",
    "unisonWarpSpread",
];
/** Voice-global destinations following the three oscillator-local blocks. */
export const SHARED_VOICE_MODULATION_TARGET_KINDS = [
    "filterCutoffOctaves",
    "filterQ",
];
/** The complete source domain; display names live with presentation metadata. */
export const MODULATION_SOURCE_IDENTITIES = Object.freeze([
    { id: "mseg-1", sourceKind: "mseg", sourceSlot: 1, group: "voice", runtimeIndex: 0 },
    { id: "mseg-2", sourceKind: "mseg", sourceSlot: 2, group: "voice", runtimeIndex: 1 },
    { id: "mseg-3", sourceKind: "mseg", sourceSlot: 3, group: "voice", runtimeIndex: 2 },
    { id: "env-1", sourceKind: "env", sourceSlot: 1, group: "voice", runtimeIndex: 3 },
    { id: "env-2", sourceKind: "env", sourceSlot: 2, group: "voice", runtimeIndex: 4 },
    { id: "env-3", sourceKind: "env", sourceSlot: 3, group: "voice", runtimeIndex: 5 },
    { id: "macro-1", sourceKind: "macro", sourceSlot: 1, group: "macro", runtimeIndex: 0 },
    { id: "macro-2", sourceKind: "macro", sourceSlot: 2, group: "macro", runtimeIndex: 1 },
    { id: "macro-3", sourceKind: "macro", sourceSlot: 3, group: "macro", runtimeIndex: 2 },
    { id: "macro-4", sourceKind: "macro", sourceSlot: 4, group: "macro", runtimeIndex: 3 },
    { id: "velocity", sourceKind: "velocity", sourceSlot: null, group: "voice", runtimeIndex: 6 },
    { id: "pressure", sourceKind: "pressure", sourceSlot: null, group: "voice", runtimeIndex: 7 },
    { id: "slide", sourceKind: "slide", sourceSlot: null, group: "voice", runtimeIndex: 8 },
]);
/** The complete 32-destination voice domain in stable runtime order. */
export const VOICE_MODULATION_TARGET_KINDS = Object.freeze([
    ...OSCILLATOR_IDS.flatMap((oscillatorID) => (OSCILLATOR_MODULATION_PARAMETER_KINDS.map((parameterKind) => `osc${oscillatorID}.${parameterKind}`))),
    ...SHARED_VOICE_MODULATION_TARGET_KINDS,
]);
/** Voice destinations paired with their canonical runtime indexes. */
export const VOICE_MODULATION_TARGET_IDENTITIES = Object.freeze(VOICE_MODULATION_TARGET_KINDS.map((kind, runtimeIndex) => ({ kind, group: "voice", runtimeIndex })));
const rackModulationParameters = allRackParameterDescriptors()
    .filter((parameter) => parameter.modulationTargetIndex !== null);
/** Rack destinations paired with their descriptor-owned runtime indexes. */
export const RACK_MODULATION_TARGET_IDENTITIES = Object.freeze(rackModulationParameters.map((parameter) => ({
    // SAFETY: The preceding filter proves the authored index is non-null; endpoint IDs
    // and indexes are both minted only by the rack descriptor catalog.
    kind: `rack.${parameter.endpointID}`,
    group: "rack",
    runtimeIndex: parameter.modulationTargetIndex,
})).sort((left, right) => left.runtimeIndex - right.runtimeIndex));
/** Every canonical modulation target, with voice and rack indexes kept in separate runtime groups. */
export const MODULATION_TARGET_IDENTITIES = Object.freeze([
    ...VOICE_MODULATION_TARGET_IDENTITIES,
    ...RACK_MODULATION_TARGET_IDENTITIES,
]);
/** Number of canonical sources. */
export const MODULATION_SOURCE_COUNT = MODULATION_SOURCE_IDENTITIES.length;
/** Number of oscillator-local and shared voice destinations. */
export const MODULATION_VOICE_TARGET_COUNT = VOICE_MODULATION_TARGET_IDENTITIES.length;
/** Number of authored rack destinations. */
export const MODULATION_RACK_TARGET_COUNT = RACK_MODULATION_TARGET_IDENTITIES.length;
/** Complete legal source-target domain size. */
export const MODULATION_LEGAL_PAIR_COUNT = MODULATION_SOURCE_COUNT * MODULATION_TARGET_IDENTITIES.length;
const sourceIdentityById = new Map(MODULATION_SOURCE_IDENTITIES.map((identity) => [identity.id, identity]));
const sourceIdentityByAddress = new Map(MODULATION_SOURCE_IDENTITIES.map((identity) => [
    `${identity.sourceKind}:${identity.sourceSlot ?? 0}`,
    identity,
]));
const targetIdentityByKind = new Map(MODULATION_TARGET_IDENTITIES.map((identity) => [identity.kind, identity]));
function assertCanonicalIdentities() {
    if (MODULATION_SOURCE_COUNT !== 13
        || MODULATION_VOICE_TARGET_COUNT !== 32
        || MODULATION_RACK_TARGET_COUNT !== 36
        || MODULATION_LEGAL_PAIR_COUNT !== 884) {
        throw new Error("Modulation identity catalog has an unexpected domain size");
    }
    for (const [group, expectedCount] of [["voice", 9], ["macro", 4]]) {
        const identities = MODULATION_SOURCE_IDENTITIES.filter((identity) => identity.group === group);
        const indexes = identities.map((identity) => identity.runtimeIndex).sort((left, right) => left - right);
        if (identities.length !== expectedCount || indexes.some((index, position) => index !== position)) {
            throw new Error(`Modulation ${group} source indexes must be unique and contiguous`);
        }
    }
    for (const [group, expectedCount] of [["voice", 32], ["rack", 36]]) {
        const identities = MODULATION_TARGET_IDENTITIES.filter((identity) => identity.group === group);
        const indexes = identities.map((identity) => identity.runtimeIndex).sort((left, right) => left - right);
        if (identities.length !== expectedCount || indexes.some((index, position) => index !== position)) {
            throw new Error(`Modulation ${group} target indexes must be unique and contiguous`);
        }
    }
    if (sourceIdentityById.size !== MODULATION_SOURCE_COUNT
        || sourceIdentityByAddress.size !== MODULATION_SOURCE_COUNT
        || targetIdentityByKind.size !== MODULATION_TARGET_IDENTITIES.length) {
        throw new Error("Modulation identities must be unique");
    }
}
assertCanonicalIdentities();
/** Parse an untrusted source ID against the canonical source domain. */
export function parseModulationSourceIdentity(value) {
    if (typeof value !== "string")
        return null;
    // SAFETY: The map performs the runtime membership check before an identity is returned.
    return sourceIdentityById.get(value) ?? null;
}
/** Resolve a normalized route source to its canonical identity and runtime group. */
export function getModulationSourceIdentity(sourceKind, sourceSlot) {
    const identity = sourceIdentityByAddress.get(`${sourceKind}:${sourceSlot ?? 0}`);
    if (identity === undefined) {
        throw new Error(`Unknown modulation source: ${sourceKind}:${sourceSlot ?? 0}`);
    }
    return identity;
}
/** Parse an untrusted target kind without legacy aliases. */
export function parseModulationTargetKind(value) {
    if (typeof value !== "string")
        return null;
    return targetIdentityByKind.has(value) ? value : null;
}
/** Parse an untrusted voice target without legacy aliases. */
export function parseVoiceModulationTargetKind(value) {
    const targetKind = parseModulationTargetKind(value);
    return targetKind !== null && targetIdentityByKind.get(targetKind)?.group === "voice"
        ? targetKind
        : null;
}
/** Parse an untrusted rack target without accepting unknown `rack.*` strings. */
export function parseRackModulationTargetKind(value) {
    const targetKind = parseModulationTargetKind(value);
    return targetKind !== null && targetIdentityByKind.get(targetKind)?.group === "rack"
        ? targetKind
        : null;
}
/** Return the stable runtime target index for a canonical voice destination. */
export function getVoiceModulationTargetIndex(targetKind) {
    const identity = targetIdentityByKind.get(targetKind);
    if (identity?.group !== "voice")
        throw new Error(`Unknown voice modulation target: ${targetKind}`);
    return identity.runtimeIndex;
}
/** Return the stable runtime target index for a canonical rack destination. */
export function getRackModulationTargetIndex(targetKind) {
    const identity = targetIdentityByKind.get(targetKind);
    if (identity?.group !== "rack")
        throw new Error(`Unknown rack modulation target: ${targetKind}`);
    return identity.runtimeIndex;
}
/** Return the oscillator-local or shared parameter kind for a voice target. */
export function getVoiceModulationParameterKind(targetKind) {
    const separatorIndex = targetKind.indexOf(".");
    return separatorIndex >= 0
        ? targetKind.slice(separatorIndex + 1)
        : targetKind;
}
/** All canonical sources may address all canonical targets. */
export function isLegalModulationPair(sourceId, targetKind) {
    return parseModulationSourceIdentity(sourceId) !== null && parseModulationTargetKind(targetKind) !== null;
}
