// Generated from ui/shared/mseg.ts by node ui/build.mjs. Do not edit this file directly.
// kit/ui/mseg.ts
var MSEG_BODY_SAMPLES = 2048;
var MSEG_PADDED_SAMPLES = MSEG_BODY_SAMPLES + 3;
var MSEG_CURVE_POWER_LIMIT = 20;
var MSEG_DEFAULT_NAME = "MSEG 1";
var MSEG_DEFAULT_DEPTH = 1;
var MSEG_RATE_MIN_SECONDS = 0;
var MSEG_RATE_MAX_SECONDS = 2;
var MSEG_RATE_KIND_SECONDS = 0;
var MSEG_RATE_KIND_TEMPO = 1;
var MSEG_NOTE_OFF_POLICY_FINISH_LOOP = 0;
var MSEG_NOTE_OFF_POLICY_IMMEDIATE = 1;
var MSEG_NOTE_OFF_POLICY_IGNORE = 2;
var MSEG_POINT_HIT_RADIUS_PX = 22;
var MSEG_SEGMENT_HIT_RADIUS_PX = 14;
var MSEG_POINT_RADIUS_PX = 8;
var MSEG_SELECTED_POINT_RADIUS_PX = 10;
var MSEG_EDITOR_HORIZONTAL_PADDING_PX = 14;
var MSEG_EDITOR_VERTICAL_PADDING_PX = 14;
var MSEG_EDITOR_CURVE_TOLERANCE_PX = 0.5;
var MSEG_EDITOR_MAX_SUBDIVISION_DEPTH = 12;
var MSEG_TIME_AXIS_QUARTERS = [0.25, 0.5, 0.75];
var MSEG_ORIENTATION_HYSTERESIS_RATIO = 1.08;
function resolveMsegSurfaceOrientation(width, height, current) {
  const safeWidth = Math.max(1, Number(width) || 0);
  const safeHeight = Math.max(1, Number(height) || 0);
  if (current === "horizontal") {
    return safeHeight > safeWidth * MSEG_ORIENTATION_HYSTERESIS_RATIO ? "vertical" : "horizontal";
  }
  return safeWidth > safeHeight * MSEG_ORIENTATION_HYSTERESIS_RATIO ? "horizontal" : "vertical";
}
function objectFields(value) {
  return value !== null && typeof value === "object" ? value : {};
}
function clamp(value, min, max) {
  return Math.min(Math.max(value, min), max);
}
function greatestCommonDivisor(left, right) {
  let dividend = Math.abs(Math.trunc(left));
  let divisor = Math.abs(Math.trunc(right));
  while (divisor !== 0) {
    const remainder = dividend % divisor;
    dividend = divisor;
    divisor = remainder;
  }
  return Math.max(1, dividend);
}
function formatMsegSecondsTick(seconds) {
  const roundedMilliseconds = Math.round(Math.max(0, Number(seconds) || 0) * 1e3);
  const roundedSeconds = roundedMilliseconds / 1e3;
  return `${roundedSeconds}s`;
}
function formatMsegNoteTick(totalDivision, quarterIndex) {
  const totalNumerator = Math.max(1, Math.abs(Math.trunc(Number(totalDivision.numerator) || 1)));
  const totalDenominator = Math.max(1, Math.abs(Math.trunc(Number(totalDivision.denominator) || 1)));
  const numerator = totalNumerator * quarterIndex;
  const denominator = totalDenominator * 4;
  const divisor = greatestCommonDivisor(numerator, denominator);
  return `${numerator / divisor}/${denominator / divisor}`;
}
function createMsegTimeAxisTicks(scale) {
  return MSEG_TIME_AXIS_QUARTERS.map((fraction, index) => ({
    fraction,
    label: scale.kind === "seconds" ? formatMsegSecondsTick(scale.totalSeconds * fraction) : formatMsegNoteTick(scale.totalDivision, index + 1)
  }));
}
function almostEqual(left, right, epsilon = 1e-12) {
  return Math.abs(left - right) <= epsilon;
}
function clampCurvePower(value) {
  return clamp(Number.isFinite(value) ? value : 0, -MSEG_CURVE_POWER_LIMIT, MSEG_CURVE_POWER_LIMIT);
}
function clamp01(value) {
  return clamp(Number.isFinite(value) ? value : 0, 0, 1);
}
function createDefaultMsegShape(name = MSEG_DEFAULT_NAME) {
  return {
    format: "mseg.shape",
    version: 1,
    name,
    globalSmooth: false,
    points: [
      { x: 0, y: 0, curvePower: 0 },
      { x: 1, y: 1, curvePower: 0 }
    ]
  };
}
function createDefaultMsegPlayback() {
  return {
    format: "mseg.playback",
    version: 1,
    rate: {
      kind: "seconds",
      seconds: 1
    },
    loop: { startX: 0, endX: 1 },
    noteOffPolicy: "finish_loop",
    legatoRestarts: false,
    holdFinalValue: true
  };
}
function clampMsegDepth(value) {
  return clamp(Number.isFinite(value) ? value : 0, -1, 1);
}
function clampMsegRateSeconds(value) {
  const numericValue = Number(value);
  return clamp(
    Number.isFinite(numericValue) ? numericValue : 1,
    MSEG_RATE_MIN_SECONDS,
    MSEG_RATE_MAX_SECONDS
  );
}
function createMsegEditorMetrics(width, height, {
  pointRadius = MSEG_POINT_RADIUS_PX,
  horizontalPadding = MSEG_EDITOR_HORIZONTAL_PADDING_PX,
  verticalPadding = MSEG_EDITOR_VERTICAL_PADDING_PX
} = {}) {
  const safeWidth = Math.max(1, Number(width) || 0);
  const safeHeight = Math.max(1, Number(height) || 0);
  const safePointRadius = Math.max(0, Number(pointRadius) || 0);
  const safeHorizontalPadding = Math.max(0, Number(horizontalPadding) || 0);
  const safeVerticalPadding = Math.max(0, Number(verticalPadding) || 0);
  const maxInsetX = Math.max(0, (safeWidth - 1) * 0.5);
  const maxInsetY = Math.max(0, (safeHeight - 1) * 0.5);
  const insetX = Math.min(maxInsetX, safePointRadius + safeHorizontalPadding);
  const insetY = Math.min(maxInsetY, safePointRadius + safeVerticalPadding);
  const plotLeft = insetX;
  const plotTop = insetY;
  const plotRight = Math.max(plotLeft + 1, safeWidth - insetX);
  const plotBottom = Math.max(plotTop + 1, safeHeight - insetY);
  return {
    width: safeWidth,
    height: safeHeight,
    pointRadius: safePointRadius,
    plotLeft,
    plotTop,
    plotRight,
    plotBottom,
    plotWidth: Math.max(1, plotRight - plotLeft),
    plotHeight: Math.max(1, plotBottom - plotTop)
  };
}
function pointToMsegEditorCoordinates(point, width, height, options = {}) {
  const metrics = createMsegEditorMetrics(width, height, options);
  const orientation = options.orientation === "vertical" ? "vertical" : "horizontal";
  const normalizedX = clamp01(Number(point?.x));
  const normalizedY = clamp01(Number(point?.y));
  if (orientation === "vertical") {
    return {
      x: metrics.plotLeft + normalizedY * metrics.plotWidth,
      y: metrics.plotTop + normalizedX * metrics.plotHeight
    };
  }
  return {
    x: metrics.plotLeft + normalizedX * metrics.plotWidth,
    y: metrics.plotTop + (1 - normalizedY) * metrics.plotHeight
  };
}
function msegEditorCoordinatesToPoint(editorX, editorY, width, height, options = {}) {
  const metrics = createMsegEditorMetrics(width, height, options);
  const orientation = options.orientation === "vertical" ? "vertical" : "horizontal";
  if (orientation === "vertical") {
    return {
      x: clamp01((Number(editorY) - metrics.plotTop) / metrics.plotHeight),
      y: clamp01((Number(editorX) - metrics.plotLeft) / metrics.plotWidth)
    };
  }
  return {
    x: clamp01((Number(editorX) - metrics.plotLeft) / metrics.plotWidth),
    y: clamp01(1 - (Number(editorY) - metrics.plotTop) / metrics.plotHeight)
  };
}
function normalizeMsegLoop(loop) {
  if (!loop || typeof loop !== "object") {
    return null;
  }
  const nextLoop = objectFields(loop);
  const startX = clamp01(Number(nextLoop.startX));
  const endX = clamp01(Number(nextLoop.endX));
  if (almostEqual(startX, endX)) {
    return null;
  }
  if (endX < startX) {
    return {
      startX: endX,
      endX: startX
    };
  }
  return { startX, endX };
}
function normalizeMsegPlayback(playback = createDefaultMsegPlayback()) {
  const next = objectFields(playback);
  const rate = objectFields(next.rate);
  const seconds = Number(rate.seconds);
  const noteOffPolicyCandidate = next.noteOffPolicy;
  const noteOffPolicy = noteOffPolicyCandidate === "finish_loop" || noteOffPolicyCandidate === "immediate" || noteOffPolicyCandidate === "ignore" ? noteOffPolicyCandidate : "finish_loop";
  return {
    format: "mseg.playback",
    version: 1,
    rate: {
      kind: "seconds",
      seconds: clampMsegRateSeconds(Number.isFinite(seconds) ? seconds : 1)
    },
    loop: normalizeMsegLoop(next.loop),
    noteOffPolicy,
    legatoRestarts: Boolean(next.legatoRestarts),
    holdFinalValue: next.holdFinalValue !== false
  };
}
function normalizePoint(point, pointIndex, pointCount) {
  const nextPoint = objectFields(point);
  let x = Number(nextPoint.x);
  if (!Number.isFinite(x)) {
    x = pointIndex === 0 ? 0 : pointIndex === pointCount - 1 ? 1 : 0;
  }
  if (pointIndex !== 0 && pointIndex !== pointCount - 1) {
    x = clamp01(x);
  }
  return {
    x,
    y: clamp01(Number(nextPoint.y)),
    curvePower: clampCurvePower(Number(nextPoint.curvePower))
  };
}
function normalizeMsegShape(shape = createDefaultMsegShape()) {
  const next = objectFields(shape);
  const inputPoints = Array.isArray(next.points) ? next.points : [];
  if (inputPoints.length < 2) {
    throw new Error("MSEG shapes require at least two points");
  }
  const points = inputPoints.map((point, index) => normalizePoint(point, index, inputPoints.length));
  if (!almostEqual(points[0].x, 0) || !almostEqual(points[points.length - 1].x, 1)) {
    throw new Error("MSEG shapes must start at x = 0 and end at x = 1");
  }
  for (let index = 1; index < points.length; index += 1) {
    if (points[index].x < points[index - 1].x) {
      throw new Error("MSEG shape points must stay in non-decreasing x order");
    }
  }
  return {
    format: "mseg.shape",
    version: 1,
    name: typeof next.name === "string" && next.name.trim() ? next.name : MSEG_DEFAULT_NAME,
    globalSmooth: Boolean(next.globalSmooth),
    points
  };
}
function serializeMsegShape(shape) {
  return JSON.stringify(normalizeMsegShape(shape));
}
function deserializeMsegShape(value) {
  if (typeof value !== "string" || !value.trim()) {
    return createDefaultMsegShape();
  }
  try {
    return normalizeMsegShape(JSON.parse(value));
  } catch {
    return createDefaultMsegShape();
  }
}
function serializeMsegPlayback(playback) {
  return JSON.stringify(normalizeMsegPlayback(playback));
}
function deserializeMsegPlayback(value) {
  if (typeof value !== "string" || !value.trim()) {
    return createDefaultMsegPlayback();
  }
  try {
    return normalizeMsegPlayback(JSON.parse(value));
  } catch {
    return createDefaultMsegPlayback();
  }
}
function deserializeMsegDepth(value) {
  const numericValue = Number(value);
  return clampMsegDepth(Number.isFinite(numericValue) ? numericValue : MSEG_DEFAULT_DEPTH);
}
function powerScale(value, power) {
  if (Math.abs(power) < 0.01) {
    return value;
  }
  const numerator = Math.exp(power * value) - 1;
  const denominator = Math.exp(power) - 1;
  return numerator / denominator;
}
function evaluateMsegSegmentPoint(from, to, t) {
  const clampedT = clamp01(t);
  const curvedT = clamp01(powerScale(clampedT, from.curvePower));
  return {
    x: from.x + (to.x - from.x) * clampedT,
    y: from.y + (to.y - from.y) * curvedT,
    curvePower: from.curvePower
  };
}
function distanceSquaredToLineSegment(targetX, targetY, fromX, fromY, toX, toY) {
  const deltaX = toX - fromX;
  const deltaY = toY - fromY;
  const segmentLengthSquared = deltaX * deltaX + deltaY * deltaY;
  if (segmentLengthSquared <= 1e-12) {
    const pointDeltaX2 = targetX - fromX;
    const pointDeltaY2 = targetY - fromY;
    return pointDeltaX2 * pointDeltaX2 + pointDeltaY2 * pointDeltaY2;
  }
  const projection = clamp(
    ((targetX - fromX) * deltaX + (targetY - fromY) * deltaY) / segmentLengthSquared,
    0,
    1
  );
  const closestX = fromX + deltaX * projection;
  const closestY = fromY + deltaY * projection;
  const pointDeltaX = targetX - closestX;
  const pointDeltaY = targetY - closestY;
  return pointDeltaX * pointDeltaX + pointDeltaY * pointDeltaY;
}
function sampleMsegSegmentEditorPolyline(shape, segmentIndex, width, height, editorOptions = {}) {
  const normalizedShape = normalizeMsegShape(shape);
  if (!Number.isInteger(segmentIndex) || segmentIndex < 0 || segmentIndex >= normalizedShape.points.length - 1) {
    return [];
  }
  const from = normalizedShape.points[segmentIndex];
  const to = normalizedShape.points[segmentIndex + 1];
  const startCoordinates = pointToMsegEditorCoordinates(from, width, height, editorOptions);
  const endCoordinates = pointToMsegEditorCoordinates(to, width, height, editorOptions);
  if (almostEqual(from.x, to.x)) {
    return [startCoordinates, endCoordinates];
  }
  const polyline = [startCoordinates];
  const errorToleranceSquared = MSEG_EDITOR_CURVE_TOLERANCE_PX * MSEG_EDITOR_CURVE_TOLERANCE_PX;
  const appendAdaptiveSamples = (startT, endT, startPointCoordinates, endPointCoordinates, depth) => {
    if (depth >= MSEG_EDITOR_MAX_SUBDIVISION_DEPTH) {
      polyline.push(endPointCoordinates);
      return;
    }
    const midpointT = startT + (endT - startT) * 0.5;
    const midpoint = evaluateMsegSegmentPoint(from, to, midpointT);
    const midpointCoordinates = pointToMsegEditorCoordinates(midpoint, width, height, editorOptions);
    const errorSquared = distanceSquaredToLineSegment(
      midpointCoordinates.x,
      midpointCoordinates.y,
      startPointCoordinates.x,
      startPointCoordinates.y,
      endPointCoordinates.x,
      endPointCoordinates.y
    );
    if (errorSquared <= errorToleranceSquared) {
      polyline.push(endPointCoordinates);
      return;
    }
    appendAdaptiveSamples(startT, midpointT, startPointCoordinates, midpointCoordinates, depth + 1);
    appendAdaptiveSamples(midpointT, endT, midpointCoordinates, endPointCoordinates, depth + 1);
  };
  appendAdaptiveSamples(0, 1, startCoordinates, endCoordinates, 0);
  return polyline;
}
function sampleMsegEditorPolyline(shape, width, height, editorOptions = {}) {
  const normalizedShape = normalizeMsegShape(shape);
  const polyline = [];
  for (let segmentIndex = 0; segmentIndex < normalizedShape.points.length - 1; segmentIndex += 1) {
    const segmentPolyline = sampleMsegSegmentEditorPolyline(
      normalizedShape,
      segmentIndex,
      width,
      height,
      editorOptions
    );
    if (segmentPolyline.length === 0) {
      continue;
    }
    if (polyline.length === 0) {
      polyline.push(...segmentPolyline);
      continue;
    }
    polyline.push(...segmentPolyline.slice(1));
  }
  return polyline;
}
function findEvaluationSegment(points, x) {
  if (x <= points[0].x) {
    return { from: points[0], to: points[0], laterPointWins: false };
  }
  for (let index = 0; index < points.length - 1; index += 1) {
    const from = points[index];
    const to = points[index + 1];
    if (x < to.x) {
      return { from, to, laterPointWins: false };
    }
    if (almostEqual(x, to.x)) {
      let latestIndex = index + 1;
      while (latestIndex + 1 < points.length && almostEqual(points[latestIndex + 1].x, x)) {
        latestIndex += 1;
      }
      return {
        from: points[latestIndex],
        to: points[latestIndex],
        laterPointWins: true
      };
    }
  }
  return {
    from: points[points.length - 1],
    to: points[points.length - 1],
    laterPointWins: false
  };
}
function evaluateNormalizedMsegShape(points, x) {
  const clampedX = clamp01(Number(x));
  const segment = findEvaluationSegment(points, clampedX);
  if (segment.laterPointWins || almostEqual(segment.from.x, segment.to.x)) {
    return segment.to.y;
  }
  const width = segment.to.x - segment.from.x;
  const t = width <= 0 ? 1 : (clampedX - segment.from.x) / width;
  const curvedT = clamp01(powerScale(t, segment.from.curvePower));
  return segment.from.y + (segment.to.y - segment.from.y) * curvedT;
}
function evaluateMsegShape(shape, x) {
  return evaluateNormalizedMsegShape(normalizeMsegShape(shape).points, x);
}
function catmullRom(p0, p1, p2, p3, t) {
  return p1 + 0.5 * t * (p2 - p0 + t * (2 * p0 - 5 * p1 + 4 * p2 - p3 + t * (-p0 + 3 * p1 - 3 * p2 + p3)));
}
function renderMsegShape(shape) {
  const padded = new Float32Array(MSEG_PADDED_SAMPLES);
  renderMsegShapeInto(shape, padded);
  return padded;
}
function renderMsegShapeInto(shape, padded) {
  if (padded.length !== MSEG_PADDED_SAMPLES) throw new Error("Invalid MSEG destination length.");
  const normalizedShape = normalizeMsegShape(shape);
  for (let sampleIndex = 0; sampleIndex < MSEG_BODY_SAMPLES; sampleIndex += 1) {
    const x = sampleIndex / (MSEG_BODY_SAMPLES - 1);
    padded[sampleIndex + 1] = evaluateMsegShape(normalizedShape, x);
  }
  padded[0] = padded[1];
  padded[MSEG_BODY_SAMPLES + 1] = padded[MSEG_BODY_SAMPLES];
  padded[MSEG_BODY_SAMPLES + 2] = padded[MSEG_BODY_SAMPLES];
}
function sampleRenderedMsegBuffer(paddedBuffer, x) {
  if (!(paddedBuffer instanceof Float32Array) || paddedBuffer.length !== MSEG_PADDED_SAMPLES) {
    throw new Error(`Rendered MSEG buffers must be a Float32Array with ${MSEG_PADDED_SAMPLES} samples`);
  }
  const clampedX = clamp01(Number(x));
  const scaled = clampedX * (MSEG_BODY_SAMPLES - 1);
  const sampleIndex = Math.floor(scaled);
  const fractional = scaled - sampleIndex;
  return catmullRom(
    paddedBuffer[sampleIndex],
    paddedBuffer[sampleIndex + 1],
    paddedBuffer[sampleIndex + 2],
    paddedBuffer[sampleIndex + 3],
    fractional
  );
}
function findMsegPointHitIndex(shape, editorX, editorY, width, height, hitRadius = MSEG_POINT_HIT_RADIUS_PX, editorOptions = {}) {
  const points = normalizeMsegShape(shape).points;
  const targetX = Number(editorX);
  const targetY = Number(editorY);
  if (!Number.isFinite(targetX) || !Number.isFinite(targetY)) {
    return -1;
  }
  const safeHitRadius = Math.max(0, Number(hitRadius) || 0);
  let closestPointIndex = -1;
  let closestDistanceSquared = safeHitRadius * safeHitRadius;
  points.forEach((point, pointIndex) => {
    const coordinates = pointToMsegEditorCoordinates(point, width, height, editorOptions);
    const deltaX = targetX - coordinates.x;
    const deltaY = targetY - coordinates.y;
    const distanceSquared = deltaX * deltaX + deltaY * deltaY;
    if (distanceSquared <= closestDistanceSquared) {
      closestPointIndex = pointIndex;
      closestDistanceSquared = distanceSquared;
    }
  });
  return closestPointIndex;
}
function findMsegSegmentHitIndex(shape, editorX, editorY, width, height, hitRadius = MSEG_SEGMENT_HIT_RADIUS_PX, editorOptions = {}) {
  const normalizedShape = normalizeMsegShape(shape);
  const targetX = Number(editorX);
  const targetY = Number(editorY);
  if (!Number.isFinite(targetX) || !Number.isFinite(targetY)) {
    return -1;
  }
  const safeHitRadius = Math.max(0, Number(hitRadius) || 0);
  let closestSegmentIndex = -1;
  let closestDistanceSquared = safeHitRadius * safeHitRadius;
  for (let segmentIndex = 0; segmentIndex < normalizedShape.points.length - 1; segmentIndex += 1) {
    const polyline = sampleMsegSegmentEditorPolyline(
      normalizedShape,
      segmentIndex,
      width,
      height,
      editorOptions
    );
    for (let pointIndex = 0; pointIndex < polyline.length - 1; pointIndex += 1) {
      const from = polyline[pointIndex];
      const to = polyline[pointIndex + 1];
      const distanceSquared = distanceSquaredToLineSegment(
        targetX,
        targetY,
        from.x,
        from.y,
        to.x,
        to.y
      );
      if (distanceSquared <= closestDistanceSquared) {
        closestSegmentIndex = segmentIndex;
        closestDistanceSquared = distanceSquared;
      }
    }
  }
  return closestSegmentIndex;
}
function deriveMsegSegmentCurvePower(shape, segmentIndex, x, y) {
  const normalizedShape = normalizeMsegShape(shape);
  if (!Number.isInteger(segmentIndex) || segmentIndex < 0 || segmentIndex >= normalizedShape.points.length - 1) {
    throw new Error("segmentIndex must address a segment inside the shape");
  }
  const from = normalizedShape.points[segmentIndex];
  const to = normalizedShape.points[segmentIndex + 1];
  const width = to.x - from.x;
  const deltaY = to.y - from.y;
  if (width <= 1e-12 || Math.abs(deltaY) <= 1e-12) {
    return 0;
  }
  const localX = clamp(clamp01(Number(x)), from.x, to.x);
  const t = clamp((localX - from.x) / width, 1e-4, 1 - 1e-4);
  const targetCurvedT = clamp((Number(y) - from.y) / deltaY, 1e-4, 1 - 1e-4);
  if (!Number.isFinite(targetCurvedT) || almostEqual(targetCurvedT, t, 1e-4)) {
    return 0;
  }
  let low = -MSEG_CURVE_POWER_LIMIT;
  let high = MSEG_CURVE_POWER_LIMIT;
  let lowValue = powerScale(t, low);
  let highValue = powerScale(t, high);
  const target = clamp(targetCurvedT, Math.min(lowValue, highValue), Math.max(lowValue, highValue));
  const ascending = lowValue <= highValue;
  for (let iteration = 0; iteration < 32; iteration += 1) {
    const middle = (low + high) * 0.5;
    const middleValue = powerScale(t, middle);
    if (almostEqual(middleValue, target, 1e-5)) {
      return clampCurvePower(middle);
    }
    if (ascending && middleValue < target || !ascending && middleValue > target) {
      low = middle;
      lowValue = middleValue;
    } else {
      high = middle;
      highValue = middleValue;
    }
  }
  return clampCurvePower((low + high) * 0.5);
}
function toMsegPlaybackConfigEvent(playback) {
  const normalizedPlayback = normalizeMsegPlayback(playback);
  return {
    seconds: normalizedPlayback.rate.seconds,
    holdFinalValue: normalizedPlayback.holdFinalValue,
    rateKind: MSEG_RATE_KIND_SECONDS,
    loopEnabled: normalizedPlayback.loop !== null,
    loopStart: normalizedPlayback.loop?.startX ?? 0,
    loopEnd: normalizedPlayback.loop?.endX ?? 0,
    noteOffPolicy: normalizedPlayback.noteOffPolicy === "immediate" ? MSEG_NOTE_OFF_POLICY_IMMEDIATE : normalizedPlayback.noteOffPolicy === "ignore" ? MSEG_NOTE_OFF_POLICY_IGNORE : MSEG_NOTE_OFF_POLICY_FINISH_LOOP,
    legatoRestarts: normalizedPlayback.legatoRestarts
  };
}
function msegShapesEqual(left, right) {
  return serializeMsegShape(left) === serializeMsegShape(right);
}
function msegPlaybacksEqual(left, right) {
  return serializeMsegPlayback(left) === serializeMsegPlayback(right);
}
function addMsegPoint(shape, x, y) {
  const normalizedShape = normalizeMsegShape(shape);
  const points = normalizedShape.points.map((point) => ({ ...point }));
  const nextPoint = {
    x: clamp01(Number(x)),
    y: clamp01(Number(y)),
    curvePower: 0
  };
  let insertIndex = points.length - 1;
  while (insertIndex > 0 && points[insertIndex - 1].x > nextPoint.x) {
    insertIndex -= 1;
  }
  points.splice(insertIndex, 0, nextPoint);
  return normalizeMsegShape({
    ...normalizedShape,
    points
  });
}
function moveMsegPoint(shape, pointIndex, x, y) {
  const normalizedShape = normalizeMsegShape(shape);
  if (!Number.isInteger(pointIndex) || pointIndex < 0 || pointIndex >= normalizedShape.points.length) {
    throw new Error("pointIndex must address a point inside the shape");
  }
  const points = normalizedShape.points.map((point) => ({ ...point }));
  const previousX = pointIndex > 0 ? points[pointIndex - 1].x : 0;
  const nextX = pointIndex < points.length - 1 ? points[pointIndex + 1].x : 1;
  const moved = { ...points[pointIndex] };
  moved.y = clamp01(Number(y));
  if (pointIndex === 0) {
    moved.x = 0;
  } else if (pointIndex === points.length - 1) {
    moved.x = 1;
  } else {
    moved.x = clamp(clamp01(Number(x)), previousX, nextX);
  }
  points[pointIndex] = moved;
  return normalizeMsegShape({
    ...normalizedShape,
    points
  });
}
function deleteMsegPoint(shape, pointIndex) {
  const normalizedShape = normalizeMsegShape(shape);
  if (!Number.isInteger(pointIndex) || pointIndex < 0 || pointIndex >= normalizedShape.points.length) {
    throw new Error("pointIndex must address a point inside the shape");
  }
  if (pointIndex === 0 || pointIndex === normalizedShape.points.length - 1) {
    return normalizedShape;
  }
  const points = normalizedShape.points.filter((_, index) => index !== pointIndex);
  return normalizeMsegShape({
    ...normalizedShape,
    points
  });
}
function setMsegSegmentCurvePower(shape, segmentIndex, curvePower) {
  const normalizedShape = normalizeMsegShape(shape);
  if (!Number.isInteger(segmentIndex) || segmentIndex < 0 || segmentIndex >= normalizedShape.points.length - 1) {
    throw new Error("segmentIndex must address a segment inside the shape");
  }
  const points = normalizedShape.points.map((point) => ({ ...point }));
  points[segmentIndex].curvePower = clampCurvePower(Number(curvePower));
  return normalizeMsegShape({
    ...normalizedShape,
    points
  });
}

// ui/shared/mseg.ts
function createDefaultMsegShape2(...args) {
  return { ...createDefaultMsegShape(...args), format: "cosimo.mseg.shape" };
}
function normalizeMsegShape2(...args) {
  return { ...normalizeMsegShape(...args), format: "cosimo.mseg.shape" };
}
function deserializeMsegShape2(...args) {
  return { ...deserializeMsegShape(...args), format: "cosimo.mseg.shape" };
}
function addMsegPoint2(...args) {
  return { ...addMsegPoint(...args), format: "cosimo.mseg.shape" };
}
function moveMsegPoint2(...args) {
  return { ...moveMsegPoint(...args), format: "cosimo.mseg.shape" };
}
function deleteMsegPoint2(...args) {
  return { ...deleteMsegPoint(...args), format: "cosimo.mseg.shape" };
}
function setMsegSegmentCurvePower2(...args) {
  return { ...setMsegSegmentCurvePower(...args), format: "cosimo.mseg.shape" };
}
function createDefaultMsegPlayback2(...args) {
  return { ...createDefaultMsegPlayback(...args), format: "cosimo.mseg.playback" };
}
function normalizeMsegPlayback2(...args) {
  return { ...normalizeMsegPlayback(...args), format: "cosimo.mseg.playback" };
}
function deserializeMsegPlayback2(...args) {
  return { ...deserializeMsegPlayback(...args), format: "cosimo.mseg.playback" };
}
function serializeMsegShape2(shape) {
  return JSON.stringify(normalizeMsegShape2(shape));
}
function serializeMsegPlayback2(playback) {
  return JSON.stringify(normalizeMsegPlayback2(playback));
}
export {
  MSEG_BODY_SAMPLES,
  MSEG_CURVE_POWER_LIMIT,
  MSEG_DEFAULT_DEPTH,
  MSEG_DEFAULT_NAME,
  MSEG_EDITOR_CURVE_TOLERANCE_PX,
  MSEG_EDITOR_HORIZONTAL_PADDING_PX,
  MSEG_EDITOR_VERTICAL_PADDING_PX,
  MSEG_NOTE_OFF_POLICY_FINISH_LOOP,
  MSEG_NOTE_OFF_POLICY_IGNORE,
  MSEG_NOTE_OFF_POLICY_IMMEDIATE,
  MSEG_PADDED_SAMPLES,
  MSEG_POINT_HIT_RADIUS_PX,
  MSEG_POINT_RADIUS_PX,
  MSEG_RATE_KIND_SECONDS,
  MSEG_RATE_KIND_TEMPO,
  MSEG_RATE_MAX_SECONDS,
  MSEG_RATE_MIN_SECONDS,
  MSEG_SEGMENT_HIT_RADIUS_PX,
  MSEG_SELECTED_POINT_RADIUS_PX,
  addMsegPoint2 as addMsegPoint,
  clamp01,
  clampMsegDepth,
  clampMsegRateSeconds,
  createDefaultMsegPlayback2 as createDefaultMsegPlayback,
  createDefaultMsegShape2 as createDefaultMsegShape,
  createMsegEditorMetrics,
  createMsegTimeAxisTicks,
  deleteMsegPoint2 as deleteMsegPoint,
  deriveMsegSegmentCurvePower,
  deserializeMsegDepth,
  deserializeMsegPlayback2 as deserializeMsegPlayback,
  deserializeMsegShape2 as deserializeMsegShape,
  evaluateMsegShape,
  findMsegPointHitIndex,
  findMsegSegmentHitIndex,
  moveMsegPoint2 as moveMsegPoint,
  msegEditorCoordinatesToPoint,
  msegPlaybacksEqual,
  msegShapesEqual,
  normalizeMsegPlayback2 as normalizeMsegPlayback,
  normalizeMsegShape2 as normalizeMsegShape,
  pointToMsegEditorCoordinates,
  renderMsegShape,
  renderMsegShapeInto,
  resolveMsegSurfaceOrientation,
  sampleMsegEditorPolyline,
  sampleMsegSegmentEditorPolyline,
  sampleRenderedMsegBuffer,
  serializeMsegPlayback2 as serializeMsegPlayback,
  serializeMsegShape2 as serializeMsegShape,
  setMsegSegmentCurvePower2 as setMsegSegmentCurvePower,
  toMsegPlaybackConfigEvent
};
