// Generated from ui/shared/mseg.ts by node ui/build.mjs. Do not edit this file directly.
// kit/ui/mseg.ts
var MSEG_BODY_SAMPLES = 2048;
var MSEG_PADDED_SAMPLES = MSEG_BODY_SAMPLES + 3;
var MSEG_CURVE_POWER_LIMIT = 20;
var MSEG_DEFAULT_NAME = "MSEG 1";
function objectFields(value) {
  return value !== null && typeof value === "object" ? value : {};
}
function clamp(value, min, max) {
  return Math.min(Math.max(value, min), max);
}
function almostEqual(left, right, epsilon = 1e-12) {
  return Math.abs(left - right) <= epsilon;
}
function clampCurvePower(value) {
  return clamp(Number.isFinite(value) ? value : 0, -MSEG_CURVE_POWER_LIMIT, MSEG_CURVE_POWER_LIMIT);
}
function clamp01(value) {
  return clamp(Number.isFinite(value) ? value : 0, 0, 1);
}
function createDefaultMsegShape(name = MSEG_DEFAULT_NAME) {
  return {
    format: "mseg.shape",
    version: 1,
    name,
    globalSmooth: false,
    points: [
      { x: 0, y: 0, curvePower: 0 },
      { x: 1, y: 1, curvePower: 0 }
    ]
  };
}
function normalizePoint(point, pointIndex, pointCount) {
  const nextPoint = objectFields(point);
  let x = Number(nextPoint.x);
  if (!Number.isFinite(x)) {
    x = pointIndex === 0 ? 0 : pointIndex === pointCount - 1 ? 1 : 0;
  }
  if (pointIndex !== 0 && pointIndex !== pointCount - 1) {
    x = clamp01(x);
  }
  return {
    x,
    y: clamp01(Number(nextPoint.y)),
    curvePower: clampCurvePower(Number(nextPoint.curvePower))
  };
}
function normalizeMsegShape(shape = createDefaultMsegShape()) {
  const next = objectFields(shape);
  const inputPoints = Array.isArray(next.points) ? next.points : [];
  if (inputPoints.length < 2) {
    throw new Error("MSEG shapes require at least two points");
  }
  const points = inputPoints.map((point, index) => normalizePoint(point, index, inputPoints.length));
  if (!almostEqual(points[0].x, 0) || !almostEqual(points[points.length - 1].x, 1)) {
    throw new Error("MSEG shapes must start at x = 0 and end at x = 1");
  }
  for (let index = 1; index < points.length; index += 1) {
    if (points[index].x < points[index - 1].x) {
      throw new Error("MSEG shape points must stay in non-decreasing x order");
    }
  }
  return {
    format: "mseg.shape",
    version: 1,
    name: typeof next.name === "string" && next.name.trim() ? next.name : MSEG_DEFAULT_NAME,
    globalSmooth: Boolean(next.globalSmooth),
    points
  };
}
function addMsegPoint(shape, x, y) {
  const normalizedShape = normalizeMsegShape(shape);
  const points = normalizedShape.points.map((point) => ({ ...point }));
  const nextPoint = {
    x: clamp01(Number(x)),
    y: clamp01(Number(y)),
    curvePower: 0
  };
  let insertIndex = points.length - 1;
  while (insertIndex > 0 && points[insertIndex - 1].x > nextPoint.x) {
    insertIndex -= 1;
  }
  points.splice(insertIndex, 0, nextPoint);
  return normalizeMsegShape({
    ...normalizedShape,
    points
  });
}
function moveMsegPoint(shape, pointIndex, x, y) {
  const normalizedShape = normalizeMsegShape(shape);
  if (!Number.isInteger(pointIndex) || pointIndex < 0 || pointIndex >= normalizedShape.points.length) {
    throw new Error("pointIndex must address a point inside the shape");
  }
  const points = normalizedShape.points.map((point) => ({ ...point }));
  const previousX = pointIndex > 0 ? points[pointIndex - 1].x : 0;
  const nextX = pointIndex < points.length - 1 ? points[pointIndex + 1].x : 1;
  const moved = { ...points[pointIndex] };
  moved.y = clamp01(Number(y));
  if (pointIndex === 0) {
    moved.x = 0;
  } else if (pointIndex === points.length - 1) {
    moved.x = 1;
  } else {
    moved.x = clamp(clamp01(Number(x)), previousX, nextX);
  }
  points[pointIndex] = moved;
  return normalizeMsegShape({
    ...normalizedShape,
    points
  });
}
function deleteMsegPoint(shape, pointIndex) {
  const normalizedShape = normalizeMsegShape(shape);
  if (!Number.isInteger(pointIndex) || pointIndex < 0 || pointIndex >= normalizedShape.points.length) {
    throw new Error("pointIndex must address a point inside the shape");
  }
  if (pointIndex === 0 || pointIndex === normalizedShape.points.length - 1) {
    return normalizedShape;
  }
  const points = normalizedShape.points.filter((_, index) => index !== pointIndex);
  return normalizeMsegShape({
    ...normalizedShape,
    points
  });
}
function setMsegSegmentCurvePower(shape, segmentIndex, curvePower) {
  const normalizedShape = normalizeMsegShape(shape);
  if (!Number.isInteger(segmentIndex) || segmentIndex < 0 || segmentIndex >= normalizedShape.points.length - 1) {
    throw new Error("segmentIndex must address a segment inside the shape");
  }
  const points = normalizedShape.points.map((point) => ({ ...point }));
  points[segmentIndex].curvePower = clampCurvePower(Number(curvePower));
  return normalizeMsegShape({
    ...normalizedShape,
    points
  });
}

// ui/shared/mseg.ts
var MSEG_DEFAULT_DEPTH = 1;
var MSEG_RATE_MIN_SECONDS = 0;
var MSEG_RATE_MAX_SECONDS = 2;
var MSEG_RATE_KIND_SECONDS = 0;
var MSEG_NOTE_OFF_POLICY_FINISH_LOOP = 0;
var MSEG_NOTE_OFF_POLICY_IMMEDIATE = 1;
var MSEG_NOTE_OFF_POLICY_IGNORE = 2;
function objectFields2(value) {
  return value !== null && typeof value === "object" ? value : {};
}
function clamp2(value, min, max) {
  return Math.min(Math.max(value, min), max);
}
function createDefaultMsegShape2(...args) {
  return { ...createDefaultMsegShape(...args), format: "cosimo.mseg.shape" };
}
function normalizeMsegShape2(...args) {
  return { ...normalizeMsegShape(...args), format: "cosimo.mseg.shape" };
}
function addMsegPoint2(...args) {
  return { ...addMsegPoint(...args), format: "cosimo.mseg.shape" };
}
function moveMsegPoint2(...args) {
  return { ...moveMsegPoint(...args), format: "cosimo.mseg.shape" };
}
function deleteMsegPoint2(...args) {
  return { ...deleteMsegPoint(...args), format: "cosimo.mseg.shape" };
}
function setMsegSegmentCurvePower2(...args) {
  return { ...setMsegSegmentCurvePower(...args), format: "cosimo.mseg.shape" };
}
function serializeMsegShape(shape) {
  return JSON.stringify(normalizeMsegShape2(shape));
}
function deserializeMsegShape(value) {
  if (typeof value !== "string" || !value.trim()) {
    return createDefaultMsegShape2();
  }
  try {
    return normalizeMsegShape2(JSON.parse(value));
  } catch {
    return createDefaultMsegShape2();
  }
}
function msegShapesEqual(left, right) {
  return serializeMsegShape(left) === serializeMsegShape(right);
}
function clampMsegDepth(value) {
  return clamp2(Number.isFinite(value) ? value : 0, -1, 1);
}
function deserializeMsegDepth(value) {
  const numericValue = Number(value);
  return clampMsegDepth(Number.isFinite(numericValue) ? numericValue : MSEG_DEFAULT_DEPTH);
}
function clampMsegRateSeconds(value) {
  const numericValue = Number(value);
  return clamp2(
    Number.isFinite(numericValue) ? numericValue : 1,
    MSEG_RATE_MIN_SECONDS,
    MSEG_RATE_MAX_SECONDS
  );
}
function createDefaultMsegPlayback() {
  return {
    format: "cosimo.mseg.playback",
    version: 1,
    rate: {
      kind: "seconds",
      seconds: 1
    },
    loop: { startX: 0, endX: 1 },
    noteOffPolicy: "finish_loop",
    legatoRestarts: false,
    holdFinalValue: true
  };
}
function normalizeMsegLoop(loop) {
  if (!loop || typeof loop !== "object") {
    return null;
  }
  const nextLoop = objectFields2(loop);
  const startX = clamp01(Number(nextLoop.startX));
  const endX = clamp01(Number(nextLoop.endX));
  if (Math.abs(startX - endX) <= 1e-12) {
    return null;
  }
  return endX < startX ? { startX: endX, endX: startX } : { startX, endX };
}
function normalizeMsegPlayback(playback = createDefaultMsegPlayback()) {
  const next = objectFields2(playback);
  const rate = objectFields2(next.rate);
  const seconds = Number(rate.seconds);
  const noteOffPolicyCandidate = next.noteOffPolicy;
  const noteOffPolicy = noteOffPolicyCandidate === "finish_loop" || noteOffPolicyCandidate === "immediate" || noteOffPolicyCandidate === "ignore" ? noteOffPolicyCandidate : "finish_loop";
  return {
    format: "cosimo.mseg.playback",
    version: 1,
    rate: {
      kind: "seconds",
      seconds: clampMsegRateSeconds(Number.isFinite(seconds) ? seconds : 1)
    },
    loop: normalizeMsegLoop(next.loop),
    noteOffPolicy,
    legatoRestarts: Boolean(next.legatoRestarts),
    holdFinalValue: next.holdFinalValue !== false
  };
}
function serializeMsegPlayback(playback) {
  return JSON.stringify(normalizeMsegPlayback(playback));
}
function deserializeMsegPlayback(value) {
  if (typeof value !== "string" || !value.trim()) {
    return createDefaultMsegPlayback();
  }
  try {
    return normalizeMsegPlayback(JSON.parse(value));
  } catch {
    return createDefaultMsegPlayback();
  }
}
function msegPlaybacksEqual(left, right) {
  return serializeMsegPlayback(left) === serializeMsegPlayback(right);
}
function toMsegPlaybackConfigEvent(playback) {
  const normalizedPlayback = normalizeMsegPlayback(playback);
  return {
    seconds: normalizedPlayback.rate.seconds,
    holdFinalValue: normalizedPlayback.holdFinalValue,
    rateKind: MSEG_RATE_KIND_SECONDS,
    loopEnabled: normalizedPlayback.loop !== null,
    loopStart: normalizedPlayback.loop?.startX ?? 0,
    loopEnd: normalizedPlayback.loop?.endX ?? 0,
    noteOffPolicy: normalizedPlayback.noteOffPolicy === "immediate" ? MSEG_NOTE_OFF_POLICY_IMMEDIATE : normalizedPlayback.noteOffPolicy === "ignore" ? MSEG_NOTE_OFF_POLICY_IGNORE : MSEG_NOTE_OFF_POLICY_FINISH_LOOP,
    legatoRestarts: normalizedPlayback.legatoRestarts
  };
}
function catmullRom(p0, p1, p2, p3, t) {
  return p1 + 0.5 * t * (p2 - p0 + t * (2 * p0 - 5 * p1 + 4 * p2 - p3 + t * (-p0 + 3 * p1 - 3 * p2 + p3)));
}
function sampleRenderedMsegBuffer(paddedBuffer, x) {
  if (!(paddedBuffer instanceof Float32Array) || paddedBuffer.length !== MSEG_PADDED_SAMPLES) {
    throw new Error(`Rendered MSEG buffers must be a Float32Array with ${MSEG_PADDED_SAMPLES} samples`);
  }
  const clampedX = clamp01(Number(x));
  const scaled = clampedX * (MSEG_BODY_SAMPLES - 1);
  const sampleIndex = Math.floor(scaled);
  const fractional = scaled - sampleIndex;
  return catmullRom(
    paddedBuffer[sampleIndex],
    paddedBuffer[sampleIndex + 1],
    paddedBuffer[sampleIndex + 2],
    paddedBuffer[sampleIndex + 3],
    fractional
  );
}
export {
  MSEG_DEFAULT_DEPTH,
  MSEG_NOTE_OFF_POLICY_FINISH_LOOP,
  MSEG_NOTE_OFF_POLICY_IGNORE,
  MSEG_NOTE_OFF_POLICY_IMMEDIATE,
  MSEG_RATE_KIND_SECONDS,
  MSEG_RATE_MAX_SECONDS,
  MSEG_RATE_MIN_SECONDS,
  addMsegPoint2 as addMsegPoint,
  clampMsegDepth,
  clampMsegRateSeconds,
  createDefaultMsegPlayback,
  createDefaultMsegShape2 as createDefaultMsegShape,
  deleteMsegPoint2 as deleteMsegPoint,
  deserializeMsegDepth,
  deserializeMsegPlayback,
  deserializeMsegShape,
  moveMsegPoint2 as moveMsegPoint,
  msegPlaybacksEqual,
  msegShapesEqual,
  normalizeMsegPlayback,
  normalizeMsegShape2 as normalizeMsegShape,
  sampleRenderedMsegBuffer,
  serializeMsegPlayback,
  serializeMsegShape,
  setMsegSegmentCurvePower2 as setMsegSegmentCurvePower,
  toMsegPlaybackConfigEvent
};
