// Generated from ui/shared/oscillator-binding.ts by node ui/build.mjs. Do not edit this file directly.
import { OSCILLATOR_IDS, OSCILLATOR_MODULATION_PARAMETER_KINDS, getVoiceModulationTargetIndex, } from "./modulation-targets.js";
export { OSCILLATOR_DEFAULT_MUTE_BY_ID, OSCILLATOR_DEFAULT_VOLUME_DB, OSCILLATOR_DEFAULT_VOLUME_NORMALIZED, OSCILLATOR_VOLUME_MAX_DB, OSCILLATOR_VOLUME_MIN_DB, getOscillatorDefaultMute, } from "./oscillator-defaults.js";
const OSCILLATOR_CONTROL_DEFINITIONS = [
    {
        controlID: "wavetableSelect",
        endpointSuffix: "WavetableSelect",
        articulationParameterID: null,
    },
    {
        controlID: "framePosition",
        endpointSuffix: "WavetablePosition",
        articulationParameterID: "framePosition",
    },
    { controlID: "pan", endpointSuffix: "Pan", articulationParameterID: "pan" },
    { controlID: "octave", endpointSuffix: "Octave", articulationParameterID: "octave" },
    { controlID: "semitone", endpointSuffix: "Semitone", articulationParameterID: "semitone" },
    { controlID: "fineCents", endpointSuffix: "FineCents", articulationParameterID: "fineCents" },
    { controlID: "phase", endpointSuffix: "Phase", articulationParameterID: "phase" },
    {
        controlID: "phaseRandom",
        endpointSuffix: "PhaseRandom",
        articulationParameterID: "phaseRandom",
    },
    { controlID: "retrigger", endpointSuffix: "Retrigger", articulationParameterID: "retrigger" },
    { controlID: "volumeDb", endpointSuffix: "VolumeDb", articulationParameterID: "volumeDb" },
    { controlID: "mute", endpointSuffix: "Mute", articulationParameterID: "mute" },
    { controlID: "solo", endpointSuffix: "Solo", articulationParameterID: "solo" },
    { controlID: "warpMode", endpointSuffix: "WarpMode", articulationParameterID: "warpMode" },
    { controlID: "warpAmount", endpointSuffix: "WarpAmount", articulationParameterID: "warpAmount" },
    {
        controlID: "unisonVoices",
        endpointSuffix: "UnisonVoices",
        articulationParameterID: "unisonVoices",
    },
    {
        controlID: "unisonDetune",
        endpointSuffix: "UnisonDetune",
        articulationParameterID: "unisonDetune",
    },
    {
        controlID: "unisonBlend",
        endpointSuffix: "UnisonBlend",
        articulationParameterID: "unisonBlend",
    },
    {
        controlID: "unisonWidth",
        endpointSuffix: "UnisonWidth",
        articulationParameterID: "unisonWidth",
    },
    {
        controlID: "unisonDetuneMode",
        endpointSuffix: "UnisonDetuneMode",
        articulationParameterID: "unisonDetuneMode",
    },
    {
        controlID: "unisonStackMode",
        endpointSuffix: "UnisonStackMode",
        articulationParameterID: "unisonStackMode",
    },
    {
        controlID: "unisonWavetablePositionSpread",
        endpointSuffix: "UnisonPositionSpread",
        articulationParameterID: "unisonWavetablePositionSpread",
    },
    {
        controlID: "unisonWarpSpread",
        endpointSuffix: "UnisonWarpSpread",
        articulationParameterID: "unisonWarpSpread",
    },
];
const OSCILLATOR_RUNTIME_IDENTITIES = [
    { id: "A", oscillatorIndex: 0 },
    { id: "B", oscillatorIndex: 1 },
    { id: "C", oscillatorIndex: 2 },
];
function uiTargetIDSuffix(parameterKind) {
    switch (parameterKind) {
        case "wavetablePosition": return "framePosition";
        case "ampGainDb": return "volumeDb";
        case "warpAmount":
        case "pitchSemitones":
        case "pan":
        case "unisonDetune":
        case "unisonBlend":
        case "unisonWidth":
        case "unisonWavetablePositionSpread":
        case "unisonWarpSpread":
            return parameterKind;
    }
}
function createControlAddress(oscillatorID, oscillatorIndex, definition) {
    const articulationParameterID = definition.articulationParameterID === null
        ? null
        : `osc${oscillatorID}.${definition.articulationParameterID}`;
    return Object.freeze({
        controlID: definition.controlID,
        // SAFETY: both interpolated pieces come from closed unions above, so
        // their concatenation is exactly one OscillatorControlEndpointID.
        endpointID: `osc${oscillatorID}${definition.endpointSuffix}`,
        oscillatorIndex,
        articulationParameterID,
    });
}
function createModulationAddress(oscillatorID, oscillatorIndex, parameterKind) {
    const targetKind = `osc${oscillatorID}.${parameterKind}`;
    return Object.freeze({
        parameterKind,
        targetKind,
        // SAFETY: the oscillator and target suffix are both closed canonical
        // unions, so the interpolated ID belongs to the UI target domain.
        uiTargetID: `osc${oscillatorID}.${uiTargetIDSuffix(parameterKind)}`,
        runtimeTargetIndex: getVoiceModulationTargetIndex(targetKind),
        oscillatorIndex,
    });
}
function createBindingContract(id, oscillatorIndex) {
    const controls = Object.freeze(OSCILLATOR_CONTROL_DEFINITIONS.map((definition) => createControlAddress(id, oscillatorIndex, definition)));
    const modulationTargets = Object.freeze(OSCILLATOR_MODULATION_PARAMETER_KINDS.map((parameterKind) => createModulationAddress(id, oscillatorIndex, parameterKind)));
    const articulationParameterIDs = Object.freeze(controls.flatMap((control) => control.articulationParameterID === null ? [] : [control.articulationParameterID]));
    return Object.freeze({
        id,
        oscillatorIndex,
        tableStatus: Object.freeze({ endpointID: "runtimeState", oscillatorIndex }),
        controls,
        modulationTargets,
        articulationParameterIDs,
    });
}
/** The canonical A/B/C contracts in frozen runtime order. */
export const OSCILLATOR_BINDING_CONTRACTS = Object.freeze(OSCILLATOR_RUNTIME_IDENTITIES.map(({ id, oscillatorIndex }) => createBindingContract(id, oscillatorIndex)));
/** The presentation-only initial tab; it is deliberately not stored with patch values. */
export const DEFAULT_SELECTED_OSCILLATOR_ID = "A";
function assertBindingContracts() {
    if (OSCILLATOR_BINDING_CONTRACTS.length !== OSCILLATOR_IDS.length
        || OSCILLATOR_BINDING_CONTRACTS.some((contract, index) => (contract.id !== OSCILLATOR_IDS[index] || contract.oscillatorIndex !== index))) {
        throw new Error("Oscillator binding contracts must match frozen A/B/C runtime order");
    }
    const endpointIDs = OSCILLATOR_BINDING_CONTRACTS.flatMap((contract) => contract.controls.map((control) => control.endpointID));
    if (new Set(endpointIDs).size !== endpointIDs.length) {
        throw new Error("Oscillator control endpoint IDs must be unique");
    }
}
assertBindingContracts();
/** Resolve one oscillator's complete shared contract without accepting aliases. */
export function getOscillatorBindingContract(oscillatorID) {
    const contract = OSCILLATOR_BINDING_CONTRACTS.find((candidate) => candidate.id === oscillatorID);
    if (contract === undefined)
        throw new Error(`Unknown oscillator identity: ${oscillatorID}`);
    return contract;
}
/** Resolve one control address inside an oscillator contract. */
export function getOscillatorControlAddress(oscillatorID, controlID) {
    const control = getOscillatorBindingContract(oscillatorID).controls.find((candidate) => candidate.controlID === controlID);
    if (control === undefined)
        throw new Error(`Unknown oscillator control: ${oscillatorID}.${controlID}`);
    return control;
}
/**
 * Project a user edit through the selected oscillator contract. This is the
 * single write-routing seam for later desktop/iPhone host adapters.
 */
export function projectSelectedOscillatorWrite(selectedOscillatorID, controlID, value) {
    const address = getOscillatorControlAddress(selectedOscillatorID, controlID);
    return Object.freeze({
        oscillatorID: selectedOscillatorID,
        oscillatorIndex: address.oscillatorIndex,
        controlID,
        endpointID: address.endpointID,
        value,
    });
}
