// Generated from ui/shared/wavetable-bank.ts by node ui/build.mjs. Do not edit this file directly.
// kit/ui/resource-client.ts
function fail(message) {
  throw new Error(message);
}
function readAscii(view, offset, length) {
  let text = "";
  for (let index = 0; index < length; index += 1) text += String.fromCharCode(view.getUint8(offset + index));
  return text;
}
function decodeText(bytes) {
  return typeof TextDecoder === "function" ? new TextDecoder().decode(bytes) : String.fromCharCode(...bytes);
}
function encodeText(text) {
  return typeof TextEncoder === "function" ? new TextEncoder().encode(text) : Uint8Array.from(text, (character) => character.charCodeAt(0));
}
function bytesFromPayload(path, payload) {
  if (typeof payload === "string") return encodeText(payload);
  if (payload instanceof ArrayBuffer) return new Uint8Array(payload.slice(0));
  if (ArrayBuffer.isView(payload)) return new Uint8Array(payload.buffer.slice(payload.byteOffset, payload.byteOffset + payload.byteLength));
  if (Array.isArray(payload)) return Uint8Array.from(payload);
  return fail(`The host returned ${path} in a form this kit cannot read.`);
}
function parseMonoWave(path, buffer) {
  const view = new DataView(buffer);
  if (view.byteLength < 12 || readAscii(view, 0, 4) !== "RIFF" || readAscii(view, 8, 4) !== "WAVE")
    fail(`${path} is not a WAV file.`);
  let format = 0, channels = 0, sampleRate = 0, bitsPerSample = 0, dataOffset = -1, dataSize = 0;
  for (let cursor = 12; cursor + 8 <= view.byteLength; ) {
    const chunk = readAscii(view, cursor, 4), size = view.getUint32(cursor + 4, true), body = cursor + 8;
    if (chunk === "fmt ") {
      format = view.getUint16(body, true);
      channels = view.getUint16(body + 2, true);
      sampleRate = view.getUint32(body + 4, true);
      bitsPerSample = view.getUint16(body + 14, true);
    } else if (chunk === "data") {
      dataOffset = body;
      dataSize = Math.min(size, view.byteLength - body);
    }
    cursor = body + size + size % 2;
  }
  if (dataOffset < 0 || format === 0) fail(`${path} is missing its WAV format or data chunk.`);
  if (channels !== 1) fail(`${path} has ${channels} channels; readAudio reads mono WAV files only.`);
  const data = buffer.slice(dataOffset, dataOffset + dataSize);
  if (format === 3 && bitsPerSample === 32) return { sampleRate, samples: new Float32Array(data, 0, Math.floor(dataSize / 4)) };
  if (format === 1 && bitsPerSample === 16) {
    const pcm = new Int16Array(data, 0, Math.floor(dataSize / 2));
    return { sampleRate, samples: Float32Array.from(pcm, (sample) => sample / 32768) };
  }
  return fail(`${path} uses WAV format ${format} at ${bitsPerSample} bits; use 16-bit PCM or 32-bit float.`);
}
function decodedAudio(path, input) {
  const decoded = input ?? {};
  const frames = decoded.frames;
  if (!frames || typeof frames.length !== "number") fail(`The host decoded ${path} without audio frames.`);
  const samples = new Float32Array(frames.length);
  for (let index = 0; index < frames.length; index += 1) {
    const frame = frames[index];
    if (typeof frame === "number") samples[index] = frame;
    else if (frame && frame.length === 1) samples[index] = Number(frame[0]) || 0;
    else fail(`${path} is not mono; readAudio reads mono audio only.`);
  }
  return { sampleRate: Number(decoded.sampleRate) || 0, samples };
}
function defaultPatchRoot() {
  const page = globalThis.location?.href;
  if (typeof page === "string" && page.length > 0) return new URL("/", page);
  const folder = new URL(import.meta.url);
  folder.pathname = folder.pathname.replace(/\/[^/]*$/, "/");
  return folder;
}
function resourceURL(path, address, patchRoot) {
  if (address instanceof URL) return address;
  if (typeof address === "string" && address.length > 0)
    return /^[a-zA-Z][a-zA-Z\d+.-]*:/.test(address) ? new URL(address) : new URL(address.replace(/^\//, ""), patchRoot);
  return new URL(path, patchRoot);
}
function createPatchConnectionResourceClient(source, options = {}) {
  const host = source ?? {};
  const patchRoot = options.patchRoot ?? defaultPatchRoot();
  const fetchBuffer = async (path, address = host.getResourceAddress?.(path)) => {
    if (typeof fetch !== "function") fail(`Cannot read ${path}: this host has neither a resource bridge nor fetch.`);
    const url = resourceURL(path, address, patchRoot);
    const response = await fetch(url.toString());
    if (!response.ok) fail(`Could not read ${path} from ${url} (HTTP ${response.status}).`);
    return response.arrayBuffer();
  };
  const readBytes = async (path) => host.readResource ? bytesFromPayload(path, await host.readResource(path)) : new Uint8Array(await fetchBuffer(path));
  return {
    async readText(path) {
      if (!host.readResource) return decodeText(new Uint8Array(await fetchBuffer(path)));
      const payload = await host.readResource(path);
      if (typeof payload === "string") return payload;
      if (typeof payload === "object" && payload !== null && "text" in payload && typeof payload.text === "function")
        return String(await payload.text());
      return decodeText(bytesFromPayload(path, payload));
    },
    async readJSON(path) {
      return JSON.parse(await this.readText(path));
    },
    readBytes,
    async readAudio(path) {
      const address = host.getResourceAddress?.(path);
      if (address !== void 0 && address !== null && typeof fetch === "function") return parseMonoWave(path, await fetchBuffer(path, address));
      if (host.readResourceAsAudioData) return decodedAudio(path, await host.readResourceAsAudioData(path));
      return parseMonoWave(path, new Uint8Array(await readBytes(path)).buffer);
    },
    getURL(path) {
      return resourceURL(path, host.getResourceAddress?.(path), patchRoot);
    }
  };
}

// ui/shared/wavetable-bank.ts
var DEFAULT_SAMPLES_PER_FRAME = 2048;
var DEFAULT_FACTORY_BANK_CATALOG_PATH = "assets/factory-bank-catalog.json";
var DEFAULT_FACTORY_TABLE_INDEX = 34;
function assert(condition, message) {
  if (!condition) {
    throw new Error(message);
  }
}
function clampToRange(value, min, max) {
  return Math.min(Math.max(value, min), max);
}
function canonicalizeFrame(frame) {
  let sum = 0;
  for (let index = 0; index < frame.length; index += 1) {
    sum += Number(frame[index]) || 0;
  }
  const mean = sum / Math.max(1, frame.length);
  const canonical = new Float32Array(frame.length);
  for (let index = 0; index < frame.length; index += 1) {
    canonical[index] = (Number(frame[index]) || 0) - mean;
  }
  return canonical;
}
function getFactoryBankCatalogValue(catalogValue) {
  assert(
    Array.isArray(catalogValue?.tables),
    "Factory bank catalog must provide a tables array"
  );
  const catalog = catalogValue;
  catalog.tables.forEach((table, tableIndex) => {
    assert(
      typeof table?.tableId === "string" && table.tableId.length > 0,
      `Factory bank catalog table ${tableIndex} must provide tableId`
    );
    assert(
      typeof table?.name === "string" && table.name.length > 0,
      `Factory bank catalog table ${tableIndex} must provide name`
    );
    assert(
      Number.isInteger(Number(table?.frameCount)) && Number(table.frameCount) > 0,
      `Factory bank catalog table ${tableIndex} must provide a positive frameCount`
    );
    assert(
      typeof table?.sourceWav === "string" && table.sourceWav.length > 0,
      `Factory bank catalog table ${tableIndex} must provide sourceWav`
    );
  });
  return catalog;
}
function extractSourceFrames(samples, {
  expectedFrameCount,
  samplesPerFrame = DEFAULT_SAMPLES_PER_FRAME
} = {}) {
  assert(
    samples.length % samplesPerFrame === 0,
    `Source wavetable files must contain a whole number of ${samplesPerFrame}-sample frames`
  );
  const frameCount = samples.length / samplesPerFrame;
  assert(frameCount > 0, "Source wavetable files must contain at least one frame");
  if (expectedFrameCount !== void 0) {
    assert(
      frameCount === expectedFrameCount,
      `Source wavetable frame count mismatch: expected ${expectedFrameCount}, got ${frameCount}`
    );
  }
  const frames = [];
  for (let frameIndex = 0; frameIndex < frameCount; frameIndex += 1) {
    const start = frameIndex * samplesPerFrame;
    const end = start + samplesPerFrame;
    frames.push(canonicalizeFrame(samples.slice(start, end)));
  }
  return {
    frameCount,
    frames
  };
}
async function loadFactoryBankCatalog(resourceClient, {
  catalogPath = DEFAULT_FACTORY_BANK_CATALOG_PATH
} = {}) {
  return getFactoryBankCatalogValue(await resourceClient.readJSON(catalogPath));
}
async function loadFactoryBankFrames(resourceClient, {
  catalogPath = DEFAULT_FACTORY_BANK_CATALOG_PATH,
  tableIndex = 0,
  samplesPerFrame = DEFAULT_SAMPLES_PER_FRAME
} = {}) {
  const catalogValue = await loadFactoryBankCatalog(resourceClient, { catalogPath });
  const clampedTableIndex = clampToRange(tableIndex, 0, catalogValue.tables.length - 1);
  const sourceTableMeta = catalogValue.tables[clampedTableIndex];
  const sourceAudio = await resourceClient.readAudio(sourceTableMeta.sourceWav);
  const sourceFrames = extractSourceFrames(sourceAudio.samples, {
    expectedFrameCount: Number(sourceTableMeta.frameCount),
    samplesPerFrame
  });
  return {
    sampleRate: sourceAudio.sampleRate,
    sampleBlobPath: sourceTableMeta.sourceWav,
    tableIndex: clampedTableIndex,
    frameCount: sourceFrames.frameCount,
    samples: sourceAudio.samples,
    frames: sourceFrames.frames
  };
}
function loadFactoryBankCatalogFromPatch(patchConnection) {
  return loadFactoryBankCatalog(createPatchConnectionResourceClient(patchConnection));
}
function loadFactoryBankFramesFromPatch(patchConnection, options = {}) {
  return loadFactoryBankFrames(createPatchConnectionResourceClient(patchConnection), options);
}
export {
  DEFAULT_FACTORY_BANK_CATALOG_PATH,
  DEFAULT_FACTORY_TABLE_INDEX,
  DEFAULT_SAMPLES_PER_FRAME,
  getFactoryBankCatalogValue,
  loadFactoryBankCatalog,
  loadFactoryBankCatalogFromPatch,
  loadFactoryBankFrames,
  loadFactoryBankFramesFromPatch
};
