// Generated from ui/desktop/standalone-loader.js by node ui/build.mjs. Do not edit this file directly.
const DEFAULT_DESKTOP_UI_SOURCE_MODE = "compiled";
const DEFAULT_DESKTOP_DEV_SERVER_ORIGIN = "http://127.0.0.1:5174";
const DESKTOP_DEV_SERVER_MODULE_PATH = "/patch_gui/desktop/index.js";
const OPEN_IN_EDITOR_PATH = "/__open-in-editor";
const FETCH_BRIDGE_MARKER = Symbol.for("cosimo.desktopDevServerFetchBridge");
const DESKTOP_UI_SOURCE_MODE_KEY = "__COSIMO_DESKTOP_UI_SOURCE_MODE__";
const DESKTOP_DEV_SERVER_ORIGIN_KEY = "__COSIMO_DESKTOP_DEV_SERVER_ORIGIN__";
export function getDesktopUISourceMode(globalObject = globalThis) {
    const mode = typeof globalObject?.[DESKTOP_UI_SOURCE_MODE_KEY] === "string"
        ? globalObject[DESKTOP_UI_SOURCE_MODE_KEY].trim()
        : "";
    return mode || DEFAULT_DESKTOP_UI_SOURCE_MODE;
}
function normalizeDevServerOrigin(devServerOrigin) {
    const origin = typeof devServerOrigin === "string"
        ? devServerOrigin.trim()
        : "";
    return (origin || DEFAULT_DESKTOP_DEV_SERVER_ORIGIN).replace(/\/+$/, "");
}
export function getDesktopDevServerOrigin(globalObject = globalThis) {
    return normalizeDevServerOrigin(globalObject?.[DESKTOP_DEV_SERVER_ORIGIN_KEY]);
}
export function buildDesktopDevServerModuleUrl(devServerOrigin = getDesktopDevServerOrigin()) {
    return `${normalizeDevServerOrigin(devServerOrigin)}${DESKTOP_DEV_SERVER_MODULE_PATH}`;
}
export function buildDesktopCompiledModuleUrl(baseUrl = import.meta.url) {
    return new URL("./app.js", baseUrl).href;
}
function rewriteOpenInEditorRequest(input, devServerOrigin) {
    const normalizedOrigin = normalizeDevServerOrigin(devServerOrigin);
    if (typeof input === "string") {
        if (!input.startsWith(`${OPEN_IN_EDITOR_PATH}?`) && input !== OPEN_IN_EDITOR_PATH) {
            return input;
        }
        return `${normalizedOrigin}${input}`;
    }
    if (input instanceof URL) {
        if (input.pathname !== OPEN_IN_EDITOR_PATH) {
            return input;
        }
        return new URL(`${input.pathname}${input.search}`, normalizedOrigin).href;
    }
    if (input instanceof Request) {
        const requestUrl = new URL(input.url);
        if (requestUrl.pathname !== OPEN_IN_EDITOR_PATH) {
            return input;
        }
        return new Request(new URL(`${requestUrl.pathname}${requestUrl.search}`, normalizedOrigin), input);
    }
    return input;
}
export function createOpenInEditorDevServerFetchBridge(fetchImpl, devServerOrigin = getDesktopDevServerOrigin()) {
    return async function fetchWithOpenInEditorBridge(input, init) {
        return await fetchImpl(rewriteOpenInEditorRequest(input, devServerOrigin), init);
    };
}
export function installOpenInEditorDevServerFetchBridge({ devServerOrigin = getDesktopDevServerOrigin(), globalObject = globalThis, } = {}) {
    if (typeof globalObject.fetch !== "function") {
        return false;
    }
    if (globalObject.fetch[FETCH_BRIDGE_MARKER]) {
        return false;
    }
    const wrappedFetch = createOpenInEditorDevServerFetchBridge(globalObject.fetch.bind(globalObject), devServerOrigin);
    wrappedFetch[FETCH_BRIDGE_MARKER] = true;
    globalObject.fetch = wrappedFetch;
    return true;
}
export async function loadDesktopPatchViewModule({ mode = getDesktopUISourceMode(), devServerModuleUrl = buildDesktopDevServerModuleUrl(), compiledModuleUrl = buildDesktopCompiledModuleUrl(), importModule = async (specifier) => await import(specifier), onDevServerModuleLoaded = ({ devServerOrigin }) => installOpenInEditorDevServerFetchBridge({ devServerOrigin }), } = {}) {
    switch (mode) {
        case "dev-server": {
            const devServerModule = await importModule(devServerModuleUrl);
            await onDevServerModuleLoaded?.({
                devServerModuleUrl,
                devServerOrigin: new URL(devServerModuleUrl).origin,
                module: devServerModule,
            });
            return devServerModule;
        }
        case "compiled":
            return await importModule(compiledModuleUrl);
        default:
            throw new Error(`Unsupported desktop UI source mode: ${mode}`);
    }
}
export async function createDesktopPatchView(...args) {
    const desktopPatchViewModule = await loadDesktopPatchViewModule();
    if (typeof desktopPatchViewModule.createDesktopPatchView === "function") {
        return desktopPatchViewModule.createDesktopPatchView(...args);
    }
    return desktopPatchViewModule.default(...args);
}
export default async function createPatchView(...args) {
    const desktopPatchViewModule = await loadDesktopPatchViewModule();
    return await desktopPatchViewModule.default(...args);
}
