import defaultSource from "./default.tsx?raw";
import scalesSource from "./scales.tsx?raw";
import entrySource from "./entry.tsx?raw";
import liveSource from "./live.tsx?raw";
import twoAxisSource from "./two-axis.tsx?raw";
import menuSource from "./menu.tsx?raw";
import customSource from "./custom.tsx?raw";
import stylesSource from "./styles.tsx?raw";
import statesSource from "./states.tsx?raw";
import horizontalSource from "./horizontal.tsx?raw";
import gesturesSource from "./gestures.tsx?raw";
import exampleStyles from "./examples.css?raw";
export const exampleSources: Record<string, string> = { "default": defaultSource, "scales": scalesSource, "entry": entrySource, "live": liveSource, "two-axis": twoAxisSource, "menu": menuSource, "custom": customSource, "styles": stylesSource, "states": statesSource, "horizontal": horizontalSource, "gestures": gesturesSource };
export { exampleStyles };
