#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
output_dir="${1:-$repo_root/build/ios_auv3/generated/cmajor}"
default_patch_path="$repo_root/WavetableSynth.iOS.cmajorpatch"
generated_marker_filename=".cosimo-ios-auv3-generated"

if [[ ! -f "$default_patch_path" ]]; then
  default_patch_path="$repo_root/WavetableSynth.cmajorpatch"
fi

patch_path="${2:-$default_patch_path}"
resolved_output_dir="$(python3 - "$output_dir" <<'PY'
import os
import sys

print(os.path.realpath(sys.argv[1]))
PY
)"

case "$resolved_output_dir" in
  ""|"/"|"$repo_root")
    printf 'Refusing to overwrite unsafe output directory: %s\n' "$resolved_output_dir" >&2
    exit 1
    ;;
esac

if [[ "$resolved_output_dir" != "$repo_root"/* && "$resolved_output_dir" != */generated/cmajor ]]; then
  printf 'Refusing to write outside the repo workspace unless the path ends with generated/cmajor: %s\n' "$resolved_output_dir" >&2
  exit 1
fi

output_dir="$resolved_output_dir"
output_parent="$(dirname "$output_dir")"

if ! command -v cmaj >/dev/null 2>&1; then
  printf 'cmaj is required to generate the raw iOS performer source.\n' >&2
  exit 1
fi

if ! command -v npm >/dev/null 2>&1; then
  printf 'npm is required to build the generated patch_gui JavaScript files.\n' >&2
  exit 1
fi

if [[ ! -f "$patch_path" ]]; then
  printf 'Patch file not found: %s\n' "$patch_path" >&2
  exit 1
fi

mkdir -p "$output_parent"

(
  cd "$repo_root"
  npm run ui:build
)
(
  cd "$repo_root"
  uv run python build_assets.py
)

temp_dir="$(mktemp -d "${TMPDIR:-/tmp}/cosimo-ios-auv3.XXXXXX")"
cleanup() {
  rm -rf "$temp_dir"
}
trap cleanup EXIT

generated_dir="$temp_dir/generated"
generated_cpp="$generated_dir/WavetableSynth.cpp"

mkdir -p "$generated_dir"

cmaj generate --target=cpp "$patch_path" --output="$generated_cpp"

touch "$generated_dir/$generated_marker_filename"

if [[ -e "$output_dir" ]]; then
  if [[ ! -d "$output_dir" ]]; then
    printf 'Refusing to overwrite non-directory output path: %s\n' "$output_dir" >&2
    exit 1
  fi

  if [[ -z "$(find "$output_dir" -mindepth 1 -maxdepth 1 -print -quit)" ]]; then
    rm -rf "$output_dir"
  elif [[ -f "$output_dir/$generated_marker_filename" ]]; then
    rm -rf "$output_dir"
  else
    printf 'Refusing to overwrite a non-empty directory that was not generated by this script: %s\n' "$output_dir" >&2
    exit 1
  fi
fi

mv "$generated_dir" "$output_dir"

printf 'Generated raw iOS performer source at %s\n' "$output_dir"
