import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import typescript from "typescript";
import { build, loadConfigFromFile } from "vite";

const thisDirectory = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(thisDirectory, "..");
const buildTargets = new Set(process.argv.slice(2));

function shouldBuild(targetName) {
    return buildTargets.size === 0 || buildTargets.has(targetName) || buildTargets.has("--all");
}

async function writeTextFileIfChanged(filePath, contents) {
    const normalizedContents = contents.replace(/\r\n/g, "\n");

    try {
        const existingContents = await fs.readFile(filePath, "utf8");

        if (existingContents === normalizedContents) {
            return;
        }
    } catch (error) {
        if (error?.code !== "ENOENT") {
            throw error;
        }
    }

    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, normalizedContents, "utf8");
}

async function copyTextFileIfChanged(sourceRelativePath, outputRelativePath) {
    const sourceFile = path.join(repoRoot, sourceRelativePath);
    const outputFile = path.join(repoRoot, outputRelativePath);
    const sourceText = await fs.readFile(sourceFile, "utf8");
    await writeTextFileIfChanged(outputFile, sourceText);
}

async function emitGeneratedPatchGuiModule(sourceRelativePath, outputRelativePath) {
    const sourceFile = path.join(repoRoot, sourceRelativePath);
    const outputFile = path.join(repoRoot, outputRelativePath);
    const sourceText = await fs.readFile(sourceFile, "utf8");
    const transpiled = typescript.transpileModule(sourceText, {
        compilerOptions: {
            target: typescript.ScriptTarget.ES2022,
            module: typescript.ModuleKind.ESNext,
            newLine: typescript.NewLineKind.LineFeed,
        },
        fileName: sourceFile,
        reportDiagnostics: true,
    });

    if ((transpiled.diagnostics?.length ?? 0) > 0) {
        const message = typescript.formatDiagnosticsWithColorAndContext(
            transpiled.diagnostics,
            {
                getCanonicalFileName: (fileName) => fileName,
                getCurrentDirectory: () => repoRoot,
                getNewLine: () => "\n",
            },
        );

        throw new Error(`Could not generate ${outputRelativePath} from ${sourceRelativePath}\n${message}`);
    }

    const rewrittenOutputText = transpiled.outputText.replace(
        /(from\s+["']|import\(\s*["'])(\.\.?\/[^"']+)(["']\s*\)?)/g,
        (match, prefix, specifier, suffix) => (
            path.posix.extname(specifier) ? match : `${prefix}${specifier}.js${suffix}`
        ),
    );
    const generatedSource = [
        `// Generated from ${sourceRelativePath} by node ui/build.mjs. Do not edit this file directly.`,
        rewrittenOutputText.trimEnd(),
        "",
    ].join("\n");

    await writeTextFileIfChanged(outputFile, generatedSource);
}

async function runBuild(configRelativePath) {
    const configFile = path.resolve(thisDirectory, configRelativePath);
    const loadedConfig = await loadConfigFromFile(
        { command: "build", mode: "production" },
        configFile,
    );

    if (!loadedConfig) {
        throw new Error(`Could not load Vite config ${configFile}`);
    }

    await build(loadedConfig.config);
}

if (shouldBuild("--desktop") || shouldBuild("--ios")) {
    await emitGeneratedPatchGuiModule("ui/shared/resource-client.ts", "patch_gui/resource-client.js");
    await emitGeneratedPatchGuiModule("ui/shared/mseg.ts", "patch_gui/mseg.js");
    await emitGeneratedPatchGuiModule("ui/shared/mseg-controller.ts", "patch_gui/mseg-controller.js");
    await emitGeneratedPatchGuiModule("ui/shared/modulation.ts", "patch_gui/modulation.js");
}

if (shouldBuild("--ios")) {
    await copyTextFileIfChanged("ui/ios/runtime-shell.html", "patch_gui/index.ios.html");
    await emitGeneratedPatchGuiModule("ui/ios/runtime-host.js", "patch_gui/index.ios-host.js");
    await runBuild("../ios_auv3/vite.config.mjs");
    await runBuild("./vite.worker.config.mjs");
}

if (shouldBuild("--desktop")) {
    await runBuild("./vite.desktop.config.mjs");
    await emitGeneratedPatchGuiModule("ui/desktop/standalone-loader.js", "patch_gui/desktop/index.js");
}
