import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import typescript from "typescript";
import { build as bundleModule } from "esbuild";
import { build, loadConfigFromFile } from "vite";

const thisDirectory = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(thisDirectory, "..");
const buildTargets = new Set(process.argv.slice(2));

function shouldBuild(targetName) {
    return buildTargets.size === 0 || buildTargets.has(targetName) || buildTargets.has("--all");
}

async function writeTextFileIfChanged(filePath, contents) {
    const normalizedContents = contents.replace(/\r\n/g, "\n");

    try {
        const existingContents = await fs.readFile(filePath, "utf8");

        if (existingContents === normalizedContents) {
            return;
        }
    } catch (error) {
        if (error?.code !== "ENOENT") {
            throw error;
        }
    }

    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, normalizedContents, "utf8");
}

async function copyTextFileIfChanged(sourceRelativePath, outputRelativePath) {
    const sourceFile = path.join(repoRoot, sourceRelativePath);
    const outputFile = path.join(repoRoot, outputRelativePath);
    const sourceText = await fs.readFile(sourceFile, "utf8");
    await writeTextFileIfChanged(outputFile, sourceText);
}

const kitRoot = path.join(repoRoot, "kit");

function withJsExtension(specifier) {
    return path.posix.extname(specifier) ? specifier : `${specifier}.js`;
}

function importsKitCode(moduleText, sourceFile) {
    return [...moduleText.matchAll(/(?:from\s+["']|import\(\s*["'])(\.\.?\/[^"']+)["']/g)]
        .some(([, specifier]) => path.resolve(path.dirname(sourceFile), specifier).startsWith(kitRoot + path.sep));
}

/**
 * Each synth module becomes one patch_gui module whose relative imports name
 * its patch_gui siblings. patch_gui has no kit tree, so a module that uses kit
 * code is bundled with that code inlined while its synth imports stay siblings.
 */
async function emitGeneratedPatchGuiModule(sourceRelativePath, outputRelativePath) {
    const sourceFile = path.join(repoRoot, sourceRelativePath);
    const outputFile = path.join(repoRoot, outputRelativePath);
    const header = `// Generated from ${sourceRelativePath} by node ui/build.mjs. Do not edit this file directly.`;
    const transpiled = typescript.transpileModule(await fs.readFile(sourceFile, "utf8"), {
        compilerOptions: {
            target: typescript.ScriptTarget.ES2022,
            module: typescript.ModuleKind.ESNext,
            newLine: typescript.NewLineKind.LineFeed,
        },
        fileName: sourceFile,
        reportDiagnostics: true,
    });

    if ((transpiled.diagnostics?.length ?? 0) > 0) {
        const message = typescript.formatDiagnosticsWithColorAndContext(
            transpiled.diagnostics,
            {
                getCanonicalFileName: (fileName) => fileName,
                getCurrentDirectory: () => repoRoot,
                getNewLine: () => "\n",
            },
        );

        throw new Error(`Could not generate ${outputRelativePath} from ${sourceRelativePath}\n${message}`);
    }

    if (importsKitCode(transpiled.outputText, sourceFile)) {
        const result = await bundleModule({
            entryPoints: [sourceFile], bundle: true, write: false, format: "esm", platform: "browser", target: "es2022",
            plugins: [{
                name: "synth-siblings",
                setup(builder) {
                    builder.onResolve({ filter: /^\.\.?\// }, ({ path: specifier, resolveDir }) => (
                        path.resolve(resolveDir, specifier).startsWith(kitRoot + path.sep)
                            ? undefined
                            : { path: withJsExtension(specifier), external: true }
                    ));
                },
            }],
        });
        await writeTextFileIfChanged(outputFile, `${header}\n${result.outputFiles[0].text}`);
        return;
    }

    const rewrittenOutputText = transpiled.outputText.replace(
        /(from\s+["']|import\(\s*["'])(\.\.?\/[^"']+)(["']\s*\)?)/g,
        (match, prefix, specifier, suffix) => `${prefix}${withJsExtension(specifier)}${suffix}`,
    );
    await writeTextFileIfChanged(outputFile, `${header}\n${rewrittenOutputText.trimEnd()}\n`);
}

async function runBuild(configRelativePath) {
    const configFile = path.resolve(thisDirectory, configRelativePath);
    const loadedConfig = await loadConfigFromFile(
        { command: "build", mode: "production" },
        configFile,
    );

    if (!loadedConfig) {
        throw new Error(`Could not load Vite config ${configFile}`);
    }

    await build(loadedConfig.config);
}

if (shouldBuild("--desktop") || shouldBuild("--desktop-runtime") || shouldBuild("--ios")) {
    await emitGeneratedPatchGuiModule("kit/ui/resource-client.ts", "patch_gui/resource-client.js");
    await emitGeneratedPatchGuiModule("ui/shared/runtime-install-channel.ts", "patch_gui/runtime-install-channel.js");
    await emitGeneratedPatchGuiModule("ui/shared/mseg.ts", "patch_gui/mseg.js");
    await emitGeneratedPatchGuiModule("ui/shared/effect-output-trim.ts", "patch_gui/effect-output-trim.js");
    await emitGeneratedPatchGuiModule("ui/shared/rack-parameter-descriptors.ts", "patch_gui/rack-parameter-descriptors.js");
    await emitGeneratedPatchGuiModule("ui/shared/result.ts", "patch_gui/result.js");
    await emitGeneratedPatchGuiModule("ui/shared/cosimo-ids.ts", "patch_gui/cosimo-ids.js");
    await emitGeneratedPatchGuiModule("ui/shared/global-tune.ts", "patch_gui/global-tune.js");
    await emitGeneratedPatchGuiModule("ui/shared/enhancer-spectrum.ts", "patch_gui/enhancer-spectrum.js");
    await emitGeneratedPatchGuiModule("ui/shared/voice-enhancer.ts", "patch_gui/voice-enhancer.js");
    await emitGeneratedPatchGuiModule("ui/shared/key-track.ts", "patch_gui/key-track.js");
    await emitGeneratedPatchGuiModule("ui/shared/oscillator-defaults.ts", "patch_gui/oscillator-defaults.js");
    await emitGeneratedPatchGuiModule("ui/shared/target-descriptor.ts", "patch_gui/target-descriptor.js");
    await emitGeneratedPatchGuiModule("ui/shared/modulation-runtime-program.ts", "patch_gui/modulation-runtime-program.js");
    await emitGeneratedPatchGuiModule("ui/shared/modulation-targets.ts", "patch_gui/modulation-targets.js");
    await emitGeneratedPatchGuiModule("ui/shared/lane-modulation-targets.ts", "patch_gui/lane-modulation-targets.js");
    await emitGeneratedPatchGuiModule("ui/shared/lane-slot-params.ts", "patch_gui/lane-slot-params.js");
    await emitGeneratedPatchGuiModule("ui/shared/lane-state.ts", "patch_gui/lane-state.js");
    await emitGeneratedPatchGuiModule("ui/shared/lane-state-v2.ts", "patch_gui/lane-state-v2.js");
    await emitGeneratedPatchGuiModule("ui/shared/user-edit-bus.ts", "patch_gui/user-edit-bus.js");
    await emitGeneratedPatchGuiModule("ui/shared/modulation.ts", "patch_gui/modulation.js");
    await emitGeneratedPatchGuiModule("ui/shared/rack-route-presentation.ts", "patch_gui/rack-route-presentation.js");
    await emitGeneratedPatchGuiModule("ui/shared/articulations.ts", "patch_gui/articulations.js");
    await emitGeneratedPatchGuiModule("ui/shared/articulation-image.ts", "patch_gui/articulation-image.js");
    await emitGeneratedPatchGuiModule("ui/shared/theme.ts", "patch_gui/theme.js");
    await emitGeneratedPatchGuiModule("ui/shared/responsive-layout.ts", "patch_gui/responsive-layout.js");
    await emitGeneratedPatchGuiModule("ui/shared/wavetable-bank.ts", "patch_gui/wavetable-bank.js");
    await emitGeneratedPatchGuiModule("ui/shared/wavetable-display.ts", "patch_gui/wavetable-display.js");
}

if (shouldBuild("--ios")) {
    await copyTextFileIfChanged("ui/ios/runtime-shell.html", "patch_gui/index.ios.html");
    await emitGeneratedPatchGuiModule("ui/ios/runtime-host.js", "patch_gui/index.ios-host.js");
    await runBuild("../ios_auv3/vite.config.mjs");
    await runBuild("./vite.worker.config.mjs");
}

if (shouldBuild("--desktop") || shouldBuild("--desktop-runtime")) {
    if (shouldBuild("--desktop")) {
        await runBuild("./vite.desktop.config.mjs");
    }
    await emitGeneratedPatchGuiModule("ui/desktop/standalone-loader.js", "patch_gui/desktop/index.js");
}
