/***********************************************************************************
 *
 *   A Javascript/Webassembly implementation of the Cmajor processor 'MsegPlayback'.
 *
 *   This class was auto-generated by the Cmajor toolkit.
 *
 *   To use it, construct an instance of this class, and call `initialise()` to
 *   asynchronously prepare it for use. Once initialised, the class provides
 *   appropriate setter/getter methods for reading/writing data to its endpoints,
 *   and an `advance()` method to render the next block.
 *
 *   This roughly mirrors functionality of the cmajor Performer API - see the
 *   C++ API classes and Cmajor docs for more information about how this is used.
 */
class MsegPlayback
{
  /** After constructing one of these objects, call its
   *  initialise() method to prepare it for use.
   */
  constructor()
  {
  }getMemoryRequirements() { return { minimumPages: 82, minimumBytes: 5373952, shared: true, maximumPages: 256 }; }

  async compile()
  {
    return WebAssembly.compile (this._getWasmBytes());
  }

  //==============================================================================
  /** Prepares this processor for use.
   *
   *  @param {number} sessionID - A unique integer ID which will be used for `processor.session`.
   *  @param {number} frequency - The frequency in Hz that the processor will be expected to run at.
   */
  async initialise (sessionID, frequency, options = {})
  {
    if (options === null || typeof options !== "object" || Array.isArray (options))
      throw new TypeError ("initialise(): options must be an object");
    if (options.externalFunctions !== undefined && (options.externalFunctions === null || typeof options.externalFunctions !== "object" || Array.isArray (options.externalFunctions)))
      throw new TypeError ("initialise(): externalFunctions must be an object");
    if (! ((sessionID ^ 0) > 1))
      throw new Error ("initialise() requires a valid non-zero session ID argument");

    if (! (frequency > 1))
      throw new Error ("initialise() requires a valid frequency argument");

      await this._initialiseInternal (sessionID, frequency, options);

    return true;
  }

  //==============================================================================
  /** Advances the processor by a number of frames.
   *
   *  Before calling `advance()` you should use the appropriate functions to
   *  push data and events into the processor's input endpoints. After calling
   *  `advance()` you can use its output endpoint access functions to read the
   *  results.
   *
   *  @param {number} numFrames - An integer number of frames to advance.
   *                              This must be greater than zero.
   */
  advance (numFrames)
  {
    this._advanceInternal (numFrames);
  }

  //==============================================================================
  /** Returns an object which encapsulates the state of the patch at this point.
   *  The state can be restored by passing this object to `restoreState()`.
   */
  getState()
  {
    return { memory: this.byteMemory.slice(0) };
  }

  /** Restores the patch to a state that was previously saved by a call to `getState()`
   */
  restoreState (savedState)
  {
    if (savedState?.memory && savedState.memory?.length === this.byteMemory.length)
      this.byteMemory.set (savedState.memory);
    else
      throw Error ("restoreState(): not a valid state object");
  }

  /** Returns a list of the output endpoints that this processor exposes.
   *  @returns {Array}
   */
  getOutputEndpoints()
  {
    return [
      {
        "endpointID": "out",
        "endpointType": "stream",
        "dataType": {
          "type": "float32"
        },
        "purpose": "audio out",
        "numAudioChannels": 1
      },
      {
        "endpointID": "position",
        "endpointType": "event",
        "dataType": {
          "type": "object",
          "class": "Position",
          "members": {
            "generation": {
              "type": "int32"
            },
            "active": {
              "type": "bool"
            },
            "position": {
              "type": "float32"
            }
          }
        }
      }
    ];
  }

  /** Returns a list of the input endpoints that this processor exposes.
   *  @returns {Array}
   */
  getInputEndpoints()
  {
    return [
      {
        "endpointID": "trigger",
        "endpointType": "event",
        "dataType": {
          "type": "int32"
        }
      },
      {
        "endpointID": "legatoTrigger",
        "endpointType": "event",
        "dataType": {
          "type": "int32"
        }
      },
      {
        "endpointID": "noteOff",
        "endpointType": "event",
        "dataType": {
          "type": "int32"
        }
      },
      {
        "endpointID": "playback",
        "endpointType": "event",
        "dataType": {
          "type": "object",
          "class": "Playback",
          "members": {
            "holdFinalValue": {
              "type": "bool"
            },
            "loopEnabled": {
              "type": "bool"
            },
            "loopStart": {
              "type": "float32"
            },
            "loopEnd": {
              "type": "float32"
            },
            "ignoreNoteOff": {
              "type": "bool"
            },
            "legatoRestarts": {
              "type": "bool"
            }
          }
        }
      },
      {
        "endpointID": "duration",
        "endpointType": "value",
        "dataType": {
          "type": "float32"
        }
      }
    ];
  }

  /** Sends an event of type `int32` to endpoint "trigger".
   *  @param {number} eventValue - The event to be added to the queue for this endpoint.
   */
  sendInputEvent_trigger (eventValue)
  {
    this.instance.exports._sendEvent_trigger (this.stateAddress, eventValue);
  }

  /** Sends an event of type `int32` to endpoint "legatoTrigger".
   *  @param {number} eventValue - The event to be added to the queue for this endpoint.
   */
  sendInputEvent_legatoTrigger (eventValue)
  {
    this.instance.exports._sendEvent_legatoTrigger (this.stateAddress, eventValue);
  }

  /** Sends an event of type `int32` to endpoint "noteOff".
   *  @param {number} eventValue - The event to be added to the queue for this endpoint.
   */
  sendInputEvent_noteOff (eventValue)
  {
    this.instance.exports._sendEvent_noteOff (this.stateAddress, eventValue);
  }

  /** Sends an event of type `kit::mseg::Playback` to endpoint "playback".
   *  @param {Object} eventValue - The event to be added to the queue for this endpoint.
   */
  sendInputEvent_playback (eventValue)
  {
    this._pack_o6_Playback_holdFinalValue_b_loopEnabled_b_loopStart_f32_loopEnd_f32_ignoreNoteOff_b_legatoRestarts_b (this.scratchSpaceAddress, eventValue);
    this.instance.exports._sendEvent_playback (this.stateAddress, this.scratchSpaceAddress);
  }

  /** Sets the value of endpoint "duration".
   *  @param {Object} newValue - The new value, whose type will depend on the endpoint type
   *  @param {number} numFramesToReachValue - If this is non-zero and the type is scalar,
   *                                          this applies a ramp to reach the new value.
  */
  setInputValue_duration (newValue, numFramesToReachValue)
  {
    this._pack_f32 (this.scratchSpaceAddress, newValue);
    this.instance.exports._setValue_duration (this.stateAddress, this.scratchSpaceAddress, numFramesToReachValue);
  }

  /** Returns a frame from the output stream "out"
   *
   * @param {number} frameIndex - the index of the frame to fetch
   */
  getOutputFrame_out (frameIndex)
  {
    return this._getOutputFrameInternal_out (frameIndex);
  }

  /** Copies frames from the output stream "out" into a destination array.
   *
   * @param {Array} destChannelArrays   - An array of arrays (one per channel) into
   *                                      which the samples will be copied
   * @param {number} maxNumFramesToRead - The maximum number of frames to copy
   * @param {number} destChannel        - The channel to start writing from
   */
  getOutputFrames_out (destChannelArrays, maxNumFramesToRead, destChannel)
  {
    this._getOutputFramesInternal_out (destChannelArrays, maxNumFramesToRead, destChannel);
  }

  /** Returns the number of events available for endpoint "position" */
  getOutputEventCount_position()
  {
    return this._unpackEventCountInternal_position();
  }

  /** Resets the FIFO for event endpoint "position" */
  resetOutputEventCount_position()
  {
    this._resetEventCountInternal_position();
  }

  /** Returns one of the events from the FIFO for endpoint "position"
   *  @param {number} index - The index of the event to return
  */
  getOutputEvent_position (index)
  {
    return this._readEventInternal_position (index);
  }

  //==============================================================================
  // Code beyond this point is private internal implementation detail

  //==============================================================================
  /** @access private */
  async _initialiseInternal (sessionID, frequency, options)
  {
    this.stateAddress = 5245120;
    this.scratchSpaceAddress = 5246368;

    const requirements = this.getMemoryRequirements();
    const memory = options.memory !== undefined ? options.memory
      : (requirements.shared ? undefined : new WebAssembly.Memory ({ initial: requirements.minimumPages }));
    if (! (memory instanceof WebAssembly.Memory))
      throw new TypeError ("initialise(): shared memory must be supplied as a WebAssembly.Memory");
    if ((typeof SharedArrayBuffer !== "undefined" && memory.buffer instanceof SharedArrayBuffer) !== requirements.shared)
      throw new TypeError ("initialise(): memory sharedness does not match generated module");
    if (memory.buffer.byteLength < requirements.minimumBytes)
      throw new RangeError ("initialise(): memory is smaller than the compiler's program region");
    const stack = new WebAssembly.Global ({ value: "i32", mutable: true }, 5245120);
    const imports = {
      env: {
        __proto__: null,
        __linear_memory: memory,
        __memory_base: 0,
        __stack_pointer: stack,
        __table_base: 0,
        memcpy:  (dst, src, len) => { this.byteMemory.copyWithin (dst, src, src + len); return dst; },
        memmove: (dst, src, len) => { this.byteMemory.copyWithin (dst, src, src + len); return dst; },
        memset:  (dst, value, len) => { this.byteMemory.fill (value, dst, dst + len); return dst; }
      },
    };

    const module = options.module !== undefined ? options.module : await WebAssembly.compile (this._getWasmBytes());
    if (! (module instanceof WebAssembly.Module))
      throw new TypeError ("initialise(): module must be a WebAssembly.Module");
    const identities = WebAssembly.Module.customSections (module, "cmajor.wrapper");
    if (identities.length !== 1 || String.fromCharCode (...new Uint8Array (identities[0])) !== "3167047660733228549:5245120:5245856:5246368:82")
      throw new TypeError ("initialise(): module does not match this generated wrapper");
    const externalFunctions = options.externalFunctions ?? {};
    const requiredFunctions = WebAssembly.Module.imports (module)
      .filter (entry => entry.kind === "function" && entry.module === "env" && ! Object.hasOwn (imports.env, entry.name))
      .map (entry => entry.name);
    for (const name of requiredFunctions)
    {
      if (! Object.hasOwn (externalFunctions, name) || typeof externalFunctions[name] !== "function")
        throw new TypeError ("initialise(): missing external function " + name);
      imports.env[name] = externalFunctions[name];
    }
    for (const name of Object.keys (externalFunctions))
      if (! requiredFunctions.includes (name))
        throw new TypeError ("initialise(): undeclared external function " + name);
    this.instance = await WebAssembly.instantiate (module, imports);
    const exports = this.instance.exports;
    const memoryBuffer = exports.memory?.buffer || memory.buffer;
    const memoryDataView = new DataView (memoryBuffer, 0, requirements.minimumBytes);
    const byteMemory = new Uint8Array (memoryBuffer, 0, requirements.minimumBytes);
    this.byteMemory = byteMemory;
    this.memoryDataView = memoryDataView;

    exports.initialise?.(this.stateAddress, this.scratchSpaceAddress, sessionID, frequency);

    const advanceFn = exports.advanceBlock ? ((numFrames) => exports.advanceBlock (5245120, 5245856, numFrames))
                                           : (() => exports.advanceOneFrame (5245120, 5245856));

    this.reset = () => {
       byteMemory.fill (0, 5245120, 5245856);
       byteMemory.fill (0, 5246368, 5246368 + 4);
       exports.initialise?.(this.stateAddress, this.scratchSpaceAddress, sessionID, frequency);
    };

    this._advanceInternal = (numFrames) => {
      byteMemory.fill (0, 5245856, 5245856 + numFrames * 4);
      advanceFn (numFrames);
    };

    this._getOutputFrameInternal_out = (frameIndex) => { return memoryDataView.getFloat32 (5245856 + frameIndex * 4, true); };

    this._getOutputFramesInternal_out = (destChannelArrays, maxNumFramesToRead, destChannel) => {
      if (maxNumFramesToRead > 128)
        maxNumFramesToRead = 128;

      const channelsToCopy = Math.min (1, destChannelArrays.length - destChannel);
      let source = 5245856;

      for (let frame = 0; frame < maxNumFramesToRead; ++frame)
      {
        for (let channel = 0; channel < channelsToCopy; ++channel)
          destChannelArrays[destChannel + channel][frame] = memoryDataView.getFloat32 (source + 4 * channel, true);

        source += 4;
      }
    };

    this._unpackEventCountInternal_position = () => { return memoryDataView.getInt32 (5245204, true); };
    this._resetEventCountInternal_position = () => { memoryDataView.setInt32 (5245204, 0, true); };

    this._readEventInternal_position = (index) => {
      const eventAddress = 5245208 + (20 * index);
      const frame = memoryDataView.getInt32 (eventAddress, true);
      return { frame, typeIndex: 0, event: this._unpack_o3_Position_generation_i32_active_b_position_f32 (eventAddress + 8) };
    };

    this._pack_o6_Playback_holdFinalValue_b_loopEnabled_b_loopStart_f32_loopEnd_f32_ignoreNoteOff_b_legatoRestarts_b = (address, newValue) => {
      memoryDataView.setUint8 (address, newValue.holdFinalValue ? (1 | memoryDataView.getUint8(address)) : (254 & memoryDataView.getUint8(address)));
      memoryDataView.setUint8 (address + 1, newValue.loopEnabled ? (1 | memoryDataView.getUint8(address + 1)) : (254 & memoryDataView.getUint8(address + 1)));
      memoryDataView.setFloat32 (address + 4, newValue.loopStart, true);
      memoryDataView.setFloat32 (address + 8, newValue.loopEnd, true);
      memoryDataView.setUint8 (address + 12, newValue.ignoreNoteOff ? (1 | memoryDataView.getUint8(address + 12)) : (254 & memoryDataView.getUint8(address + 12)));
      memoryDataView.setUint8 (address + 13, newValue.legatoRestarts ? (1 | memoryDataView.getUint8(address + 13)) : (254 & memoryDataView.getUint8(address + 13)));
    };

    this._pack_f32 = (address, newValue) => {
      memoryDataView.setFloat32 (address, newValue, true);
    };

    this._unpack_o3_Position_generation_i32_active_b_position_f32 = (address) => {
      return { "generation": memoryDataView.getInt32 (address, true), "active": ((memoryDataView.getUint8 (address + 4) & 1) !== 0), "position": memoryDataView.getFloat32 (address + 8, true) };
    };
  }

  /** @access private */
  _getWasmBytes()
  {
    return new Uint8Array([0,97,115,109,1,0,0,0,1,163,128,128,128,0,6,96,2,127,127,0,96,1,125,1,125,96,1,127,1,127,96,2,127,127,1,125,96,3,127,127,127,0,96,4,127,127,127,124,0,2,95,4,3,101,110,118,15,95,95,
      108,105,110,101,97,114,95,109,101,109,111,114,121,2,3,82,128,2,3,101,110,118,16,99,109,97,106,95,95,100,97,116,97,95,95,115,105,122,101,0,2,3,101,110,118,16,99,109,97,106,95,95,100,97,116,97,95,95,114,
      101,97,100,0,3,3,101,110,118,15,95,95,115,116,97,99,107,95,112,111,105,110,116,101,114,3,127,1,3,137,128,128,128,0,8,0,1,0,0,0,4,5,4,7,141,129,128,128,0,7,18,95,115,101,110,100,69,118,101,110,116,95,116,
      114,105,103,103,101,114,0,2,24,95,115,101,110,100,69,118,101,110,116,95,108,101,103,97,116,111,84,114,105,103,103,101,114,0,4,18,95,115,101,110,100,69,118,101,110,116,95,110,111,116,101,79,102,102,0,5,
      19,95,115,101,110,100,69,118,101,110,116,95,112,108,97,121,98,97,99,107,0,6,18,95,115,101,116,86,97,108,117,101,95,100,117,114,97,116,105,111,110,0,7,10,105,110,105,116,105,97,108,105,115,101,0,8,12,97,
      100,118,97,110,99,101,66,108,111,99,107,0,9,12,129,128,128,128,0,1,10,133,139,128,128,0,8,65,1,1,125,32,0,65,1,58,0,32,32,0,65,0,54,2,40,32,0,65,0,54,2,28,32,0,32,0,40,2,24,65,1,106,54,2,24,67,0,0,0,0,
      16,131,128,128,128,0,33,2,32,0,65,0,58,0,34,32,0,32,2,56,2,44,11,208,1,3,2,125,1,127,2,125,67,0,0,0,0,33,1,2,64,65,0,16,128,128,128,128,0,65,131,16,71,13,0,65,0,67,0,224,255,68,67,0,0,0,0,32,0,32,0,67,
      0,0,0,0,93,27,67,0,224,255,68,148,32,0,67,0,0,128,63,94,27,34,2,142,252,0,34,3,16,129,128,128,128,0,33,0,65,0,32,3,65,1,106,16,129,128,128,128,0,34,1,32,2,32,3,178,147,34,2,67,0,0,0,63,148,65,0,32,3,65,
      2,106,16,129,128,128,128,0,34,4,32,0,147,32,2,32,0,32,0,146,32,1,67,0,0,160,192,148,146,32,4,67,0,0,128,64,148,146,65,0,32,3,65,3,106,16,129,128,128,128,0,34,5,147,32,2,32,5,32,1,67,0,0,64,64,148,32,0,
      147,32,4,67,0,0,64,64,148,147,146,148,146,148,146,148,146,33,1,11,32,1,11,76,1,1,125,2,64,32,0,45,0,36,69,13,0,32,0,65,1,58,0,32,32,0,65,0,54,2,40,32,0,65,0,54,2,28,32,0,32,0,40,2,24,65,1,106,54,2,24,67,
      0,0,0,0,16,131,128,128,128,0,33,2,32,0,65,0,58,0,34,32,0,32,2,56,2,44,11,11,41,0,2,64,32,0,45,0,32,69,13,0,32,0,45,0,33,65,1,113,69,13,0,32,0,45,0,35,65,1,113,13,0,32,0,65,1,58,0,34,11,11,191,1,4,1,127,
      2,125,2,127,1,125,32,1,45,0,1,33,2,32,1,42,2,4,33,3,32,1,42,2,8,33,4,32,1,45,0,12,33,5,32,1,45,0,13,33,6,32,0,32,1,45,0,0,65,1,113,58,0,37,32,0,32,6,65,1,113,58,0,36,32,0,32,5,65,1,113,58,0,35,32,0,67,
      0,0,128,63,67,0,0,0,0,32,3,32,3,67,0,0,0,0,93,27,32,3,67,0,0,128,63,94,27,34,3,67,0,0,128,63,67,0,0,0,0,32,4,32,4,67,0,0,0,0,93,27,32,4,67,0,0,128,63,94,27,34,4,32,3,32,4,94,27,34,7,56,2,52,32,0,32,3,32,
      4,32,3,32,4,93,27,34,3,56,2,48,32,0,32,2,32,7,32,3,147,67,189,55,134,53,94,113,58,0,33,11,68,1,1,125,2,64,32,0,40,2,80,13,0,32,0,32,0,40,2,0,65,1,106,54,2,0,11,32,1,42,2,0,33,3,32,0,32,2,65,1,32,2,65,1,
      75,27,34,2,54,2,80,32,0,32,3,32,0,42,2,72,147,32,2,178,149,56,2,76,11,31,0,32,0,65,128,128,128,252,3,54,2,40,32,0,65,1,58,0,37,65,0,32,3,57,3,128,128,128,128,0,11,209,5,7,2,127,1,124,3,127,3,125,1,127,
      4,125,1,127,35,128,128,128,128,0,65,16,107,34,3,36,128,128,128,128,0,2,64,32,0,40,2,4,34,4,32,2,70,13,0,65,0,43,3,128,128,128,128,0,34,5,68,0,0,0,0,0,0,78,64,163,252,2,34,6,65,1,32,6,65,1,74,27,33,7,32,
      0,65,216,0,106,33,8,67,0,0,128,63,32,5,182,34,9,149,33,10,3,64,2,64,2,64,32,0,40,2,0,34,6,13,0,32,0,42,2,64,33,11,12,1,11,32,0,42,2,72,33,11,2,64,32,0,40,2,80,34,12,69,13,0,32,0,32,12,65,127,106,34,12,
      54,2,80,32,0,32,11,32,0,42,2,76,146,34,11,56,2,72,32,12,13,0,32,0,32,6,65,127,106,54,2,0,11,32,0,32,11,56,2,64,11,32,0,32,11,56,2,56,2,64,2,64,32,0,40,2,60,65,127,71,13,0,67,0,0,0,0,33,11,12,1,11,32,0,
      42,2,40,33,13,2,64,2,64,2,64,2,64,32,0,45,0,32,69,13,0,32,0,32,13,16,131,128,128,128,0,34,14,56,2,44,32,0,45,0,33,65,1,115,32,0,45,0,34,114,65,1,113,34,6,69,13,1,32,13,67,0,0,128,63,96,69,13,1,32,0,65,
      0,58,0,32,11,32,0,45,0,37,13,1,67,0,0,0,0,33,11,65,0,33,12,12,2,11,32,13,67,0,0,128,63,32,11,32,10,32,11,32,10,94,27,32,9,148,149,146,33,11,2,64,2,64,32,6,69,13,0,32,11,67,0,0,128,63,32,11,67,0,0,128,63,
      93,27,33,11,12,1,11,2,64,32,11,32,0,42,2,52,34,15,67,189,55,134,53,146,95,69,13,0,32,11,32,15,32,11,32,15,93,27,33,11,12,1,11,32,0,42,2,48,34,16,32,11,32,15,147,34,11,32,15,32,16,147,34,15,32,11,32,15,
      149,142,148,147,146,33,11,11,32,0,32,11,56,2,40,65,1,33,12,32,14,67,0,0,0,0,146,33,11,12,1,11,65,0,33,12,32,0,42,2,44,67,0,0,0,0,146,33,11,11,2,64,32,0,40,2,28,34,6,13,0,32,0,40,2,24,33,17,32,3,32,12,58,
      0,12,2,64,32,0,40,2,84,34,6,65,31,74,13,0,32,8,32,6,65,20,108,106,34,6,65,16,106,67,0,0,128,63,67,0,0,0,0,32,13,32,13,67,0,0,0,0,93,27,32,13,67,0,0,128,63,94,27,56,2,0,32,6,32,4,54,2,0,32,6,65,8,106,32,
      17,54,2,0,32,6,65,4,106,65,0,54,2,0,32,6,65,12,106,32,3,45,0,12,58,0,0,32,0,40,2,4,33,4,32,0,40,2,84,33,6,11,32,0,32,6,65,1,106,54,2,84,32,7,33,6,11,32,0,65,1,54,2,60,32,0,32,6,65,127,106,54,2,28,11,32,
      1,32,4,65,2,116,106,32,11,56,2,0,32,0,32,0,40,2,4,65,1,106,34,4,54,2,4,32,4,32,2,71,13,0,11,11,32,0,65,0,54,2,4,32,3,65,16,106,36,128,128,128,128,0,11,11,142,128,128,128,0,1,0,65,0,11,8,0,0,0,0,0,0,0,0,
      0,244,129,128,128,0,7,108,105,110,107,105,110,103,2,8,200,129,128,128,0,12,0,32,2,18,95,115,101,110,100,69,118,101,110,116,95,116,114,105,103,103,101,114,0,2,3,19,46,76,107,105,116,95,95,109,115,101,103,
      95,95,115,97,109,112,108,101,0,16,0,0,16,1,0,32,4,24,95,115,101,110,100,69,118,101,110,116,95,108,101,103,97,116,111,84,114,105,103,103,101,114,0,32,5,18,95,115,101,110,100,69,118,101,110,116,95,110,111,
      116,101,79,102,102,0,32,6,19,95,115,101,110,100,69,118,101,110,116,95,112,108,97,121,98,97,99,107,0,32,7,18,95,115,101,116,86,97,108,117,101,95,100,117,114,97,116,105,111,110,0,32,8,10,105,110,105,116,
      105,97,108,105,115,101,1,2,14,46,76,103,95,95,102,114,101,113,117,101,110,99,121,0,0,8,0,32,9,12,97,100,118,97,110,99,101,66,108,111,99,107,2,16,0,5,151,128,128,128,0,1,19,46,98,115,115,46,46,76,103,95,
      95,102,114,101,113,117,101,110,99,121,3,0,0,193,128,128,128,0,10,114,101,108,111,99,46,67,79,68,69,5,13,0,45,1,0,88,2,0,145,1,3,0,160,1,3,0,189,1,3,0,232,1,3,0,203,2,1,3,172,5,9,0,7,196,5,11,7,207,5,11,
      3,230,5,9,0,0,179,7,1,7,255,10,11,0,157,129,128,128,0,15,116,97,114,103,101,116,95,102,101,97,116,117,114,101,115,9,43,11,98,117,108,107,45,109,101,109,111,114,121,43,15,98,117,108,107,45,109,101,109,111,
      114,121,45,111,112,116,43,22,99,97,108,108,45,105,110,100,105,114,101,99,116,45,111,118,101,114,108,111,110,103,43,10,109,117,108,116,105,118,97,108,117,101,43,15,109,117,116,97,98,108,101,45,103,108,111,
      98,97,108,115,43,19,110,111,110,116,114,97,112,112,105,110,103,45,102,112,116,111,105,110,116,43,15,114,101,102,101,114,101,110,99,101,45,116,121,112,101,115,43,8,115,105,103,110,45,101,120,116,43,7,115,
      105,109,100,49,50,56,0,61,14,99,109,97,106,111,114,46,119,114,97,112,112,101,114,51,49,54,55,48,52,55,54,54,48,55,51,51,50,50,56,53,52,57,58,53,50,52,53,49,50,48,58,53,50,52,53,56,53,54,58,53,50,52,54,
      51,54,56,58,56,50,]);
  }
}


export default MsegPlayback;
